- unique_initial_sample:
    seeds: [
    [
        "COc1nn(C)cc1CNC(=O)N[C@@H](C)c1cccc2ccccc12",
        "Cc1ccc(NC(=O)[C@H]2CCCN2C(=O)Cc2ccccc2)c(O)c1",
        "COc1ccnc(NC[C@]23C[C@](NC(=O)[C@@H]4C[C@@H]4C)(C2)C(C)(C)O3)n1",
        "Cc1csc(N2CCN(C(=O)c3ccc(C(=O)NC4CC4)cc3)C[C@H]2C)n1",
        "O=C(N[C@@H](CN1CCCC1=O)c1ccccc1)[C@@H]1CCCN(C(=O)Cc2ccc(F)cc2)C1",
        "O=C(Nc1cccnc1)c1cccc(S(=O)(=O)N2CCCCC2)c1",
        "Cc1cc([N+](=O)[O-])c(C)c(S(=O)(=O)N(C)[C@@H]2C[N@H+]3CC[C@@H]2CC3)c1",
        "Cc1ccc(C(=O)N2CC[C@H](c3cc(O)[nH]n3)C2)cc1",
        "Cc1cccc([C@@H]2CCCN2C(=O)NCc2ccc(S(C)(=O)=O)cc2)n1",
        "Cc1ccc(C[C@@H](C)NC(=O)N2CCS(=O)(=O)CC2)s1",
    ],
    [
        "O=C([O-])c1cccc(CS(=O)(=O)N2CC[C@H](O)C2)c1",
        "O=C(CCc1cccc(Br)c1)N[C@H]1C[C@H](Cn2ccnc2)C[C@@H]1O",
        "Cc1ccccc1CNc1cc(C(N)=O)ccc1Cl",
        "COc1ccc(OC)c([C@@H]2CCCN2C(=O)c2ccnc(OC)n2)c1",
        "Cc1ccncc1N1CCN(C(=O)c2cc(N3CCCC3=O)ccc2F)CC1",
        "O[C@@]1(c2nc(Cc3ccccc3)no2)CCc2ccccc2C1",
        "COC[C@@H]1CN(C(=O)c2ncoc2C2CC2)CCO1",
        "COc1cccc(C[C@@]2(C(=O)N[C@@H]3CCCC[C@H]3O)C[C@@H]3CC[C@H]2C3)c1",
        "CCc1nocc1CN(C)C(=O)c1ccc2[nH]c(=O)n(C)c2c1",
        "CC[NH+]1CCN([C@@H]2CCN(C(=O)Cc3cncs3)C2)CC1",
    ],
    [
        "CC(C)C[C@H]1C(=O)NCCN1C(=O)c1cc(O)nc(C(C)C)c1",
        "O=C(Cc1ccc(-n2cnnn2)cc1)Nc1cnn(C[C@@H]2CCCO2)c1",
        "Cc1nc(NCc2cccc(N3CCCCC3=O)c2)cc(-c2ccccn2)n1",
        "O=C(c1ccnn1C1CCCC1)N1CCN(c2cncc3ccccc23)CC1",
        "Cc1ccc(-c2nnn(CC(=O)N[C@H]3CCCC34CCOCC4)n2)cc1",
        "N#Cc1ccc(C(=O)N2CCCC[C@H]2C(=O)[O-])cc1",
        "Cc1cc(C(=O)N2CCC[C@H](c3nc(-c4cccc(F)c4)no3)C2)c2n[nH]cc2c1",
        "Cc1c(CC(=O)N2CC[C@@H](S(C)(=O)=O)C2)nnn1-c1ccccc1",
        "CC(C)CCOC1CCN(C(=O)c2ccc(C(=O)[O-])cn2)CC1",
        "C[C@H]1CN(C(=O)Cn2cc(NC(=O)NC[C@](C)(O)c3cccc(Cl)c3)cn2)C[C@H](C)O1",
    ],
    [
        "CCc1nn(C)cc1C(=O)N[C@@H]1c2ccccc2C[C@@H]1O",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
        "C=CCC1(C(=O)N2CC[C@@H](c3nc(C)no3)C2)CCOCC1",
        "CC[C@@H](CC#N)NC(=O)c1nnc2ccc(Br)cn12",
        "O=C(c1cccc(Cn2ccnn2)c1)N1C[C@H]2COC[C@@H]2C1",
        "C[C@H](Cc1nc(-c2ccccc2)no1)NC(=O)c1cccc(C#N)c1",
        "O=C(c1ccccc1OC(F)F)N1CCN(C(=O)[C@H](O)c2ccccc2Cl)CC1",
        "C[C@H]1CN(c2nnc(-c3ccccc3)n2C[C@@H]2CCCO2)CCS1",
        "Cc1cc(C(=O)N2CC[C@@](F)(c3cccc(C(F)(F)F)c3)C2)nc2nc(O)[nH]c(=O)c12",
        "CNC(=O)C[C@@H]1CN(C(=O)NCc2cccc(C(F)(F)F)c2)C[C@@H]1O",
    ],
    [
        "Cc1cc(C)cc(-n2nc(C(=O)N3CCCC[C@@H]3c3cn[nH]c3)cc2C)c1",
        "CCc1cccc(C)c1NS(=O)(=O)c1cnc2n1CCC2",
        "O=C(Nc1cnn(-c2ncccc2F)c1)C1(F)CCC1",
        "CC1(C)C[C@H](NC(=O)N2CCC(c3ccc(O)cc3)CC2)CCO1",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "O=C(NC[C@H]1CCC[N@H+](Cc2ncon2)C1)c1cccc(-n2cncn2)c1",
        "Cc1cccc2nc(N3CC[C@H](S(C)(=O)=O)C3)sc12",
        "CC[C@H](C)[C@@H](NC(C)=O)C(=O)N1CCC(c2noc(-c3ccccc3OC)n2)CC1",
        "CCc1onc(C)c1NS(=O)(=O)c1ccc(OCC(=O)[O-])c(Cl)c1",
        "Cc1ccnc2ccc(C(=O)N3Cc4ccccc4C[C@@H]3C(N)=O)cc12",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "NC(=O)C1CCN(c2ccccc2NC(=O)[C@@H]2Cc3cc(F)ccc3O2)CC1",
        "CNC(=O)[C@@H]1CCC[C@H]1[NH2+][C@H]1[C@@H]2CCO[C@@H]2C12CCCC2",
        "CCc1cc(N2CC[C@@H](n3cc(C(=O)[O-])nn3)C2)c2ccccc2n1",
        "O=C1CCc2cc(C(=O)N3CCOc4cccc(F)c4C3)c(F)cc2N1",
        "N#Cc1cccc(-n2ccc(-c3nc(-c4n[nH]c5ccccc45)no3)n2)c1",
        "Cc1ccc(F)cc1C(=O)NC(C)(C)c1cn(C)nn1",
        "CCOc1c(Cl)cc(CNc2ccc3nc(C)nn3n2)cc1OC",
        "O=C(C[C@@H]1CCc2ccccc2C1)N1CCC(c2nnc3n2CC[NH2+]C3)CC1",
        "Cc1ccsc1S(=O)(=O)NC(=O)C(F)(F)C1CCOCC1",
    ],
    [
        "O=C(COc1ccc(F)cc1)N[C@H]1CCC(=O)N[C@H]1c1ccccc1",
        "O=C([C@H](CO)c1ccccc1)N(Cc1ccccc1F)C1CC1",
        "CCS(=O)(=O)N1CCN(c2nnc(-c3cccn3C)n2C)CC1",
        "COCC1(C)CCN(C(=O)Nc2cnn(-c3ncccn3)c2)CC1",
        "c1cc(NCc2ccc(C3CCC3)nc2)cc(-c2nnc[nH]2)c1",
        "O=C(NCc1ccc(Br)s1)NC[C@H]1CCCO1",
        "O=C(NCC(=O)N1CCC(c2noc3cc(F)ccc23)CC1)c1cccnc1",
        "O=C([O-])C[C@H](NC(=O)c1ccc2cc[nH]c2c1)c1cccs1",
        "Cc1nc(CN(C)C(=O)C[C@H]2CCCC[C@H]2O)no1",
        "CS(=O)(=O)[C@@H]1CCN(C(=O)c2cccnc2N2CCCC2)C1",
    ],
    [
        "CCn1nc(C)c(C[N@H+]2CCc3[nH]cnc3[C@@H]2c2ccc(F)cc2)n1",
        "Cc1ccncc1N1CCN(C(=O)c2cc(N3CCCC3=O)ccc2F)CC1",
        "Cc1nc(N2CCOCC2)ccc1NC(=O)N1CC(CO)C1",
        "COc1ccc([C@H](NC(=O)NCc2nc(-c3ccco3)n[nH]2)c2ccc(C)cc2)cc1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)Nc1cnn(CCOC)c1",
        "Cc1cccc(CN(C)C(=O)c2cnn3ccc(C)cc23)c1",
        "CNC(=O)Cn1nc(NC(=O)N[C@H](C)c2ccc(OCC(=O)NC3CC3)cc2)cc1C",
        "CC1CCN(C(=O)C2CCN(C(=O)Nc3cccc(-c4ccc5c(c4)CCO5)c3)CC2)CC1",
        "COc1cc(CC(=O)N2CCOC[C@H]2c2c(C)n[nH]c2C)ccc1C",
        "CCn1cc(Cl)cc1C(=O)N[C@@H](C(=O)[O-])C(C)C",
    ],
    [
        "CCn1nc(C)c(Cn2cnc3c(sc4ncccc43)c2=O)n1",
        "C[C@@H]1c2cc3c(cc2C2(CCCC2)CN1C(=O)Nc1ccc(F)c(C(N)=O)c1)OCCO3",
        "Cc1c(Br)cc(F)cc1C(=O)N(CC(N)=O)CC(C)C",
        "CS(=O)(=O)NCc1cn(-c2cccc(C(F)(F)F)c2)nn1",
        "CCc1ccc(O)c(NC(=O)C[C@@H](C)[C@H]2CCC[NH2+]C2)c1",
        "Cc1nn(CC(=O)N[C@H]2CCOc3ccc(F)cc32)cc1-c1ccccc1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COc1cccc(C(=O)NCC(=O)N[C@@H]2CCC(=O)N[C@H]2[C@@H]2CCCO2)c1",
        "O=C(Cn1cnc2scc(-c3ccc(Br)cc3)c2c1=O)N1CCCC1",
    ],
    [
        "CC(=O)N1c2ccc(S(=O)(=O)N3CC4(CCC4)c4c(F)cccc43)cc2C[C@@H]1C",
        "Cn1ccnc1[C@H]1CCN(C(=O)Cc2n[nH]c(=O)c3ccccc23)C1",
        "COC[C@H](Nc1ccc2nc(C3CC3)oc2c1)C1CCOCC1",
        "Cc1cc(S(N)(=O)=O)cc(C(=O)NC[C@@H]2CCCO2)c1C",
        "Cc1ccc(NC(=O)c2ccc3[nH]c(=O)n(C)c3c2)cc1-c1ncco1",
        "CNC(=O)Cn1nc(NC(=O)N[C@H](C)c2ccc(OCC(=O)NC3CC3)cc2)cc1C",
        "C[C@@H](NC(=O)N[C@H]1CCCN(Cc2ccccc2)C1=O)c1ccccn1",
        "CCc1csc(CC(=O)N[C@@H](CN2CCOCC2)c2ccc(C)cc2)n1",
        "O=C(NCCc1ccc2cn[nH]c2c1)N1CCCC1",
        "Cc1csc([C@H]2CCCN2C(=O)c2ccc3cc[nH]c3n2)n1",
    ],
    [
        "O=C(CN1CCc2ccccc2C1=O)NCc1ccccc1",
        "Cc1nc2c(C(=O)N3CCc4ccccc4[C@@H]3c3ccccc3)ccnc2[nH]1",
        "O=C(CNC(=O)[C@@H]1CCC[NH2+]1)Nc1ccc2c[nH]nc2c1",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "COc1cc(Cc2noc(C3(Cc4ccccc4F)CC3)n2)ccc1S(C)(=O)=O",
        "Cn1ccnc1[C@]1(CNC(=O)c2ccc(-c3nnn[nH]3)cn2)NC(=O)NC1=O",
        "Cc1n[nH]c(C)c1CC(=O)N1CCO[C@H](c2ccccc2)C1",
        "O=C(CC[C@@H]1CCCOC1)NS(=O)(=O)Cc1cccc(F)c1",
        "Cc1nnc(-c2ccc(NC(=O)N3CCCC3)cc2)o1",
        "O=C1C[C@@H](Cc2ccc(C(=O)N3CCC[C@@H]3CO)cc2)C(=O)N1",
    ],
    [
        "Cc1ccccc1Cc1noc(C2CCN(C(=O)N(C)C)CC2)n1",
        "CC(C)Cc1cc(N2CCC(Cc3nncn3C)CC2)ncn1",
        "CCNC(=O)N1CCC[C@@H]1c1nc(-c2ccccc2)c(C(C)C)o1",
        "COc1cc(C)c([C@H](C)NC(=O)N2CCC2)cc1OC",
        "O=C(NCc1ccc2c(c1)OCCO2)NC1CCN(C(=O)c2ccccc2)CC1",
        "COc1ccc(C(=O)N2CCCC2)cc1NC(=O)N[C@@H]1c2ccccc2C[C@@H]1O",
        "CN(C(=O)[C@@H]1[C@H]2[C@H]3C=C[C@H]([C@H]4C(=O)N(Cc5ccccc5)C(=O)[C@H]34)[C@@H]12)[C@H]1C[C@H](c2ccccc2)C1",
        "C[NH+]1CCC(CNC(=O)CNC(=O)c2ccc3ccccc3c2)CC1",
        "CCn1cc(C(=O)NCC2([C@H](O)c3ccccc3)CC2)c2ccccc21",
        "Cc1ccc(S(=O)(=O)N[C@@H]2C=C[C@H](C(=O)[O-])C2)cc1C",
    ],
    [
        "C[C@@H](c1ccc(F)c(F)c1)N(C)C(=O)c1cn(Cc2cccc(F)c2)nn1",
        "O=C(NCc1ncccn1)c1ccc2c(c1)C[C@H](c1ccccc1)OC2=O",
        "CC(C)C[C@H](NC(=O)Cc1ccc(-c2ccccc2)cc1)c1nc(-c2nnc[nH]2)no1",
        "CC1CCN(S(=O)(=O)N[C@H]2CCN(c3ccccc3)C2=O)CC1",
        "O=C(CCCc1c[nH]c2ccccc12)NCC(=O)NCc1ccco1",
        "Cn1ccc2ccc(NC(=O)N3CC[C@H](C(C)(C)C)C3)cc2c1=O",
        "O=C(NCC(=O)N1CCc2ccccc2C1)c1ccc2c(=O)n3c(nc2c1)CCCCC3",
        "Cc1ccc(NC(=O)N2CCN(C(=O)c3ccoc3C(F)(F)F)CC2)cc1",
        "CC1(c2nc(-c3ccnc(N4CCOCC4)c3)no2)CC1",
        "C[C@]1(C(=O)[O-])CCC[N@@H+]1CC(=O)Nc1ccc(F)cc1Cl",
    ],
    [
        "c1cncc(-c2nc3c(c(NCc4nc(C5CC5)no4)n2)CCC3)c1",
        "O=C(NCc1ccc(Oc2cccnc2)c(F)c1)N1CC[C@H](C2CCOCC2)C1",
        "CCCNC(=O)C[NH+]1CCC(Nc2cc(C(F)(F)F)nc3ncnn23)CC1",
        "O=C(NCc1cc2c([nH]c1=O)CCC2)N[C@H](c1cccc(C(F)(F)F)c1)C1CCOCC1",
        "CS(=O)(=O)c1ccc(NC(=O)NC2CCOCC2)cn1",
        "O=C(Nc1cccc2ccccc12)N[C@H]1CC[NH2+]C1",
        "COc1nn(C)cc1CNC(=O)N[C@@H](C)c1cccc2ccccc12",
        "O=C(c1c[nH]nc1-c1cc2ccccc2o1)N1CCO[C@]2(CCCOC2)C1",
        "C=C(C)CCNC(=O)[C@H]1CC(c2ccccc2)=[NH+]O1",
        "O=C(NCc1cccc(Cn2cnc3ccccc32)c1)N[C@H]1CC[N@@H+]2CCC[C@@H]2C1",
    ],
    [
        "CC(C)CCn1ncc(NC(=O)[C@@H]2CC23CCOCC3)c1C(C)C",
        "CCc1cccc(C[NH2+][C@H]2CCC(=O)N[C@@H]2c2cnn(C)c2)c1",
        "Cc1ccc(CC2CCN(C(=O)c3ccc([C@]4(C)NC(=O)NC4=O)cc3)CC2)cc1C",
        "O[C@H]1CC[C@@H](Nc2ccc(Br)cn2)CC1",
        "CS(=O)(=O)c1ccccc1N1CCC[C@H]1c1cccnc1",
        "C[C@H]1CCN(C(=O)c2cc(N3CCNC3=O)ccc2Cl)C[C@@H]1O",
        "CNC(=O)C1(c2nc(-c3ccc(N4CCCC4=O)cc3)no2)CCC1",
        "O=C(Nc1ccc2c(n1)CCC2)N1C[C@@H](O)C[C@@H]1c1ccc(F)c(F)c1",
        "COc1ccccc1OCCN(C)C(=O)c1cc(=O)[nH]c2ccccc12",
        "CNC(=O)[C@H]1CCCCN1C(=O)Cc1ccc2c(c1)CCO2",
    ],
    [
        "O=C(NCC1(c2ccccc2)CCOCC1)[C@@H](O)c1cc(Cl)cc(Cl)c1",
        "Cc1nc(C(F)(F)F)ccc1C(=O)N1CC[C@@H](O)C12CCCC2",
        "O=C(c1ccc(-c2ccc(F)cc2)s1)N1CCN(c2cccnn2)CC1",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "CCS(=O)(=O)N1CCN(C(=O)C2(c3ccccc3)CC2)CC1",
        "Cc1ccc(CCC(=O)N[C@@H]2CCCCNC2=O)c(C)c1",
        "O=C(NCC1(C2CC2)CC1)[C@@H]1CCCN1C(=O)Cc1ccccc1",
        "Cc1cccc(F)c1CNC(=O)[C@H]1CC(=O)N(C2CCCC2)C1",
        "CC1(C)CCC(CNC(=O)Cc2nc3ncccn3n2)CC1",
        "CN(CCCNc1cccc2c1NC(=O)CO2)c1ccccc1",
    ],
    [
        "Cc1cc2n(n1)[C@H](C(F)(F)F)CCN2C(=O)c1cccc(N2CCCC2=O)c1",
        "COc1cc(NC(=O)CN2CCCCCC2=O)ccc1C(=O)[O-]",
        "Cc1nocc1NC(=O)NC[C@](C)(O)c1ccc(F)cc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COC(=O)c1c(NC(=O)NCCCC(C)C)nc2n1CCOC2",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@@H]3C[C@H](O)c3ccc(F)cc3)n2)ccc1F",
        "COCCCNC(=O)CSc1nnc(-c2c[nH]c3ccccc23)n1C[C@@H]1CCCO1",
        "Cc1ccc(CNC(=O)c2cccc(CNC(=O)Nc3ccc4c(c3)CCC(=O)N4C)c2)cc1",
        "C[C@@](O)(CCc1ccccc1)C(=O)N1CCCc2n[nH]cc21",
        "O=C([O-])c1cc(F)ccc1NS(=O)(=O)c1c[nH]c2ncccc12",
    ],
    [
        "CCc1nc(CNc2cccc3c2C(=O)NC3)no1",
        "Cc1ccn2c(NC(=O)c3cc(F)ccc3Cl)nnc2c1",
        "Cc1ccc(CC2CCN(C(=O)c3ccc([C@]4(C)NC(=O)NC4=O)cc3)CC2)cc1C",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "Cc1cc(C(=O)N2Cc3ccccc3C[C@@H]2C(N)=O)cc(O)n1",
        "C[C@H]([NH2+]Cc1ccc2cn[nH]c2c1)c1ccccc1F",
        "NC(=O)C1(O)CCN(C(=O)C2(c3ccc(F)cc3F)CCC2)CC1",
        "O=C(Nc1ccc2c(c1)COC2)c1coc(C2CCOCC2)n1",
        "COc1cc(C)c(C(=O)N2CCC[C@H]2c2nncn2C)cc1C(=O)[O-]",
        "C[C@@H](NC(=O)N1CCc2nccnc2C1)c1cccc(Cl)c1",
    ],
    [
        "CC1(C)C[C@@H](NC(=O)CCc2nc(-c3cccs3)no2)c2ccc(F)cc2O1",
        "CCc1cccc2c1N(C(=O)c1cc(OC)no1)CC2",
        "Cc1ccc(CNC(=O)CN2CCCC[C@@H](O)C2=O)cc1F",
        "O=C1[C@@H]([N@H+]2CCC[C@@H](Cn3ccnn3)C2)CCN1C1CC1",
        "CCc1c(NCc2ncnn2-c2ccccc2)cnn1-c1ccccc1C",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "Cc1c(CCC(=O)N2CCN(C(=O)c3ccccc3)CC2)cnn1C",
        "Cc1ccc(CC(=O)N2CCC[C@H](c3nc(=O)[nH][nH]3)C2)cc1O",
        "CC[C@H]1OCC[C@H]1NC(=O)Nc1nnn(C(C)C)n1",
        "Cc1nn(C)c2nc(-c3cccs3)cc(C(=O)NCc3ccccc3Cn3cncn3)c12",
    ],
    [
        "CCCC(=O)N1CCC[C@H]1C(=O)N[C@@H]1COc2ccccc2C1",
        "COc1ccc(Cl)cc1C(=O)N[C@H]1CCC(=O)NC1=O",
        "CC(C)S(=O)(=O)CC(=O)Nc1c2c(nn1C)CCC2",
        "O=C1CCCN1Cc1ccc(C(=O)N2CCC[C@@H](N3CCCS3(=O)=O)C2)cc1",
        "COc1cccc(CN(C)C(=O)c2ccc(C(=O)[O-])cn2)c1",
        "Cn1nc2c(c1NC(=O)[C@H]1CCCN(C(=O)Cc3ccccc3)C1)CCC2",
        "O=C1CCCc2cc(C(=O)N3CCO[C@@H](c4ccc(F)cc4)C3)ccc2N1",
        "Cc1ccc(NC(=O)[C@H]2CCCN2C(=O)Cc2ccccc2)c(O)c1",
        "O=C(NCc1ccccc1)C1CCN(C(=O)N[C@@H]2COc3ccccc32)CC1",
        "CC1=[NH+]NC(=O)[C@@H]1CCNC(=O)c1nn(C)c2c1C[C@H](C)O[C@@H]2C",
    ],
    [
        "Cc1c[nH]cc1C(=O)N1CCC(c2ccc(S(N)(=O)=O)cc2)CC1",
        "COc1cc(CCO)ccc1NC(=O)[C@H]1CC1(C)C",
        "Cc1nnc2n1C[C@H](C(=O)NCC1(c3ccc(F)cc3Cl)CC1)CC2",
        "Cc1c(C2CC2)n[nH]c1NC(=O)c1cc(C#N)cc(N(C)C)c1",
        "c1cc(NCc2ccc(C3CCC3)nc2)cc(-c2nnc[nH]2)c1",
        "CCc1ccccc1N1C[C@H](C(=O)Nc2ccc(CC(=O)N(C)C)cc2)CC1=O",
        "COc1cc(OC)cc(C2(F)CCN(C(=O)c3ccc(=O)n(-c4cnn(C)c4)c3)CC2)c1",
        "CC(C)CC(=O)N1CCC(NC(=O)NC2CCOCC2)CC1",
        "[NH3+][C@H](CC(=O)NCC(=O)NC1CC1)Cc1cc(F)c(F)cc1F",
        "CCc1nnc([C@@H]2C[C@@H](O)CN2C(=O)[C@H]2C[C@@H]2c2ccc(Cl)cc2Cl)o1",
    ],
    [
        "CCOc1ccc(NC(=O)N[C@H]2CCc3[nH]ncc3C2)cc1OC",
        "O=C([O-])CCC1CCN(C(=O)CCc2cccs2)CC1",
        "O=c1c2ccc(Cl)cc2ncn1C[C@@]1(O)CCCOC1",
        "CCc1sc(C(=O)NCc2nc(C)c(C(=O)[O-])s2)cc1C",
        "O=C(NC[C@@H]1CC[N@H+]1C1CCOCC1)c1cc(F)c2ncccc2c1",
        "COc1cc(Cc2noc(C3(Cc4ccccc4F)CC3)n2)ccc1S(C)(=O)=O",
        "NC(=O)c1ccccc1CCC(=O)N1Cc2ccc(O)cc2C2(CC2)C1",
        "CC(C)(C)c1cnc(NC(=O)N[C@H]2C[C@@H](O)C2(C)C)s1",
        "Cn1c([C@@H]2[C@H](C3CC3)CCN2C(=O)COCCc2cccc(F)c2)n[nH]c1=O",
        "Cc1cnc(C(=O)Nc2cccc(-c3nc(C)c(C)[nH]3)c2)cn1",
    ],
    [
        "Cc1ccc(S(=O)(=O)NC(=O)c2ccco2)cc1C",
        "O=C(Nc1ccccc1N1CCCC1)N[C@H]1[C@H]2CCO[C@H]2C12CCC2",
        "O=C1CN(C(=O)C2CCN(c3ccc4nncn4n3)CC2)CCN1",
        "Cn1ccc2c(C(=O)N3CCC[C@@H](c4cn[nH]c4)C3)cccc21",
        "COc1cc(C)cc(CNC(=O)[C@@H]2Cc3ccccc3N2C(C)=O)c1",
        "CN(C(=O)CS(=O)(=O)c1cc(F)ccc1F)C1CC1",
        "C[N@H+]1CCn2nc(NC(=O)NCc3ccccc3C(F)(F)F)cc2C1",
        "Cn1cc(C(=O)Nc2cccc(-c3cn[nH]c3)c2)c(C(C)(C)C)n1",
        "CNC(=O)CNC(=O)c1cccc(N[C@H]2CCN(c3ccc(Cl)c(F)c3)C2=O)c1",
        "Cc1nc(C(=O)N2CC=CCC23CCOCC3)nc(N2CC[C@@H]([NH3+])C2)c1C",
    ],
    [
        "CO[C@H]1C[C@H](COc2cccnc2)[N@@H+](Cc2ccnn2C)C1",
        "Cc1cc(NC(=O)c2cccc(F)c2)sc1C(=O)N1CC(C2CCOCC2)C1",
        "COc1ccccc1CC(=O)N1CCC(CC(=O)[O-])CC1",
        "COC(=O)c1cc(C)nc(N2CC[C@H](c3ccccc3)C2)n1",
        "O=C(CC[C@@H]1CC[NH2+]C1)Nc1cc(-c2cc(F)cc(F)c2)[nH]n1",
        "Nc1ncnc2c1ncn2C[C@@H]1CC[C@@H](C(=O)N2CCCC3(CCCCC3)C2)O1",
        "COC(=O)Nc1ccc(NC(=O)[C@@H]2CCCN(c3cnccn3)C2)cc1",
        "Cc1ccc(CNc2nccc(C(C)(C)C)n2)c(N2CCCC2)n1",
        "CC[C@](O)(C(=O)N1CCC(C(=O)N2CCOCC2)CC1)c1cccc(Cl)c1",
        "COc1ccc(-c2cc(C(=O)N3CCN(C(=O)c4cccc(O)c4)CC3)sc2C)cc1",
    ],
    [
        "O=C([O-])C1=[NH+]N(c2ccccc2Cl)C(=O)CC1",
        "Cc1cc(C(=O)[O-])ccc1S(=O)(=O)N[C@H](C)c1c(C)noc1C",
        "Cn1cc(-c2ccc(F)c(C(=O)NC[C@@]3(C)CCCC[C@@H]3O)c2)cn1",
        "Cc1[nH]nc(C(=O)N2CCC(Oc3ccccc3Cl)CC2)c1C",
        "O=C([C@@H]1C[C@@H]2CCCC[C@@H]2N1C(=O)c1ccc2ccccc2c1)N1CCC[C@H](O)CC1",
        "C[C@H](NC(=O)c1ccc(-n2cccn2)cc1)[C@@H](C)C(=O)[O-]",
        "O=C1NCc2nccc(N3CCC(c4ccccc4)CC3)c21",
        "CN(C(=O)N1CCC(c2nc(-c3ccccc3)n[nH]2)CC1)C1CCOCC1",
        "CC(C)n1cccc1C(=O)N[C@@H]1CC(=O)N(C(C)(C)C)C1",
        "O=C(NCC1(C2CC2)CC1)[C@@H]1CCCN1C(=O)Cc1ccccc1",
    ],
    [
        "CN(CC1(C)COC1)C(=O)Nc1cccc2nc(C(F)F)sc12",
        "CN(C)C(=O)N1CCN(C(=O)c2ncnc3ccsc23)CC1",
        "C[C@H](O)C(=O)N1CCN(C(=O)c2cn(Cc3cccs3)nn2)CC1",
        "CO[C@H]1C[C@@H](N(C)S(=O)(=O)c2ccc(OCC(=O)[O-])c(Cl)c2)C1",
        "O=C(C[C@@H]1CCCC(=O)N1)NCc1nnc(C2CC2)n1C1CC1",
        "[NH3+]Cc1nnc(N2CCCCC2)o1",
        "Cn1ncnc1C(=O)N[C@H]1C[C@H](Cn2ccnc2-c2ccccc2)C[C@H]1O",
        "C[C@@H]1CN(C(=O)NCc2ccc(S(C)(=O)=O)cc2)C[C@@H](c2ccccc2)O1",
        "Cn1c(=O)oc2ccc(CNC(=O)NC[C@H]3C[C@@H]3c3ccccc3)cc21",
        "O=C([O-])c1coc(C[N@@H+]2CC=C(c3ccc(F)cc3)CC2)n1",
    ],
    [
        "O=C([C@@H]1C[C@H]1c1ccc(Cl)cc1Cl)N1CCC[C@H](N2CC[NH2+]CC2=O)C1",
        "O=C(N[C@H]1CC[C@@H](O)CC1)N1CCO[C@H](c2cc(F)c(Cl)cc2Cl)C1",
        "O=C([C@@H](O)Cc1ccccc1)N1CCC(c2ccc(F)cc2)CC1",
        "CC1(C)C[C@@H](NC(=O)Nc2nnc(C(C)(C)C)s2)CCO1",
        "Cc1ccc(CC(=O)N2CCC(NC(=O)c3ccccc3)CC2)cn1",
        "O=C([O-])[C@@H]1CCN(S(=O)(=O)c2cccc(Cl)c2)CC1(F)F",
        "Cc1cccc(-c2nnc([C@H](C)[N@H+](C)CC3CCOCC3)o2)c1",
        "Cc1c(N2C(=O)[C@H]3C[C@H](O)CN3C2=O)nnn1-c1ccc(F)cc1",
        "CCc1ccc(C(=O)N2CC[N@@H+](C)C3(CCOCC3)CC2)o1",
        "CS(=O)(=O)N1CC[C@H](CNc2ncnc3ccccc23)C1",
    ],
    [
        "C[C@@H]1CCCN1C(=O)c1ccc(-c2nnn[nH]2)cc1",
        "NC(=O)C1CCN(c2ccccc2NC(=O)[C@@H]2Cc3cc(F)ccc3O2)CC1",
        "Cn1cc(-c2cncc(C(=O)N[C@H]3CC[C@H](O)CC3)c2)cn1",
        "CCOc1cn(-c2ccccc2)nc1C(=O)N1CCN(c2ncccn2)CC1",
        "Fc1ccc(OCc2noc([C@H]3C[C@]34CC[NH2+]C4)n2)cc1",
        "Cc1nn(Cc2ncc(-c3ccccc3)o2)c(C)c1[C@@H]1COCCN1C",
        "O=C(NCC1([C@H](O)c2ccccc2)CC1)c1cc(Cl)cc2cccnc12",
        "C[C@@H]1CN(C(=O)NCc2ccc(S(C)(=O)=O)cc2)C[C@@H](c2ccccc2)O1",
        "Cc1c(F)cccc1S(=O)(=O)NCCc1cnoc1",
        "CCNC(=O)c1ccc(NCc2cccc(C(=O)N3CCCCC3)c2)nc1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "Cc1[nH]c2ccccc2c1NC(=O)CCC(C)(C)C",
        "COc1ccc(CNC(=O)c2cnn(C(C)C)c2C)cc1",
        "O=C(NCc1ccccc1)N[C@@H]1CCCC[C@@H]1CO",
        "CC1CN(C(=O)c2ccnc(N3CC[C@H](C)C3)c2)C1",
        "NC(=O)[C@@H]1CCC[N@H+]1C1CCN(C(=O)c2cc3c(Cl)cccc3s2)CC1",
        "N[C@@H](CNC(=O)C[C@@H](c1ccccc1)C(F)(F)F)c1ccccc1",
        "NC(=O)c1cc(NC(=O)N2CCCCC[C@@H]2c2noc(-c3ccccc3)n2)ccc1F",
        "COc1nc(C)cc(N(C)CC2(O)CCCC2)n1",
        "O=C(OCc1ccccc1)N1CCC[C@](O)(CN2CCOCC2)C1",
    ],
    [
        "O=C(c1cccnc1C(F)(F)F)N1CCS(=O)(=O)CC1",
        "CCc1ncnc(N2CCN(C(=O)c3ccco3)CC2)c1F",
        "O=C1C[C@@H](Cc2ccc(C(=O)N3CCC[C@@H]3CO)cc2)C(=O)N1",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1F)c1ccc(NC(=O)c2ccncc2)cc1",
        "C[C@@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(F)c1",
        "CN1CC[C@@H](NC(=O)Nc2cnn(-c3ccccc3Br)c2)C1=O",
        "O=C([O-])[C@]1(O)CCCN(S(=O)(=O)c2ccccc2Cl)C1",
        "Cc1nc(-c2c(C)c(C)nn(C)c2=O)sc1C(=O)NC[C@@H](O)C1CCCCC1",
        "Cc1nnc(-c2cccc(C(=O)N3CC(O)C3)c2)o1",
    ],
]


- Experiment:
    name: 3 known

    dataset: datasets/DDS10_MQN.pkl

    model:
        name: MLP
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]
