- unique_initial_sample:
    seeds: [
    [
        "O=C(Nc1ccc(Nc2ncccn2)cc1)c1cn[nH]c1-c1ccco1",
        "NC(=O)c1ccc(C(=O)N2CCC[C@H](Cn3ccnn3)C2)nc1",
        "COc1ccnc(NC[C@]23C[C@](NC(=O)[C@@H]4C[C@@H]4C)(C2)C(C)(C)O3)n1",
        "Cc1csc(N2CCN(C(=O)c3ccc(C(=O)NC4CC4)cc3)C[C@H]2C)n1",
        "CN1C(=O)CCc2cc(NC(=O)NC[C@@H](O)c3ccccc3)ccc21",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1",
        "Cc1cc([N+](=O)[O-])c(C)c(S(=O)(=O)N(C)[C@@H]2C[N@H+]3CC[C@@H]2CC3)c1",
        "Cc1ccc(C(=O)N2CC[C@H](c3cc(O)[nH]n3)C2)cc1",
        "Cc1cccc([C@@H]2CCCN2C(=O)NCc2ccc(S(C)(=O)=O)cc2)n1",
        "Cc1cccc(-c2cccc(C(=O)N3C[C@H](CO)[C@@H](CO)C3)c2)c1",
    ],
    [
        "O=C([O-])c1cccc(CS(=O)(=O)N2CC[C@H](O)C2)c1",
        "O=C(CCc1cccc(Br)c1)N[C@H]1C[C@H](Cn2ccnc2)C[C@@H]1O",
        "Cc1ccccc1CNc1cc(C(N)=O)ccc1Cl",
        "COc1ccc(OC)c([C@@H]2CCCN2C(=O)c2ccnc(OC)n2)c1",
        "C=CCN(CC(=O)[O-])S(=O)(=O)c1ccc(OC)c(Cl)c1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)NCc1nc2ccccc2n1CC",
        "COC[C@@H]1CN(C(=O)c2ncoc2C2CC2)CCO1",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "CCc1nocc1CN(C)C(=O)c1ccc2[nH]c(=O)n(C)c2c1",
        "CC[NH+]1CCN([C@@H]2CCN(C(=O)Cc3cncs3)C2)CC1",
    ],
    [
        "CC(C)C[C@H]1C(=O)NCCN1C(=O)c1cc(O)nc(C(C)C)c1",
        "O=C(Cc1ccc(-n2cnnn2)cc1)Nc1cnn(C[C@@H]2CCCO2)c1",
        "Cc1nc([C@H](NC(=O)[C@H]2C[C@H]2c2ccc(C(F)(F)F)cc2)c2ccccc",
        "O=C(c1ccnn1C1CCCC1)N1CCN(c2cncc3ccccc23)CC1",
        "O=C(NCC1([C@@H](O)c2ccccc2)CC1)c1cnn2c(=O)cc[nH]c12",
        "N#Cc1ccc(C(=O)N2CCCC[C@H]2C(=O)[O-])cc1",
        "Cc1cc(C)n(CC(=O)NC[C@@H]2CC[C@@H](c3ncn[nH]3)O2)n1",
        "Cc1c(CC(=O)N2CC[C@@H](S(C)(=O)=O)C2)nnn1-c1ccccc1",
        "CC(C)CCOC1CCN(C(=O)c2ccc(C(=O)[O-])cn2)CC1",
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
    ],
    [
        "CCc1nn(C)cc1C(=O)N[C@@H]1c2ccccc2C[C@@H]1O",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
        "C=CCC1(C(=O)N2CC[C@@H](c3nc(C)no3)C2)CCOCC1",
        "O=C1NCCN(C(=O)c2cc(C3CC3)on2)[C@H]1c1ccc(C(F)(F)F)c",
        "O=C(c1cccc(Cn2ccnn2)c1)N1C[C@H]2COC[C@@H]2C1",
        "C[C@H](Cc1nc(-c2ccccc2)no1)NC(=O)c1cccc(C#N)c1",
        "CSC[C@@H](C)C(=O)N1CCOC[C@H]1CC(=O)[O-]",
        "C[C@H]1CN(c2nnc(-c3ccccc3)n2C[C@@H]2CCCO2)CCS1",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@@H]3C[C@H](O)c3ccc(F)cc",
        "O=C(c1ncsc1Nc1ccccc1)N1C[C@@H](CO)[C@@H](CO)C1",
    ],
    [
        "Cc1cc(C)cc(-n2nc(C(=O)N3CCCC[C@@H]3c3cn[nH]c3)cc2C)c1",
        "CCc1cccc(C)c1NS(=O)(=O)c1cnc2n1CCC2",
        "O=C1CCCc2cc(C(=O)N3C[C@@H](c4ccccc4)[C@@H]4CCC[C@H]43",
        "CCn1c(=O)c(=O)[nH]c2cc(C(=O)NC[C@H]3CN(C)CCO3)ccc21",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "O=C(NC[C@H]1CCC[N@H+](Cc2ncon2)C1)c1cccc(-n2cncn2)c1",
        "Cc1cccc2nc(N3CC[C@H](S(C)(=O)=O)C3)sc12",
        "CC(C)c1cccc(S(=O)(=O)NC(=O)CC[C@H]2Cc3ccccc3NC2=O)c1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[",
        "CC(=O)Nc1ccc(NC(=O)c2cccc3ncn(C)c23)cc1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "C[C@H]([NH3+])[C@@H]1CCCN(c2ccc(-c3ccc(Cl)s3)nn2)C1",
        "O=C(N[C@H]1CCc2ccc(F)cc21)c1c[nH]nc1-c1ccccc1",
        "CCc1cc(N2CC[C@@H](n3cc(C(=O)[O-])nn3)C2)c2ccccc2n1",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1",
        "CCc1onc(C)c1NC(=O)NCC1CCc2ccccc2CC1",
        "Cc1ccc(F)cc1C(=O)NC(C)(C)c1cn(C)nn1",
        "CCOc1c(Cl)cc(CNc2ccc3nc(C)nn3n2)cc1OC",
        "O=C(C[C@@H]1CCc2ccccc2C1)N1CCC(c2nnc3n2CC[NH2+]C3)CC1",
        "Cc1ccsc1S(=O)(=O)NC(=O)C(F)(F)C1CCOCC1",
    ],
    [
        "O=C(COc1ccc(F)cc1)N[C@H]1CCC(=O)N[C@H]1c1ccccc1",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2",
        "CCS(=O)(=O)N1CCN(c2nnc(-c3cccn3C)n2C)CC1",
        "COCC1(C)CCN(C(=O)Nc2cnn(-c3ncccn3)c2)CC1",
        "O=C(c1ccccc1)N1CCN(C(=O)C2CCOCC2)CC1",
        "O=C(NCc1ccc(Br)s1)NC[C@H]1CCCO1",
        "O=C(NCc1ccc(-c2ccccc2)cc1)[C@@H]1C[C@@H](O)CN1C",
        "O=C([O-])C[C@H](NC(=O)c1ccc2cc[nH]c2c1)c1cccs1",
        "Cc1nc(CN(C)C(=O)C[C@H]2CCCC[C@H]2O)no1",
        "CS(=O)(=O)[C@@H]1CCN(C(=O)c2cccnc2N2CCCC2)C1",
    ],
    [
        "CCn1nc(C)c(C[N@H+]2CCc3[nH]cnc3[C@@H]2c2ccc(F)cc2)n1",
        "NC(=O)c1cn(CC(=O)N2CCC[C@@H]2c2ccc(F)cc2)c2ccccc12",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)",
        "COc1ccccc1[C@@H](CNC(=O)N1CC[C@](F)(CO)C1)[NH+]1CCCC1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)Nc1cnn(CCOC)c1",
        "Cc1cccc(CN(C)C(=O)c2cnn3ccc(C)cc23)c1",
        "CC(C)N(C)C(=O)C1CCN(C(=O)CCc2ccc(C(=O)[O-])cc2)CC1",
        "CC1CCN(C(=O)C2CCN(C(=O)Nc3cccc(-c4ccc5c(c4)CCO5)c3)CC2)CC1",
        "COc1cc(CC(=O)N2CCOC[C@H]2c2c(C)n[nH]c2C)ccc1C",
        "CCn1cc(Cl)cc1C(=O)N[C@@H](C(=O)[O-])C(C)C",
    ],
    [
        "CCn1nc(C)c(Cn2cnc3c(sc4ncccc43)c2=O)n1",
        "O=C(Nc1cnn(C[C@H]2CCCO2)c1)N[C@H](CN1CCCC1=O)c1ccccc1",
        "O=C1O[C@H](c2ccccc2)Cc2cc(C(=O)N3CC[C@H](c4ccccc4F)C3)ccc21",
        "Cc1cccc(-c2cccc(C(=O)N3C[C@H](CO)[C@@H](CO)C3)c2)c1",
        "COc1c(C)cc(S(=O)(=O)N2CCN(C(=O)C3CC3)C2)cc1C",
        "Cc1nc(C(=O)N(C)C)nc(N2CC[C@H](Nc3ncc(C#N)cc3F)C2)c1C",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COc1cccc(C(=O)NCC(=O)N[C@@H]2CCC(=O)N[C@H]2[C@@H]2CCCO2)c1",
        "O=C(Cn1cnc2scc(-c3ccc(Br)cc3)c2c1=O)N1CCCC1",
    ],
    [
        "CC(=O)N1c2ccc(S(=O)(=O)N3CC4(CCC4)c4c(F)cccc43)cc2C[C@@H]1C",
        "Cn1ccnc1[C@H]1CCN(C(=O)Cc2n[nH]c(=O)c3ccccc23)C1",
        "NC(=O)c1cn(CC(=O)N2CCC[C@@H]2c2ccc(F)cc2)c2ccccc12",
        "Cc1cc(S(N)(=O)=O)cc(C(=O)NC[C@@H]2CCCO2)c1C",
        "CC[C@@H](CO)NC(=O)Nc1ccc(S(=O)(=O)NC(C)(C)C)cn1",
        "CC(C)c1cccc(S(=O)(=O)NC(=O)CC[C@H]2Cc3ccccc3NC2=O)c1",
        "NC(=O)C1(c2ccccc2)CCN(C(=O)N[C@@H]2CCN(c3ccc(Cl)c(F)c3)C2)C",
        "CCc1csc(CC(=O)N[C@@H](CN2CCOCC2)c2ccc(C)cc2)n1",
        "O=C(NCCc1ccc2cn[nH]c2c1)N1CCCC1",
        "Cc1csc([C@H]2CCCN2C(=O)c2ccc3cc[nH]c3n2)n1",
    ],
    [
        "O=C(CN1CCc2ccccc2C1=O)NCc1ccccc1",
        "COC(=O)[C@@H]1CCc2nnc(C(=O)N3CCCC3)n2C1",
        "O=C(CNC(=O)[C@@H]1CCC[NH2+]1)Nc1ccc2c[nH]nc2c1",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "Cc1cc(C)cc(C(=O)N2CCC[C@H](C(=O)NCc3cccc([C@@]4(C)NC(=",
        "Cc1n[nH]c(C)c1CC(=O)N1CCO[C@H](c2ccccc2)C1",
        "O=C(CC[C@@H]1CCCOC1)NS(=O)(=O)Cc1cccc(F)c1",
        "Cc1nnc(-c2ccc(NC(=O)N3CCCC3)cc2)o1",
        "CC(C)C(=O)Nc1cc(C(=O)N2CCC(O)(c3ccccc3)CC2)ccn1",
    ],
    [
        "Cc1ccccc1Cc1noc(C2CCN(C(=O)N(C)C)CC2)n1",
        "CC(C)Cc1cc(N2CCC(Cc3nncn3C)CC2)ncn1",
        "CCNC(=O)N1CCC[C@@H]1c1nc(-c2ccccc2)c(C(C)C)o1",
        "Cc1cc(NC(=O)c2nn(C)c3ccccc23)ccc1NC(=O)c1cnc2n1CCC",
        "CC(C)N(C)C(=O)C1CCN(C(=O)CCc2ccc(C(=O)[O-])cc2)CC1",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "Cc1nccn1-c1ncccc1CNC(=O)C1(c2ccccc2Cl)CCOCC1",
        "C[NH+]1CCC(CNC(=O)CNC(=O)c2ccc3ccccc3c2)CC1",
        "CCn1cc(C(=O)NCC2([C@H](O)c3ccccc3)CC2)c2ccccc21",
        "Cc1ccc(S(=O)(=O)N[C@@H]2C=C[C@H](C(=O)[O-])C2)cc1C",
    ],
    [
        "C[C@@H](c1ccc(F)c(F)c1)N(C)C(=O)c1cn(Cc2cccc(F)c2)nn1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "Cc1cc(S(=O)(=O)NOCC(=O)[O-])ccc1OC(C)C",
        "CC1CCN(S(=O)(=O)N[C@H]2CCN(c3ccccc3)C2=O)CC1",
        "CCc1nc([C@@H](C)NC(=O)N[C@@H]2CCCc3cn[nH]c32)n[nH]1",
        "Cn1ccc2ccc(NC(=O)N3CC[C@H](C(C)(C)C)C3)cc2c1=O",
        "Cc1nc(C2CC2)nc(C)c1C(=O)NCC1CCC1",
        "Cc1ccc(NC(=O)N2CCN(C(=O)c3ccoc3C(F)(F)F)CC2)cc1",
        "C[C@@H](NC(=O)N1C[C@H](c2ccccc2)[C@H]2COCC[C@H]21)c1c",
        "C[C@]1(C(=O)[O-])CCC[N@@H+]1CC(=O)Nc1ccc(F)cc1Cl",
    ],
    [
        "COc1ccc([C@@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CCOCC2)cc1OC",
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc54)CC3)cc",
        "CCCNC(=O)C[NH+]1CCC(Nc2cc(C(F)(F)F)nc3ncnn23)CC1",
        "Cc1ccc(Cl)c(S(=O)(=O)NC(=O)C(C)C)c1Cl",
        "CS(=O)(=O)c1ccc(NC(=O)NC2CCOCC2)cn1",
        "O=C(Nc1cccc2ccccc12)N[C@H]1CC[NH2+]C1",
        "CCOc1ccc(CNC(=O)N2CCC[C@H](C(=O)NC)C2)cc1F",
        "O=C(c1c[nH]nc1-c1cc2ccccc2o1)N1CCO[C@]2(CCCOC2)C1",
        "C=C(C)CCNC(=O)[C@H]1CC(c2ccccc2)=[NH+]O1",
        "O=C(NCc1cccc(Cn2cnc3ccccc32)c1)N[C@H]1CC[N@@H+]2CCC[C@@H]2C1",
    ],
    [
        "CC(C)CCn1ncc(NC(=O)[C@@H]2CC23CCOCC3)c1C(C)C",
        "CCc1cccc(C[NH2+][C@H]2CCC(=O)N[C@@H]2c2cnn(C)c2)c1",
        "C[C@H](COc1ccc(F)cc1F)NC(=O)N1CCC2(CCO2)CC1",
        "O=C([C@@H]1C[C@@H]2CCCC[C@H]2N1C(=O)c1ccc2ccccc2c1)N",
        "Cc1nc2c(cc1C(=O)N[C@H](C)c1ccc3c(c1)CCC(=O)N3)c(C)nn",
        "Cc1nn(C)c2nc(-c3cccs3)cc(C(=O)NCc3ccccc3Cn3cncn3)c12",
        "CNC(=O)C1(c2nc(-c3ccc(N4CCCC4=O)cc3)no2)CCC1",
        "Cc1cc(N2CCC(CO)CC2)nc(-c2cccnc2)n1",
        "COc1ccccc1OCCN(C)C(=O)c1cc(=O)[nH]c2ccccc12",
        "CNC(=O)[C@H]1CCCCN1C(=O)Cc1ccc2c(c1)CCO2",
    ],
    [
        "Cc1ccc(S(=O)(=O)Cc2nnc(C)n2C)cc1C",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc",
        "O=C1C[C@@H](C(=O)Nc2c(F)cccc2Oc2ccccc2)c2ccccc2N1",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "CCS(=O)(=O)N1CCN(C(=O)C2(c3ccccc3)CC2)CC1",
        "Cc1ccc(CCC(=O)N[C@@H]2CCCCNC2=O)c(C)c1",
        "C[C@H]1C[N@@H+](C2CC2)C[C@@H]1NC(=O)N1Cc2ccc(Br)cc2C1",
        "Cc1cccc(F)c1CNC(=O)[C@H]1CC(=O)N(C2CCCC2)C1",
        "CC1(C)CCC(CNC(=O)Cc2nc3ncccn3n2)CC1",
        "CN(CCCNc1cccc2c1NC(=O)CO2)c1ccccc1",
    ],
    [
        "Cc1cc(COCC(=O)N(C)c2ccc(Br)cn2)no1",
        "COc1cc(NC(=O)CN2CCCCCC2=O)ccc1C(=O)[O-]",
        "Cc1nocc1NC(=O)NC[C@](C)(O)c1ccc(F)cc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COC(=O)c1c(NC(=O)NCCCC(C)C)nc2n1CCOC2",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@@H]3C[C@H](O)c3ccc(F)cc3)n2)ccc1F",
        "Cn1cc(NC(=O)N2CCOC3(CCCC3)C2)c(-c2ccccc2)n1",
        "Cc1cc(C)c(S(=O)(=O)N2CCC=C(c3cnn(C)c3)C2)s1",
        "C[C@@](O)(CCc1ccccc1)C(=O)N1CCCc2n[nH]cc21",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
    ],
    [
        "CCc1nc(CNc2cccc3c2C(=O)NC3)no1",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)C",
        "N#Cc1cc(Br)cc(S(=O)(=O)NC(=O)Cc2ccc(F)cn2)c1",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "CCOC(=O)Cn1cnc2cc(Cl)ccc2c1=O",
        "C[C@H]([NH2+]Cc1ccc2cn[nH]c2c1)c1ccccc1F",
        "C[C@H](Cc1cccc(Cl)c1)C(=O)N1CCCN(C(N)=O)CC1",
        "O=C(Nc1ccc2c(c1)COC2)c1coc(C2CCOCC2)n1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "C[C@@H](NC(=O)N1CCc2nccnc2C1)c1cccc(Cl)c1",
    ],
    [
        "O=C(COc1ccccc1F)N1CCCCC[C@@H]1c1ncon1",
        "CCc1cccc2c1N(C(=O)c1cc(OC)no1)CC2",
        "Cc1nc([C@H](NC(=O)[C@H]2C[C@H]2c2ccc(C(F)(F)F)cc2",
        "O=C1[C@@H]([N@H+]2CCC[C@@H](Cn3ccnn3)C2)CCN1C1CC1",
        "COc1cccc(CNC(=O)N2CCC(C(=O)NCc3ccc(F)cc3)CC2)c1",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "Cc1c(CCC(=O)N2CCN(C(=O)c3ccccc3)CC2)cnn1C",
        "CC1(C)OCC[C@H]1NC(=O)c1ccc(C(=O)[O-])cc1",
        "CC[C@H]1OCC[C@H]1NC(=O)Nc1nnn(C(C)C)n1",
        "Cc1nn(C)cc1[C@@H](C)NS(=O)(=O)N1CCOCC1",
    ],
    [
        "CCCC(=O)N1CCC[C@H]1C(=O)N[C@@H]1COc2ccccc2C1",
        "COc1ccc(Cl)cc1C(=O)N[C@H]1CCC(=O)NC1=O",
        "CC(C)S(=O)(=O)CC(=O)Nc1c2c(nn1C)CCC2",
        "O=C1CCCN1Cc1ccc(C(=O)N2CCC[C@@H](N3CCCS3(=O)=O)C2)cc1",
        "COc1cccc(CN(C)C(=O)c2ccc(C(=O)[O-])cn2)c1",
        "O=C(NC[C@@H]1CCC[C@@]12NC(=O)NC2=O)Nc1ccn(-c2cccc(C(F)(F)F)",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "Cc1cc(C)c(NC(=O)[C@H]2C[C@@H]2c2ccccc2C)c(C)n1",
        "CC(C)c1ncncc1C(=O)Nc1cccc(-c2nncn2C)c1",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
    ],
    [
        "Cc1cc(F)ccc1-n1ccc(C(=O)N2CCc3ccccc3[C@H]2CO)n1",
        "NC(=O)NC[C@H]1CCCN(C(=O)NCc2ccccc2Oc2ccccc2)C1",
        "Cc1nnc2n1C[C@H](C(=O)NCC1(c3ccc(F)cc3Cl)CC1)CC2",
        "Cc1c(C2CC2)n[nH]c1NC(=O)c1cc(C#N)cc(N(C)C)c1",
        "Cn1ccnc1[C@@]1(CNC(=O)c2ccc(O[C@H]3CC3(F)F)cc2)NC(=O)NC1=O",
        "CN(Cc1ccc(F)cc1Cl)C(=O)c1cnns1",
        "COc1cc(OC)cc(C2(F)CCN(C(=O)c3ccc(=O)n(-c4cnn(C)c4)c3)CC2)c1",
        "CC(C)CC(=O)N1CCC(NC(=O)NC2CCOCC2)CC1",
        "[NH3+][C@H](CC(=O)NCC(=O)NC1CC1)Cc1cc(F)c(F)cc1F",
        "CN(CC1CC1)C(=O)Cn1ccc(-c2ccccc2)nc1=O",
    ],
    [
        "O=C(NCc1ccc(-c2ccccc2)cc1)[C@@H]1C[C@@H](O)CN1C(=O",
        "O=C([O-])CCC1CCN(C(=O)CCc2cccs2)CC1",
        "O=c1c2ccc(Cl)cc2ncn1C[C@@]1(O)CCCOC1",
        "CCc1sc(C(=O)NCc2nc(C)c(C(=O)[O-])s2)cc1C",
        "O=C(NC[C@@H]1CC[N@H+]1C1CCOCC1)c1cc(F)c2ncccc2c1",
        "COc1ccccc1NC(=O)Cc1noc([C@@H]2Cc3ccccc3N2C(C)=O)n1",
        "Cc1cccc(C(=O)N2CCOC[C@H]2CC(=O)[O-])c1Cl",
        "CC(C)(C)c1cnc(NC(=O)N[C@H]2C[C@@H](O)C2(C)C)s1",
        "Cc1noc([C@@H]2C[C@H](CNc3cnccn3)[C@@H](O)C2)n1",
        "COc1ccc(-c2noc(-c3ccc(NC(=O)c4cc(F)cc(F)c4)cc3O)n2",
    ],
    [
        "Cc1ccc(S(=O)(=O)NC(=O)c2ccco2)cc1C",
        "O=C(Nc1ccccc1N1CCCC1)N[C@H]1[C@H]2CCO[C@H]2C12CCC2",
        "NC(=O)[C@H](Sc1nc2c(cnn2-c2cccc(Cl)c2)c(=O)[nH]1)c1ccc(",
        "OCCn1cc(Nc2ccnc(-c3ccccc3)n2)cn1",
        "COc1cc(C)cc(CNC(=O)[C@@H]2Cc3ccccc3N2C(C)=O)c1",
        "CN(C(=O)CS(=O)(=O)c1cc(F)ccc1F)C1CC1",
        "C[N@H+]1CCn2nc(NC(=O)NCc3ccccc3C(F)(F)F)cc2C1",
        "C[C@H](Nc1nc(-c2cccnc2)nc2c1CCC2)c1cccc(S(N)(=O)=O)c1",
        "[NH3+][C@H]1CCC[C@@H](C(=O)Nc2ccc3nc(N4CCOCC4)sc3c2)C1",
        "Cc1nc(C(=O)N2CC=CCC23CCOCC3)nc(N2CC[C@@H]([NH3+])C2)c1C",
    ],
    [
        "Nc1nccc([C@H]2CCCN(C(=O)c3cccc(NS(=O)(=O)c4ccc(F)c(F",
        "Cc1cc(NC(=O)c2cccc(F)c2)sc1C(=O)N1CC(C2CCOCC2)C1",
        "COc1ccccc1CC(=O)N1CCC(CC(=O)[O-])CC1",
        "COC(=O)c1cc(C)nc(N2CC[C@H](c3ccccc3)C2)n1",
        "O=C(CC[C@@H]1CC[NH2+]C1)Nc1cc(-c2cc(F)cc(F)c2)[nH]n1",
        "Cc1n[nH]c(C)c1CC(=O)N[C@H]1CC(C)(C)Oc2ccccc21",
        "COC(=O)Nc1ccc(NC(=O)[C@@H]2CCCN(c3cnccn3)C2)cc1",
        "C[C@@H](CO)NC(=O)Nc1cnc(-c2cccc(C(F)(F)F)c2)cn1",
        "Cc1cc(C(=O)N2CCC(CCC(=O)[O-])CC2)ccn1",
        "CN(c1ccccc1)S(=O)(=O)c1csc(C(=O)[O-])c1",
    ],
    [
        "O=C([O-])C1=[NH+]N(c2ccccc2Cl)C(=O)CC1",
        "Cc1cc(C(=O)[O-])ccc1S(=O)(=O)N[C@H](C)c1c(C)noc1C",
        "NC(=O)[C@H](Sc1nc2c(cnn2-c2cccc(Cl)c2)c(=O)[nH]1)c",
        "Cc1[nH]nc(C(=O)N2CCC(Oc3ccccc3Cl)CC2)c1C",
        "COc1cc(C)c([C@H](C)NC(=O)CN2CCOC3(CCC3)C2)cc1OC",
        "C[C@H](NC(=O)c1ccc(-n2cccn2)cc1)[C@@H](C)C(=O)[O-]",
        "O=C1NCc2nccc(N3CCC(c4ccccc4)CC3)c21",
        "Cc1ccc(NC(=O)CCn2c(=O)[nH]c(=O)c3ccccc32)cc1NS(=O)",
        "CC(C)n1cccc1C(=O)N[C@@H]1CC(=O)N(C(C)(C)C)C1",
        "O=C(N[C@H]1CCCN(c2ccccc2F)C1)c1cnn2cccnc12",
    ],
    [
        "CN(CC1(C)COC1)C(=O)Nc1cccc2nc(C(F)F)sc12",
        "CN(C)C(=O)N1CCN(C(=O)c2ncnc3ccsc23)CC1",
        "C[C@H](O)C(=O)N1CCN(C(=O)c2cn(Cc3cccs3)nn2)CC1",
        "CO[C@H]1C[C@@H](N(C)S(=O)(=O)c2ccc(OCC(=O)[O-])c(Cl)c2)C1",
        "O=C(C[C@@H]1CCCC(=O)N1)NCc1nnc(C2CC2)n1C1CC1",
        "[NH3+]Cc1nnc(N2CCCCC2)o1",
        "CC(C)[C@@H](O)CC(=O)N1CC=C(c2c[nH]c3ncccc23)CC1",
        "O=C(Cc1cccnc1)NCc1cn(-c2ccccc2)nc1-c1ccc(F)cc1",
        "CCc1nc([C@@H]2CCCN2C(=O)Nc2ccncc2)no1",
        "O=C([O-])c1coc(C[N@@H+]2CC=C(c3ccc(F)cc3)CC2)n1",
    ],
    [
        "COc1cc(F)cc(CNC(=O)N2CC[C@@]3(C2)C(=O)Nc2ccccc23)c1",
        "CO[C@H]1C[C@@H](N(C)C(=O)NC[C@@H]2CCCOC2)C1",
        "CC[C@@H](NC(=O)c1ccc(C)cc1C)c1c(C)noc1C",
        "CC1(C)C[C@@H](NC(=O)Nc2nnc(C(C)(C)C)s2)CCO1",
        "Cc1ccc(CC(=O)N2CCC(NC(=O)c3ccccc3)CC2)cn1",
        "O=C(NCc1ccc(-c2ccccc2)cc1)[C@@H]1C[C@@H](O)CN1C(=O)",
        "Cc1cccc(-c2nnc([C@H](C)[N@H+](C)CC3CCOCC3)o2)c1",
        "O=C(Cc1cccnc1)NCc1cn(-c2ccccc2)nc1-c1ccc(F)cc1",
        "CCc1ccc(C(=O)N2CC[N@@H+](C)C3(CCOCC3)CC2)o1",
        "CS(=O)(=O)N1CC[C@H](CNc2ncnc3ccccc23)C1",
    ],
    [
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s",
        "O=S(=O)(NCc1cccnn1)c1ccccc1Br",
        "Cn1cc(-c2cncc(C(=O)N[C@H]3CC[C@H](O)CC3)c2)cn1",
        "CCOc1cn(-c2ccccc2)nc1C(=O)N1CCN(c2ncccn2)CC1",
        "O=C(N[C@H]1CCc2ccc(F)cc21)c1c[nH]nc1-c1ccccc1",
        "Cc1nn(Cc2ncc(-c3ccccc3)o2)c(C)c1[C@@H]1COCCN1C",
        "O=C(NCC1([C@H](O)c2ccccc2)CC1)c1cc(Cl)cc2cccnc12",
        "CCN(CC)C(=O)CCCNC(=O)Cc1cc2ccccc2c(=O)[nH]1",
        "Cc1c(F)cccc1S(=O)(=O)NCCc1cnoc1",
        "Cn1cc(S(=O)(=O)N[C@@H]2CCc3c(Cl)cccc32)cn1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "COc1cccc(CNC(=O)N2CCC(C(=O)NCc3ccc(F)cc3)CC2)c1",
        "COc1ccc(CNC(=O)c2cnn(C(C)C)c2C)cc1",
        "O=C(NCc1ccccc1)N[C@@H]1CCCC[C@@H]1CO",
        "CC1CN(C(=O)c2ccnc(N3CC[C@H](C)C3)c2)C1",
        "CC[C@@H]1C[N@H+](C)CCCN1S(=O)(=O)c1nc(C)c(C)s1",
        "COc1ccc(C[NH2+]Cc2nnc3n2CCOCC3)c(Cl)c1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "COc1nc(C)cc(N(C)CC2(O)CCCC2)n1",
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[nH]4)CC3)cc2",
    ],
    [
        "O=C(c1cccnc1C(F)(F)F)N1CCS(=O)(=O)CC1",
        "CCc1ncnc(N2CCN(C(=O)c3ccco3)CC2)c1F",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2ccccc2)c1",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1F)c1ccc(NC(=O)c2ccncc2)cc1",
        "Cc1nc(NC(=O)[C@@H]2CCC[C@H](C(=O)[O-])C2)n[nH]1",
        "O=C(Cc1c[nH]c2ccc(F)cc12)N[C@H]1CCCN(Cc2ccc(F)cc2F)C1=O",
        "O=C([O-])[C@]1(O)CCCN(S(=O)(=O)c2ccccc2Cl)C1",
        "CCOc1ccccc1CNC(=O)[C@@H]1C[C@@H](C)[C@@H](C(=O)[O-])O1",
        "Cc1nnc(-c2cccc(C(=O)N3CC(O)C3)c2)o1",
    ],
]


- Experiment:
    name: Enrich 2(RDKit2D)

    dataset: datasets/DDS10_RDKIT2D.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy
        use_pairwise: True

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]
