- unique_initial_sample:
    seeds: [
    [
        "CC(=O)/C=C/C=C/c1ccc2c(c1)O[C@H](CO)[C@@H](c1ccc(O",
        "O=C1C=C2C[C@@]3(O)COc4c(ccc(O)c4O)C3=C2C=C1O",
        "O=C(c1cc(O)c(O)c(O)c1)c1ccc(O)c(O)c1O",
        "NC(=O)/N=N/c1c(F)c(F)c(F)c(F)c1F",
        "CCCOC(=O)NCCSC(=O)OCCC",
        "CC(=O)NC(CCC(=O)c1ccc(Cl)cc1)(C(=O)[O-])C(=O)[O-]",
        "CC[C@H](C)[C@H](N)C(=O)NCC(=O)OC",
        "C/C(=[NH+]\\S(=O)(=O)c1cccc([N+](=O)[O-])c1)OCC(C)C",
        "O=C1/C(=C/c2ccc(O)c(O)c2)CC/C1=C\\c1ccc(O)c(O)c1",
        "Cc1cccc(-n2c(C)nc3ccc(NC(=O)NCCCl)cc3c2=O)c1",
    ],
    [
        "COc1c(O)cc(Br)c(C=O)c1N",
        "CC(=O)Nc1ccc2c(c1)/C(=N/c1ccc(C(=O)[O-])cc1)c1c",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)NCc1ccc(C(F)(F)F)c",
        "Oc1cc(O)c2c(c1)O[C@H](c1cc(O)c(O)c(O)c1)[C@@H](",
        "c1c2c(cc3c1OCN(C1CC1)C3)OCN(C1CC1)C2",
        "O=C1/C(=C/c2ccc(O)c(O)c2)CC/C1=C\\c1ccc(O)c(O)c1",
        "COc1ccc2cc(N3CCCC3)ccc2c1",
        "O=C(CSc1ncc[nH]1)c1ccc(Br)cc1",
        "COc1cc([C@@H]2Oc3c(OC)cc4ccc(=O)oc4c3O[C@H]2CO)",
        "C=CCNC(=S)NCc1cccc2ccccc12",
    ],
    [
        "CC(=O)Nc1ccc(C(=O)[C@H](O)c2ccc(NC(C)=O)cc2)cc1",
        "O=C1OC[C@@H](Cc2ccc(O)c(O)c2)[C@H]1Cc1ccc(O)c(O)c1",
        "C[NH+]1C=c2c3c(ccc2=C2C=C[C@H]4C=C5OCOC5=CC4=C21)OCO3",
        "O=C([O-])c1cccc(O)c1O",
        "CO[C@@H]1[C@H](O)c2coc3c2[C@@](C)(c2ccc4c(c2C3=O)CCC4",
        "CCO/C=C1\\SC(=S)N(c2ccc(C(=O)[O-])cc2)C1=O",
        "CC(C)(C)C[NH+]1CCCN(c2ccc(Cl)cc2)C1",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1c(O)ccc2ccccc12)c1ccccc1",
        "COc1cccc(P(c2cccc(OC)c2)c2cccc(OC)c2)c1",
        "O=C1c2ccc(O)cc2O[C@@H](c2cc(O)c(O)c(O)c2)[C@@H]1O",
    ],
    [
        "CC(=O)NC1=C([NH3+])C(=O)c2ccccc2C1=O",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1c(O)ccc2ccccc12)c1ccccc1O",
        "O=C([O-])[C@H](c1ccccc1)c1cccc([C@@H](C(=O)[O-])c2ccccc2)n1",
        "COc1ccc(CC2=[N+](C)CCc3cc(OC)c(OC)cc32)cc1OC",
        "COc1c(-c2ccc(O)c(O)c2)oc2c(O)c(O)cc([O-])c2c1=O",
        "CC(C)=CCc1ccc2[nH]c3c(c2c1)C(=O)C(=O)C(C)=C3[C@@H](O)[C@H](",
        "CC1(C)O[C@@H]1C(=O)[O-]",
        "OC[C@H]1COc2cc(Cl)c(Cl)cc2O1",
        "Fc1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3ccccc3)C2)cc1",
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C@@H]1O",
    ],
    [
        "COc1ccc(Cl)c(S(N)(=O)=O)c1",
        "Cc1cc(SCc2ccc([N+](=O)[O-])cc2)nc(N)n1",
        "NC(=S)SC1=NC(=O)C2(NN1)c1ccccc1-c1ccccc12",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)C[C@H]([C@]1(CO)CO1)O",
        "O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc3C[C@H]",
        "O=C(N/[NH+]=C\\C(F)(F)F)c1ccncc1",
        "C[C@@H]1C[C@H]([C@@H](O)CC2CC(=O)N(Cc3ccccc3)C(=O)C2)",
        "CCOC(=O)N[C@H]1[C@@H]2OC(C)(C)O[C@@H]2O[C@H]1CC(=O)OC",
        "O=C1/C(=C/c2ccc(O)c(O)c2)CC/C1=C\\c1ccc(O)c(O)c1",
        "O=C(Nc1ccccc1CO)c1ccccc1",
    ],
    [
        "Cc1ccccc1-c1c(N)nc(NC#N)nc1C(=O)Nc1ccccc1",
        "OCCCNC(=S)Nc1ccc(-c2nc3ccccc3[nH]2)cc1",
        "O=[N+]([O-])c1cccc([C@@H]2CC(c3ccccc3)=[NH+]N2c2ccccc2)c1",
        "CC(C)=CCc1c(OC(=O)c2c(C)cc(O)cc2O)cc(CO)c(CO)c1O",
        "Oc1ccc2c(c1)OC[C@@]1(O)Cc3cc(O)c(O)cc3[C@H]21",
        "Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2",
        "CCn1c(Cl)c(/C=[NH+]\\Nc2ccc([N+](=O)[O-])cc2)c2ccccc21",
        "N#CS/C=C\\C(N)=O",
        "O=c1oc2ccccc2cc1-n1nnc2cc([N+](=O)[O-])ccc21",
        "CCOc1ccc(/N=C/c2cccc([N+](=O)[O-])c2)c(O)c1",
    ],
    [
        "CCn1c(=O)c(C#N)c2n(CC)c3cc(C)c(C)cc3n2c1=O",
        "O=C1c2ccccc2C(=O)c2c(OC[C@H]3CO3)ccc(OC[C@@H]3CO3)c21",
        "NC(=O)c1cccc(NC=O)c1",
        "O=C(c1cc(O)c(O)c(O)c1)c1ccc(O)c(O)c1O",
        "CC(=O)Nc1nnc(SC[NH+](C)C)s1",
        "C/C(=[NH+]/NC(=O)Nc1ccc(/N=N/c2ccccc2)cc1)c1ccccn1",
        "CCOC(=O)c1[nH]c(CO)c(C(=O)OCC)c1C",
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C@@H]1O",
        "Oc1cc(O)c2c(c1)O[C@H](c1cc(O)c(O)c(O)c1)[C@@H](O)C2",
        "CC(C)=CCc1c(OC(=O)c2c(C)cc(O)cc2O)cc(CO)c(CO)c1O",
    ],
    [
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
        "COc1cc(NC/C(C)=[NH+]/NC(N)=O)c2ncccc2c1",
        "Nc1nc(Cl)c2c(n1)CCC2",
        "O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc3C[C@H]",
        "O=C(CCl)Nc1cccc2c1C(=O)c1c(c(O)c3ccccc3c1O)C2=O",
        "COc1cc2cccc(O)c2cc1OC",
        "O=C(NNC(=O)c1cccc2ccccc12)c1ccc(F)cc1",
        "CCOC(=O)/C=C/c1ccc2c(c1)O[C@@H](c1ccc(O)c(OC)c1)[C@H]",
        "c1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3ccccc3)C2)c",
        "CCN(CC)C(=O)Nc1cccc(O)c1",
    ],
    [
        "C[C@@H]1C[C@H]([C@@H](O)CC2CC(=O)N(Cc3ccc",
        "NC(=O)C[C@@H]1OC(=O)Cc2cc3c(c(O)c21)C(=O)",
        "O=C1CC[C@H](O)Cc2ccc(O)c(c2)-c2cc(ccc2O)C",
        "Nc1ncc2[nH]c(=O)[nH]c2n1",
        "Cn1cc(C(=O)c2ccccc2)cc(C(=O)c2ccccc2)c1=O",
        "CCCCCCC[C@@H]1OCC[C@H](C)O1",
        "O=C1c2cc(O)c(O)cc2O[C@H](c2ccc(O)c(O)c2)[",
        "Nc1ccc(CCOc2ccc(N)cc2)cc1",
        "CCOc1ccc(N)c(SCC(=O)[O-])c1",
        "O=c1c(O)c(-c2ccc(O)c(O)c2)oc2cc(O)c(O)c([",
    ],
    [
        "O=c1c(OC/C(=[NH+]/O)c2ccc(F)cc2)c(-c2ccccc2)oc2c",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)c1ccc(O)c(O)c1",
        "COC(=O)N1[C@@H](N2CCCC2=O)C(C)(C)S1(=O)=O",
        "CCOC(=O)CCN1C(=O)CC[C@H]1C(=O)OCC",
        "CC(=O)Nc1ccc(C(=O)[C@H](O)c2ccc(NC(C)=O)cc2)cc1",
        "O=C1c2cc(O)c(O)cc2O[C@H](c2ccc(O)c(O)c2)[C@H]1O",
        "CCO[N+]([O-])=C1C=C(C(C)(C)C)C(=O)C(C(C)(C)C)=C1",
        "COc1cccc([C@@H]2CCCC[C@@H]2O)c1",
        "COc1cc([C@H]2c3cc(O)c(OC)cc3C[C@]3(O)[C@@H]2CO[C",
        "COC(=O)/C=C/CC(=O)NS(C)(=O)=O",
    ],
    [
        "C[C@H](CC(=O)c1ccc(F)cc1)[NH+]1CCCCC1",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1c(O)ccc2ccccc12)c1ccccc1O",
        "N#C/C(=C\\Nc1ccccn1)C(=O)C1CC1",
        "O=C1c2cc(O)cc(O)c2C(=O)c2c1cc1c(c2O)[C@@H]2C=CO[C@@H]2",
        "C[C@@]1(CCCOc2cccc(N)c2)[NH+]=C(N)[NH+]=C(N)N1c1ccccc1",
        "Cn1cc(C2=C(c3cccc(OC[C@@H](O)CO)c3)C(=O)NC2=O)c2ccccc2",
        "C[NH+]1CCN(c2ccc3[nH]c(-c4c5cccccc-5[nH]c4=O)nc3c2)CC1",
        "C=C(CN1CCOCC1)c1ccc(CCC(=O)Nc2ccccc2N)cc1",
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C@@H]1O",
        "Cc1ccc(/C=[NH+]/NC(N)=[NH2+])cc1",
    ],
    [
        "COc1cccc2c1CC[C@H]1C(C)(C)C(=O)CC[C@]21CC(=O)[O-]",
        "O=C(CCl)Nc1nncs1",
        "Nc1ccc(CC[C@H]2CCC/C=C/[C@@H]3C[C@H](O)C[C@H]3[C@H](",
        "CS(=O)(=O)Oc1ccccc1C(=O)[O-]",
        "COc1ccc(C[C@H](CO)NC(=O)c2ccccc2)cc1",
        "O=C(N/[NH+]=C\\c1ccccn1)Nc1ccc(/N=N/c2ccccc2)cc1",
        "COc1cc(C[C@@H]2COC(=O)[C@]2(O)Cc2ccc(O)c(OC)c2)ccc1O",
        "O=C(c1ccc(C(=O)c2ccc(O)cc2O)cc1)c1ccc(O)cc1O",
        "S=C(N/[NH+]=C/c1c[nH]c2ccccc12)NC12CC3CC(CC(C3)C1)C2",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)ccc12",
    ],
    [
        "O=C1N[C@@](O)(c2ccccc2)c2ccccc21",
        "CCc1ccc2c(O)c3c(cc2c1C(=O)OC)C(=O)c1cccc(O)c1",
        "O=C(c1ccccc1)N1[NH+]=CCC[C@@H]1O",
        "O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)c",
        "COc1ccc(C[C@H]2COC(=O)[C@@H]2Cc2ccc(OC)c(O)c2",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)ccc12",
        "Cc1cc(Cc2cc(C)c(O)c(CO)c2)cc(CO)c1O",
        "O=c1cccc2n1Cc1cc3ccccc3nc1-2",
        "CN(C)/C=N/c1ccc(F)cc1",
        "CCOC(=O)C(Cc1cc2c(n1C)CCCC2)(NC(C)=O)C(=O)OCC",
    ],
    [
        "CCCCC=C1C(=O)NC(=S)NC1=O",
        "CC[C@H]1c2cc3n(c(=O)c2CO[C@H]1O)Cc1c-3nc2ccccc2c1C",
        "CCCCOC(=O)[C@@H]([NH3+])Cc1ccc(OC)c(Cl)c1",
        "CC(=O)Oc1cccnc1",
        "Cc1nnc2c(S)nccn12",
        "CCCC(=O)Nc1ccc(C)cc1",
        "O=C(c1cc(O)c(O)c(O)c1)c1ccc(O)c(O)c1O",
        "CC[C@](O)(c1ccc(O)cc1)[C@](O)(CC)c1ccc(O)cc1",
        "Cc1ccccc1-c1c(N)nc(NC#N)nc1C(=O)Nc1ccccc1",
        "COc1ccc(C[C@H]2COC(=O)[C@@H]2Cc2ccc(OC)c(O)c2)cc1O",
    ],
    [
        "COc1c(-c2ccc(O)c(O)c2)oc2c(O)c(O)cc([O-])c2c1=O",
        "O=C1c2ccc(O)cc2O[C@@H](c2cc(O)c(O)c(O)c2)[C@@H]1O",
        "O=C(CCc1ccc(O)c(O)c1)NCCc1cc(O)c(O)c(O)c1",
        "N#CCN1CCCN(CC#N)C1",
        "CC(C)(C)[Si](C)(C)OC[C@]12CC[C@H]3C[NH2+][C@H]([C@H]31)[C@H](c1ccccc1)N2",
        "C[C@H](Cc1ccccc1)NC(N)=O",
        "Fc1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3ccccc3)C2)cc1",
        "CC(=O)C(=Cc1cccc([N+](=O)[O-])c1)C(C)=O",
        "CC(=O)Oc1cccc2c1[nH]c(=O)c1c(OC(C)=O)c3c(cc12)OCO3",
        "CC(=O)/C=C/C=C/c1ccc2c(c1)O[C@H](CO)[C@@H](c1ccc(O)c(O)c1)O2",
    ],
    [
        "N/C(=N/c1ccc(O)cc1)S(=O)(=O)[O-]",
        "Fc1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3",
        "COc1ccc(C(=O)NCC[NH+](C)C)c2nc3ccccc3cc12",
        "OCCCc1cc(O)c2c(c1)[C@@H](CO)[C@@H](c1ccc(O)",
        "COc1ccc2c(c1)CCC[C@@]2(O)C#C[C@]1(O)CCCc2cc",
        "O=C([O-])c1ccc(Oc2ccccc2)cc1",
        "CSC(=[NH2+])c1cccc(CCCCc2ccc(NC(C)=O)cc2)c1",
        "O=c1cc(-c2ccc(O)cc2)oc2ccccc12",
        "O=Cc1cc(O)c(O)c(O)c1-c1c(C=O)cc(O)c(O)c1O",
        "O=C(Cl)c1ccc(C(F)(F)F)cc1",
    ],
    [
        "CN[C@H](C#N)c1ccc(OC)cc1",
        "O=C(Oc1ccccc1)c1cc2ccccc2oc1=O",
        "CC(=O)N[C@H](CS(=O)(=O)Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "CC(=S)NC(=O)NC(=O)c1ccc(C)cc1",
        "Nc1nccc2snnc12",
        "O=C(CCl)Nc1cccc2c1C(=O)c1c(c(O)c3ccccc3c1O)C2=O",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)c1ccc(O)c(O)c1",
        "Cc1cccc(-n2c(C)nc3ccc(NC(=O)NCCCl)cc3c2=O)c1",
        "COc1cc(C[C@@]2(O)C(=O)OC[C@H]2Cc2ccc(OC)c(OC)c2)ccc1O",
        "COc1cccc(NC(=O)CSc2nnc(-c3ccc(NC(C)=O)cc3)o2)c1",
    ],
    [
        "O=Cc1cc(O)c(O)c(O)c1-c1c(C=O)cc(O)c(O)c1O",
        "O=C1CS[C@H](c2cc([N+](=O)[O-])ccc2Cl)N1c1nncs1",
        "Cc1cccc(/C=[NH+]\\NC(=O)Nc2ccc(/N=N/c3ccccc3)cc2)n1",
        "CCOc1ccc(C2[N@]3CCC[N@H+]2CC3)cc1OC",
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
        "CCN(O)CC",
        "COc1cc(C[C@@]2(O)C(=O)OC[C@H]2Cc2ccc(OC)c(OC)c2)ccc1O",
        "Cc1nc2[nH]nc(N)c2c(C)c1Br",
        "COc1cc(O)c2c(c1)C(=O)c1cc(C)cc(O)c1C2=O",
        "O=C(N/[NH+]=C\\c1ccccn1)Nc1ccc(/N=N/c2ccccc2)cc1",
    ],
    [
        "Cc1ccc(-n2cnc3c(Cl)ncnc32)cc1[N+](=O)[O-]",
        "O=C1C=C[C@]2(C[C@@H](O)OC3=C2C(=O)c2oc4cc(O)c(O)",
        "CC(C)C(=O)C(C)(C)C(=O)N1CCCC1",
        "Cc1cccc(/C=[NH+]\\NC(=O)Nc2ccc(/N=N/c3ccccc3)cc2)",
        "COc1cc(C[C@@H]2COC(=O)[C@]2(O)Cc2ccc(O)c(OC)c2)c",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1c(O)ccc2ccccc12)c1c",
        "c1ccc2c(C[NH+]3CCCCC3)cccc2c1",
        "O=C(CCCc1ccncc1)c1ccccc1",
        "O=C([O-])CNC(=O)CCl",
        "Cc1c(O)c2c(c(O)c1Cc1cccc(C[NH3+])c1)C(=O)c1ccccc",
    ],
    [
        "CC(=O)Nc1ccc(CO[C@H](O)C[NH+]2CCCCC2)cc1[N+](=O)[O-]",
        "O=c1c(OC/C(=[NH+]/O)c2ccc(F)cc2)c(-c2ccccc2)oc2ccccc12",
        "CN1C(=O)/C(=C2\\Nc3ccccc3C2=O)c2ccccc21",
        "ClCC(CCl)(CCl)CCl",
        "Cc1ccc([S@@](=O)c2ccc([N+](=O)[O-])cc2[N+](=O)[O-])cc1[N+](=O)[O-]",
        "COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)cc2)ccc1O",
        "COc1ccc(CC[NH2+]C2=CC(=O)CC2)cc1OC",
        "Cc1ccccc1-c1c(N)nc(NC#N)nc1C(=O)Nc1ccccc1",
        "O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c(O)c1",
        "O=C1C[C@H](c2ccc(O)c(O)c2)Oc2cc(O)cc(O)c21",
    ],
    [
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C@@",
        "OCCCNC(=S)Nc1ccc(-c2nc3ccccc3[nH]2)cc1",
        "Nc1ncnc2c1ncn2Cc1cccnc1",
        "C=Cc1c(C)cc(C)cc1C",
        "COc1cc([C@H]2c3cc(O)c(OC)cc3C[C@]3(O)[C@@H]2C",
        "Cc1nc(NC(=O)Nc2ccccc2)sc1C(=O)NN",
        "O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)",
        "CC(=O)Nc1ccc(C(=O)Sc2ccccc2C(=O)NCCC(N)=O)cc1",
        "C[NH+](C)Cc1cc(Cl)ccc1O",
        "O=NN(CC(=O)[O-])Cc1ccccc1",
    ],
    [
        "O=C1c2ccccc2CCc2ccccc21",
        "CN(C)c1ccc(/[N+]([O-])=C/c2cc(=O)c(OS(C)(=O)=O)co2)cc1",
        "COc1cc([C@H]2c3cc(O)c(OC)cc3C[C@]3(O)[C@@H]2CO[C@@H]3O",
        "Cn1cnc(C(N)=S)c1N",
        "O=C1c2cc(O)c(O)cc2O[C@H](c2ccc(O)c(O)c2)[C@H]1O",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1c(O)ccc2ccccc12)c1ccccc1O",
        "O=C(/C=C/c1ccc(O)c(O)c1)CC(=O)/C=C/c1ccc(O)c(O)c1",
        "Cc1cccc(Cl)c1OCC(N)=O",
        "COc1ccc(S(=O)(=O)N(CC(=O)[O-])c2ccccc2)cc1",
        "Cc1cccc(-n2c(C)nc3ccc(NC(=O)NCCCl)cc3c2=O)c1",
    ],
    [
        "O=C1c2ccc(O)cc2O[C@@H](c2cc(O)c(O)c(O)c2)[C@@",
        "O=c1[nH][nH]c(=O)c2c1nc(SCCc1ccccc1)n2Cc1cccc",
        "CN(C)C(=O)OCCOc1ccc(Cl)cc1",
        "O=C(OCCO)N1CC[NH+](CCO)CC1",
        "S=C(N/[NH+]=C(\\c1ccccc1)c1ccccn1)SCc1ccccc1",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)NCc1cccc(C(F)(F)",
        "C/C(=[NH+]/C(C)(C)C)N1CCCCC1",
        "C[C@H](COC(=O)c1ccccc1)[NH2+]C1CCCCC1",
        "CCOc1cc([C@H](O)[C@@H](O)c2ccc(O)c(OCC)c2)ccc",
        "Cc1cc(O)c2c(c1)C(=O)C(c1c(C)cc3c(c1O)C(=O)C=C",
    ],
    [
        "CCOC(=O)[C@H]1C[C@H](O)C[NH2+]1",
        "Cc1ncc(C(=O)[O-])s1",
        "CN1C(=O)N(C)C(=O)C(Nc2ccc([N+](=O)[O-])cc2)(SCCO)C1=O",
        "OCCCNC(=S)Nc1ccc(-c2nc3ccccc3[nH]2)cc1",
        "CN1COc2ccc(Br)cc2C1",
        "O=C1c2ccc(O)cc2O[C@@H](c2cc(O)c(O)c(O)c2)[C@@H]1O",
        "COc1cc2ccccc2[n+](C)c1-c1ccccc1F",
        "COc1cc(C[C@@]2(O)C(=O)OC[C@H]2Cc2ccc(OC)c(OC)c2)ccc1O",
        "COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)cc2)ccc1O",
        "COc1cccc2c1C(=O)C1=C(C2=O)c2c(O)cc(CO)cc2[C@@H](O)[C@",
    ],
    [
        "CCOC(=O)/C=C1\\Nc2ccccc2C(c2ccccc2)=[NH+][C@H]1OC(C)=O",
        "COc1cc([C@@H]2Oc3c(OC)cc4ccc(=O)oc4c3O[C@H]2CO)ccc1O",
        "Cc1cc(Cc2cc(C)c(O)c(CO)c2)cc(CO)c1O",
        "C[S+](C)CCO",
        "O=C1N=C(N2CCN(c3ccccc3)CC2)N[C@@H]2CCCC[C@H]12",
        "Cc1[nH]c(N)nc(=O)c1CCCNC(=O)c1ccc(N)cc1",
        "O=C(c1cc(O)c(O)c(O)c1)c1ccc(O)c(O)c1O",
        "CCN(CC)CC#CCN(CC)CC",
        "CC(=O)Nc1ccc2c(c1)/C(=N/c1ccc(C(=O)[O-])cc1)c1ccccc1-",
        "O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc3C[C@H]",
    ],
    [
        "COc1ccc(OC)c(/C=C/C=O)c1",
        "CCCCN(CC)CC#N",
        "N#Cc1cccc(F)c1",
        "COc1c(-c2ccc(O)c(O)c2)oc2c(O)c(O)cc([O-])c2c",
        "CN(C=O)COCN(C)C=O",
        "Cc1ccc(N2CC[NH+](C[C@H](O)COc3ccccc3)CC2)cc1",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)NCc1cccc(C(F)(F",
        "O=C1OCC(c2ccc(O)cc2)=C1c1cc(O)c(O)c(O)c1",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)NCc1ccc(C(F)(F)",
        "O=C1NC(=O)C(c2ccc(C(=O)/C=C/c3c[nH]c4ccccc34",
    ],
    [
        "O=c1[nH]c(=O)ss1",
        "Cc1[nH]c2ccc(C(=O)NN)cc2c1CC(=O)NN",
        "CC(=O)Nc1ccc(C(=O)Sc2ccccc2C(=O)NCCC(N)=O)cc1",
        "COC(=O)CCc1cc(O)c2c(c1)[C@@H](C(=O)OC)[C@@H](c1ccc",
        "CC[NH+]1C[C@@H](O)C2=C/C(=[NH+]/NC(N)=O)C(=O)C=C21",
        "Cn1cc(C2=C(c3cccc(OC[C@@H](O)CO)c3)C(=O)NC2=O)c2cc",
        "COc1cc([C@H]2c3cc(O)c(OC)cc3C[C@]3(O)[C@@H]2CO[C@@",
        "C[N+](C)(C)CCOC(=O)c1ccc(CBr)cc1",
        "COc1ccc2c(c1)OC/C(=C\\c1ccc([N+](=O)[O-])o1)C2=O",
        "Cc1cccc(/C=[NH+]\\NC(=O)Nc2ccc(/N=N/c3ccccc3)cc2)n1",
    ],
    [
        "O=C(NC(=O)c1cc(-c2ccccc2)n[nH]1)c1ccccc1",
        "O=C1/C(=C/c2ccc(O)c(O)c2)CC/C1=C\\c1ccc(O)c(O)c1",
        "Cn1c2c(c3ccccc31)CCN(CCCC[NH+]1CCCCC1)C2=O",
        "O=C(CCc1ccc(O)c(O)c1)NCCc1cc(O)c(O)c(O)c1",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1c(O)ccc2ccccc12)c1ccccc",
        "CCCCCCOc1ccccc1CO",
        "O=C1C=C2C[C@@]3(O)COc4c(ccc(O)c4O)C3=C2C=C1O",
        "CCOC(=O)CNC(=O)Oc1cccc2cccnc12",
        "O=C1N[C@@H](Cc2ccccc2)C(=O)O1",
        "O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc3C[C@H",
    ],
    [
        "COc1cc(C[C@@H]2COC(=O)[C@]2(O)Cc2ccc(O)c(OC)c2)ccc1O",
        "COC(=O)C[C@@]1(C)[C@H](O)[C@H]2OC(C)(C)O[C@H]2[C@@H]1O",
        "c1ccc(/C(=[NH+]\\[NH+]=c2\\[nH]c3ccccc3s2)c2ccncc2)cc1",
        "O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c(O)c1",
        "NC(=S)Nn1c(=O)c2ccccc2c2ccccc2c1=O",
        "CCOC(=O)/C=C/c1ccc2c(c1)O[C@@H](c1ccc(O)c(OC)c1)[C@H](",
        "O=C1NC(=O)C(c2ccc(C(=O)/C=C/c3c[nH]c4ccccc34)cc2)C(=O)",
        "Cc1ccc(NC(=S)C#N)c(C)c1",
        "COC(=O)[C@H](CC=O)c1ccc(OC)cc1",
        "CC[C@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(O)c(O)cc3nc2-1",
    ],
    [
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
        "CCOC(=O)c1cnc2c(OC)cccc2c1O",
        "OCc1c(CO)c(Br)c2ccccc2c1Br",
        "COc1ccc(C)cc1S(=O)(=O)c1ccc(C)cc1[N+](=O)[O-]",
        "Cc1ccc(C(=O)C[N+]2(C)CCOCC2)cc1",
        "C1CCC[NH+](CCN2CCOCC2)CCC1",
        "O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc3C[C@H]12",
        "COC(=O)c1c(C)cc(OC(=O)c2c(C)cc(O)c(/C=[NH+]\\O)c2O)c(C)c1O",
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C@@H]1O",
        "O=C(CCl)Nc1cccc2c1C(=O)c1c(c(O)c3ccccc3c1O)C2=O",
    ],
]


- Experiment:
    name: Enrich 5(rdkit2D)

    dataset: datasets/DTP_CDDD.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [1320]
