- unique_initial_sample:
    seeds: [
    [
        "O=C(CCl)NCc1cnccn1",
        "COc1c(OC)c([O-])c2c(=O)c(C)c(/C=C/c3cc(O)cc(O)c3)oc2c1OC",
        "Cc1ccc(S(=O)(=O)N2Cc3ccc([N+](=O)[O-])cc3C2)cc1",
        "CCSC[C@H]1C[C@](O)(c2c(C)nn(Cc3ccccc3)c2C)C(=O)O1",
        "Nc1nc(N)c2nc(-c3ccc(O)cc3)c(-c3ccc(O)cc3)nc2n1",
        "CC(=O)NC(CCC(=O)c1ccc(Cl)cc1)(C(=O)[O-])C(=O)[O-]",
        "CC[C@H](C)[C@H](N)C(=O)NCC(=O)OC",
        "C/C(=[NH+]\\S(=O)(=O)c1cccc([N+](=O)[O-])c1)OCC(C)C",
        "COc1ccc(/C=N/n2c(-c3ccccc3)n[nH]c2=O)c(OC)c1",
        "OC[C@H]1O[C@@H](Oc2cc(/C=C/c3ccc(O)cc3)ccc2O)[C@H](O)[C@@H](O)[C@@H]1O",
    ],
    [
        "CC(=O)Nc1ccc(S(=O)(=O)c2ccc(NC=O)cc2)cc1",
        "CCCCN1C(=O)NC(=O)[C@@]1(C)c1ccccc1",
        "c1ccc(C2=[NH+]N[C@@H]3c4ccccc4-c4ccccc4N3C2)cc1",
        "CCCCCC1(C(C)C)C(=O)NC(=O)NC1=O",
        "CC(=O)Nc1ccc(CCNC(=O)c2ccc3ccccc3c2O)cc1",
        "CCCCc1cc(O)ccc1O",
        "CSC(=[NH2+])c1cccc(CCCCc2ccc(NC(C)=O)cc2)c1",
        "COc1cc([C@@H]2C[C@@](C)(O)Oc3cc4c(cc32)OCO4)cc(OC)c1O",
        "C/C=C/[C@H](C(=O)NC(N)=O)C(C)C",
        "C=CCNC(=S)NCc1cccc2ccccc12",
    ],
    [
        "CCN(CC)/[NH+]=C/C[C@H](C)Nc1ccnc2cc(Cl)ccc12",
        "CC1(C)CC(=O)C(c2c(-c3ccccc3)[nH]c3[nH]c(=S)[nH]c(=O)c23)=C([O-])C1",
        "CC(=O)Nc1nc(N)nc2c1C[C@H](N(Cc1ccc(Cl)cc1)C(C)=O)CC2",
        "O=C([O-])c1cccc(O)c1O",
        "O=CNc1cc(Br)cc2c1[nH]c(=O)c1ccccc12",
        "CCOC(=O)/C=C/c1ccc2c(c1)O[C@@H](c1ccc(O)c(OC)c1)[C@H](CO)O2",
        "CC(C)(C)C[NH+]1CCCN(c2ccc(Cl)cc2)C1",
        "CC(C)=CC[C@@H](OC(=O)CC(C)(C)O)C1=CC(=O)c2c(O)ccc(O)c2C1=O",
        "COc1cccc(P(c2cccc(OC)c2)c2cccc(OC)c2)c1",
        "Cc1cccn2ncnc12",
    ],
    [
        "CC(=O)NC1=C([NH3+])C(=O)c2ccccc2C1=O",
        "COc1ccc2c(c1)C(=O)c1c-2n(CCCCl)c(=O)c2cc(N)ccc12",
        "O=C([O-])[C@H](c1ccccc1)c1cccc([C@@H](C(=O)[O-])c2ccccc2)n1",
        "Oc1ccc([C@H]2COc3c(ccc(O)c3O)C2)cc1",
        "OCCCCC[NH2+]C1CCCCC1",
        "C1=Nc2c(ncnc2SCc2ccccc2)NN1",
        "CC1(C)O[C@@H]1C(=O)[O-]",
        "O=C1/C(=C/c2ccc(O)c(O)c2)Cc2ccccc21",
        "c1nc2c3c4c(sc3ncn2n1)CCCC4",
        "O=C(N[C@H]1c2ccccc2C[C@H]1O)[C@H](Cc1ccccc1)NCC(F)(F)F",
    ],
    [
        "COc1ccc(Cl)c(S(N)(=O)=O)c1",
        "Nc1nc(N)c(CCCNc2ccccc2)c(Cc2ccccc2)n1",
        "CCOC(=O)/C=C/c1ccc(N)cc1",
        "O=c1[nH]nc2c3cccc4cccc(c5ccc([O-])c1c52)c43",
        "CN(C=O)c1cc([N+](=O)[O-])ccc1OCc1ccccc1",
        "O=C(N/[NH+]=C\\C(F)(F)F)c1ccncc1",
        "O=C(c1ccccc1)[C@H]([C@H](O)CCl)C(O)(C(F)(F)F)C(F)(F)F",
        "CCOC(=O)N[C@H]1[C@@H]2OC(C)(C)O[C@@H]2O[C@H]1CC(=O)OC",
        "C[C@@H]1C[C@H](C)Nc2c(O)c3c(c(O)c21)C(=O)c1ccccc1C3=O",
        "Cc1cc(C(=C2C=CC(=[NH2+])C=C2)c2ccc(N)cc2)ccc1N",
    ],
    [
        "CS(=O)(=O)Oc1ccc([N+](=O)[O-])cc1",
        "CCCC1(C)[C@@H](C#N)C(=O)NC(=O)[C@@H]1C#N",
        "O=[N+]([O-])c1cccc([C@@H]2CC(c3ccccc3)=[NH+]N2c2ccccc2)c1",
        "COc1ccc(/C=C2\\Oc3cc(O)ccc3C2=O)cc1O",
        "Cc1c([N+](=O)[O-])ccc2cccnc12",
        "COc1c2c(c(OC)c3c1C(=O)c1ccccc1[C@@H]3O)CC=CC2",
        "CCn1c(Cl)c(/C=[NH+]\\Nc2ccc([N+](=O)[O-])cc2)c2ccccc21",
        "N#CS/C=C\\C(N)=O",
        "N#C/C(=C\\c1ccc(O)c(O)c1)c1c(C#N)c(N)nn1-c1ccccc1",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)C[C@H]([C@@](C)(O)CCl)O2",
    ],
    [
        "CCc1ccccc1-n1c(=O)c(C#N)c(-c2ccc(O)cc2)c2c(N)n[nH]c21",
        "COc1ccc([C@H]2COc3c(ccc(O)c3O)C2)cc1OC",
        "NC(=O)c1cccc(NC=O)c1",
        "CC(=O)c1ccccc1Br",
        "COc1ccc([C@@H](O)C(=O)c2nc3ccc([N+](=O)[O-])cc3nc2O)cc1",
        "C=C(Br)C[NH2+]CCCCCC",
        "CCOC(=O)c1[nH]c(CO)c(C(=O)OCC)c1C",
        "C[C@H]1CN(c2ccncc2[N+](=O)[O-])CCN1c1ccc(Cl)cc1",
        "CCC[C@H]1OCCN1CC",
        "O=C1C=C(c2c(O)ccc3ccccc23)c2cc(O)ccc2C1=O",
    ],
    [
        "CCC(=O)Oc1cccc(OC(=O)CC)c1",
        "COc1cc(NC/C(C)=[NH+]/NC(N)=O)c2ncccc2c1",
        "Nc1nc(Cl)c2c(n1)CCC2",
        "Nc1ncnc2c1ncn2-c1ccccc1Cl",
        "O=C1Nc2ccccc2[C@H]1Cc1cc2c3ccccc3nc-2[nH]n1",
        "O=C(/C=C/c1ccc(O)c(O)c1)c1ccc(O)c(O)c1O",
        "C[C@H]1CC[C@]23COC(=O)C2=CCC[C@H]3[C@]1(C)CC/C(=C/CO)CO",
        "O=C1C[C@H](c2ccc(O)c(O)c2)Oc2cc(O)cc(O)c21",
        "COc1cc2c3c(c4cc(OC)c(OC)cc4c2cc1OC)C[NH+]1CCC[C@H]1C3",
        "CCN(CC)C(=O)Nc1cccc(O)c1",
    ],
    [
        "CC1(C)C[C@@](O)(Cc2ccccc2)[C@H](O)c2ccccc21",
        "COc1ccc(/C=C\\c2cc(OC)c(OC)c(OC)c2)c(O)c1O",
        "C[NH+]1C(C)(C)CC(O)(C(=O)[O-])CC1(C)C",
        "Nc1ncc2[nH]c(=O)[nH]c2n1",
        "Cn1cc(C(=O)c2ccccc2)cc(C(=O)c2ccccc2)c1=O",
        "CCCCCCC[C@@H]1OCC[C@H](C)O1",
        "Cc1c(-c2ccc(O)c(O)c2)oc(=O)c2c([O-])cccc12",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1ccc(O)cc1)c1ccccc1O",
        "CCOc1ccc(N)c(SCC(=O)[O-])c1",
        "S=C1Nc2ccccc2CS1",
    ],
    [
        "CCOc1nc(C)cc(C(=O)[O-])c1C#N",
        "O=C(NN1C(=O)CS[C@H]1c1c(Cl)cccc1Cl)[C@H](O)c1ccccc1",
        "COC(=O)N1[C@@H](N2CCCC2=O)C(C)(C)S1(=O)=O",
        "CCOC(=O)CCN1C(=O)CC[C@H]1C(=O)OCC",
        "NC(=O)N/[NH+]=C\\c1ccc(O)cn1",
        "C1CSC(N2CCOCC2)=N1",
        "COc1cc2c(ccc3cc(O)c(OC)c(OC)c32)cc1O",
        "COc1cccc([C@@H]2CCCC[C@@H]2O)c1",
        "O=C(NNC(=O)c1cccc2ccccc12)c1cccc(F)c1",
        "Cc1cccc(/C=[NH+]\\NC(=O)Nc2ccc(/N=N/c3ccccc3)cc2)n1",
    ],
    [
        "C[C@H](CC(=O)c1ccc(F)cc1)[NH+]1CCCCC1",
        "CSCC[C@H]([NH3+])[P@](C)(=O)[O-]",
        "O=C1c2ccccc2C(=O)c2c1nc(-c1ccc(Cl)cc1)n2O",
        "O=C(Cn1c(=O)ccc2ccccc21)Cn1c(=O)ccc2ccccc21",
        "COc1cc(C[C@H]2CO[C@H](c3ccc(O)c(OC)c3)[C@H]2CO)ccc1O",
        "CC1(C(Cl)(Cl)Cl)C=CC(=[NH+]OCC(=O)[O-])C=C1",
        "CCOC(=O)[C@@H](Cc1ccccc1C(=O)NC)c1ccccc1",
        "CCO/[NH+]=C(\\C)C(=O)NNS(=O)(=O)c1ccc(C)cc1",
        "CCOC(=O)[C@@H](CC(C)C)NC(=O)c1cc2ccccc2[n+](C)c1",
        "Cc1ccc(/C=[NH+]/NC(N)=[NH2+])cc1",
    ],
    [
        "O=C(N/[NH+]=C\\c1ccc2c(c1)CCC2)c1cccc2ccccc12",
        "COc1cc([C@H]2Oc3c(OC)cc(/C=C/C(N)=O)cc3[C@@H]2C(N)=O)ccc1O",
        "C[S@@](=O)CCC[NH+]=C=S",
        "CS(=O)(=O)Oc1ccccc1C(=O)[O-]",
        "COc1ccc(C[C@H](CO)NC(=O)c2ccccc2)cc1",
        "CCCCN1C(=O)C(=O)N(c2ccc(NC(C)=O)cc2)C1=O",
        "CC[C@H](Cc1ccco1)C(=O)[O-]",
        "CC(C)[C@H](C)C1=CC(=O)C=CC1=O",
        "COc1ccc([C@H]2[C@@H](Cl)C(=O)N2NC(=O)c2ccccc2O)cc1OC",
        "NC(=O)c1ccc[n+](Cc2ccccc2)c1",
    ],
    [
        "O=C1N[C@@](O)(c2ccccc2)c2ccccc21",
        "Nc1nnc2nc(CC(=O)c3ccc4ccccc4c3)c(=O)[nH]n12",
        "O=C(c1ccccc1)N1[NH+]=CCC[C@@H]1O",
        "CCOC(=O)[C@@H](C)Sc1n[nH]c(=O)[nH]c1=O",
        "O=C1OC[C@H]2[C@H](c3ccc(O)c(O)c3)c3cc(O)c(O)cc3C[C@H]12",
        "CC[C@@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(O)ccc3nc2-1",
        "CCOC(=O)N/[NH+]=C/c1ccc(OC)c(O)c1",
        "O=c1cccc2n1Cc1cc3ccccc3nc1-2",
        "CN(C)/C=N/c1ccc(F)cc1",
        "Cc1cc(O)c2cc(Cc3ccc(N)cc3)ccc2n1",
    ],
    [
        "NC(=O)c1c(N)nn2c(-c3ccccc3)cc(-c3ccccc3)cc12",
        "CC(=O)Nc1ccc(S(=O)(=O)c2ccc(NC=O)cc2)cc1",
        "CCCCOC(=O)[C@@H]([NH3+])Cc1ccc(OC)c(Cl)c1",
        "CC(=O)Oc1cccnc1",
        "COc1ccc(-c2ccc([C@@H]3CC(c4ccc(Cl)cc4)=[NH+]N3)o2)c([N+](=O)[O-])c1",
        "CCCC(=O)Nc1ccc(C)cc1",
        "CN1[NH+]=C2c3ccccc3CC[C@H]2[C@@H]1c1cccc(O)c1",
        "Cc1ccc(NC(=S)NC(=O)COc2ccccc2)cc1C",
        "COC(=O)Cc1cc(O)cc2oc(-c3ccc(O)c(OC)c3)cc(=O)c12",
        "CCO/C=[NH+]\\C1=C(C#N)SC2=N/C(=C\\c3ccco3)C(=O)N21",
    ],
    [
        "Fc1cc(Cl)ccc1Cl",
        "CCOC(=O)/C(=C\\c1ccc(Cl)cc1)C(C)=O",
        "Cc1cccc(CNc2cccc(C)n2)n1",
        "O=C(CCl)Nc1cccc2c1C(=O)c1c(c(O)c3ccccc3c1O)C2=O",
        "CC(C)(C)[Si](C)(C)OC[C@]12CC[C@H]3C[NH2+][C@H]([C@H]31)[C@H](c1ccccc1)N2",
        "O[C@H](COc1ccccc1)CC(O)(C(F)(F)F)C(F)(F)F",
        "CCn1cc(C(=O)[O-])c(=O)c2ccc(C)[n+](C)c21",
        "CC(=O)C(=Cc1cccc([N+](=O)[O-])c1)C(C)=O",
        "Oc1ccc(O)c(CNc2ccc([C@@H](O)C(F)(F)F)cc2)c1",
        "COc1ccc([C@](O)(c2ccccc2)[C@H](C)O)cc1",
    ],
    [
        "Nc1nc(N)c(NC/C=C\\c2ccc([N+](=O)[O-])cc2)c(-c2ccccc2)n1",
        "CC(=O)Nc1nc(-c2nnc(S)n2-c2ccc(Cl)cc2)cs1",
        "COc1c(O)cc2c(c1O)C(=O)/C(=C/c1ccc(O)cc1)CO2",
        "CC(=O)Nc1ccc(S(=O)(=O)CCBr)cc1",
        "O=c1c2ccccc2ncn1-c1ccc(O)c(C[NH+](CCCl)CCCl)c1",
        "O=C([O-])c1ccc(Oc2ccccc2)cc1",
        "COc1ccc([C@H](O)CC(O)(C(F)(F)F)C(F)(F)F)cc1",
        "O=c1cc(-c2ccc(O)cc2)oc2ccccc12",
        "CCc1nnn(-c2ccccc2)c1C",
        "O=C(Cl)c1ccc(C(F)(F)F)cc1",
    ],
    [
        "CCOC(=O)/C=C/c1ccc2c(c1)O[C@H](CO)[C@H](c1ccc(O)c(OC)c1)O2",
        "O=C(Oc1ccccc1)c1cc2ccccc2oc1=O",
        "CC(=O)N[C@H](CS(=O)(=O)Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "CC(=S)NC(=O)NC(=O)c1ccc(C)cc1",
        "NC(=O)[C@H](c1ccccc1)C(O)(c1ccccc1)c1ccccc1",
        "CCOC(=O)/C(C#N)=C(\\C)c1ccccc1",
        "O=c1nc(SCc2ccccc2)[nH]c(Cc2ccccc2)c1CCO",
        "COC(Cn1cnc2c(N)ncnc21)OC",
        "NC(=O)N(CCc1ccccc1)N=O",
        "Oc1ccc(O)c(CNc2ccc([C@@H](O)C(F)(F)F)cc2)c1",
    ],
    [
        "N#C[C@@H](OC(=O)c1ccccc1)c1cccc([N+](=O)[O-])c1",
        "COc1cc(C(=O)C[C@]2(O)C(=O)Nc3c(Cl)cc(Cl)cc32)ccc1O",
        "O=C([O-])c1cccc(N2C(=O)CSC2=S)c1",
        "Cc1ncc(CO)c(CSSCc2c(CO)cnc(C)c2O)c1O",
        "CC(C)[C@@H](NC(=O)c1cnc2ccccc2n1)C(=O)N[C@@H](C)C(=O)[O-]",
        "O=c1[nH]c(Nc2cccc(CC(F)(F)F)c2)nc2[nH]cnc12",
        "O=c1c2ccccc2sc2c1c(N(CCO)CCO)cc1ccccc12",
        "COc1c(O)cc2c(c1OC)-c1ccc(SC)c(=O)cc1C[C@H](NC=O)C2",
        "COc1cc(O)c2c(c1)C(=O)c1cc(C)cc(O)c1C2=O",
        "O=C(Nc1ccc(S(=O)(=O)[O-])cc1)c1ccco1",
    ],
    [
        "Cc1ccc(-n2cnc3c(Cl)ncnc32)cc1[N+](=O)[O-]",
        "COc1ccc([C@]2(C(OC)OC)NC(=O)N(C)C2=O)cc1",
        "CC(C)C(=O)C(C)(C)C(=O)N1CCCC1",
        "O=C([O-])/C=C\\C(=O)Nc1ccc2c(c1)[C@H](NC(=O)C(F)(F)F)c1ccccc1-2",
        "COc1ccccc1C(=O)Sc1ccccc1C(=O)N[C@H](C(N)=O)C(C)C",
        "Cn1c(=O)nc2n(-c3ccc(Cl)cc3)c3ccc(Cl)cc3nc-2c1=O",
        "O=C1CC2(CCCC2)CC(=O)N1c1ccc(O)c(CN2CCOCC2)c1",
        "O=C(CCCc1ccncc1)c1ccccc1",
        "O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c(O)c1",
        "O=C(/C=C/c1ccccc1)C1=C([O-])C(=O)O[C@H]1c1ccccc1",
    ],
    [
        "O=C1C=CC[C@H](/C=C/C[C@@H](O)C[C@H](O)/C=C/c2ccccc2)O1",
        "NC(=O)COc1c(Cl)cc(Cl)cc1Cl",
        "CN1C(=O)/C(=C2\\Nc3ccccc3C2=O)c2ccccc21",
        "NC(=O)c1c(N)nn2c(-c3ccccc3)cc(-c3ccccc3)cc12",
        "CC(=O)Nc1ccc2c(c1)[nH]c(=O)c1ccccc12",
        "COc1cccc(C2=C(c3cn(C)c4ccccc34)C(=O)NC2=O)c1",
        "COc1ccc(CC[NH2+]C2=CC(=O)CC2)cc1OC",
        "C[NH+](CCCl)C[C@@H]1CSCO1",
        "O=C1NC(=O)/C(=C/c2ccc(Cl)cc2Cl)N1",
        "C/N=N\\C(C)C",
    ],
    [
        "N#Cc1sc(=S)n(-c2ccccc2)c1N",
        "Cc1cc(OCCc2ccccc2)ccc1Nc1cc(=O)[nH]c(=O)[nH]1",
        "CC[C@@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cccc(N)c3nc2-1",
        "C=Cc1c(C)cc(C)cc1C",
        "O=c1ccc(=O)c2c1c1[nH]c3ccccc3c1c1c(=O)c3ccccc3c(=O)c21",
        "CO[C@@H]1[C@H](O)c2coc3c2[C@@](C)(c2ccc4c(c2C3=O)CCC4=O)[C@@H]1O",
        "O=C(N[C@H]1CCC[C@@H]1O)c1ccccc1",
        "CN(N=O)C(=O)NCCOC(=O)N(C)N=O",
        "C[NH+](C)Cc1cc(Cl)ccc1O",
        "O=NN(CC(=O)[O-])Cc1ccccc1",
    ],
    [
        "NC(=O)c1cccc(SSc2cccc(C(N)=O)c2)c1",
        "CN(C)c1ccc(/[N+]([O-])=C/c2cc(=O)c(OS(C)(=O)=O)co2)cc1",
        "C[C@@]12c3ccc4c(c3C(=O)c3occ(c31)[C@@H](O)C[C@H]2O)CCC4=O",
        "Cn1cnc(C(N)=S)c1N",
        "C[NH2+]C1(c2ccc(F)cc2)CCCCC1",
        "N#Cc1c(N2CC[C@H](O)C2)c2ccccc2n2c1nc1ccccc12",
        "O=C(c1ccc([N+](=O)[O-])cc1)c1ccc(O)cc1O",
        "Cc1cccc(Cl)c1OCC(N)=O",
        "C/C=C/C=N/c1c(C#N)c2n(c1C(=O)Nc1ccc(S(N)(=O)=O)cc1)CCC2",
        "CCO[C@H]([C@@H](OCC)[n+]1ccccc1)[n+]1ccccc1",
    ],
    [
        "Cn1cc(C2=C(c3cccc(Cl)c3)C(=O)NC2=O)c2ccccc21",
        "O=C1c2ccccc2C(=O)c2c(O)c(NCCO)cc(O)c21",
        "Cc1c2ccccc2c(CSCC[C@H]([NH3+])C(=O)[O-])c2ccc3ccccc3c12",
        "O=C(OCCO)N1CC[NH+](CCO)CC1",
        "S=C(N/[NH+]=C(\\c1ccccc1)c1ccccn1)SCc1ccccc1",
        "O=C([O-])C(=Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "C/C(=[NH+]/C(C)(C)C)N1CCCCC1",
        "C[C@H](COC(=O)c1ccccc1)[NH2+]C1CCCCC1",
        "NC(=O)N[C@H]1C[C@@H]1c1ccc(Cl)c(Cl)c1",
        "COc1ccc2c(c1)CC[C@@H]1[C@@H]2CC[C@]2(C)[C@@H](O)[C@@H](O)C[C@@H]12",
    ],
    [
        "CCOC(=O)[C@H]1C[C@H](O)C[NH2+]1",
        "COc1ccc2cc(C(N)=O)/c(=N/c3cccc(C#N)c3)oc2c1",
        "CN1C(=O)N(C)C(=O)C(Nc2ccc([N+](=O)[O-])cc2)(SCCO)C1=O",
        "O=NN(CCCl)C(=O)Nc1ccc(CC(=O)[O-])cc1",
        "COc1ccc2c(c1)C/C(=C\\c1ccc(O)c(OC)c1)C2=O",
        "C[N+](C)(C)CC(=O)N/[NH+]=C/c1ccc([N+](=O)[O-])o1",
        "COc1cc2ccccc2[n+](C)c1-c1ccccc1F",
        "O=C(Nc1c(C(=O)NC2CCCCC2)[nH]c(=O)[nH]c1=O)c1ccc(Cl)cc1",
        "[O-][n+]1cc[n+]([O-])c2c3ccccc3ccc21",
        "Cn1cc(C2=C(c3cccc(OC[C@@H](O)CO)c3)C(=O)NC2=O)c2ccccc21",
    ],
    [
        "CCOC(=O)/C=C1\\Nc2ccccc2C(c2ccccc2)=[NH+][C@H]1OC(C)=O",
        "C/C(CCO)=[NH+]\\NC(N)=S",
        "COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)c(O)c2)ccc1O",
        "CC[C@@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(N)ccc3nc2-1",
        "O=C1N=C(N2CCN(c3ccccc3)CC2)N[C@@H]2CCCC[C@H]12",
        "C=CC[C@@]1(O)c2cccc(O)c2C(=O)c2cccc(O)c21",
        "CCCCc1ccc([I+]c2cccc([N+](=O)[O-])c2)cc1",
        "CCN(CC)CC#CCN(CC)CC",
        "O=C(/C=C/c1ccc(O)cc1)CC(=O)/C=C/c1ccc(O)cc1",
        "COC(=O)c1ccccc1NC(=S)NC(=O)COc1ccccc1",
    ],
    [
        "COc1ccc(OC)c(/C=C/C=O)c1",
        "COc1c2c(c(OC)c3c1C(=O)c1cccc(O)c1C3=O)CC[C@](O)(C(C)=O)C2",
        "COc1cc2c(cc1O)C[C@]13CCC(=O)N1CCc1cc(OC)c(O)c-2c13",
        "Cc1cc2ccccc2nc1Cl",
        "CN(C=O)COCN(C)C=O",
        "Cc1ccc(N2CC[NH+](C[C@H](O)COc3ccccc3)CC2)cc1",
        "O=c1oc(-c2ccc(O)c(O)c2)cc2cc(O)cc([O-])c12",
        "COc1ccc(/C=C2/SC(=O)NC2=O)cc1OC",
        "O=Cc1c(O)c(C(=O)Nc2ccc3[nH]c(=O)[nH]c3c2)cc2ccccc12",
        "O=c1cc(CC(O)(c2ccccc2)c2ccccc2)cc[nH]1",
    ],
    [
        "CC[C@@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(Cl)ccc3nc2-1",
        "Cc1[nH]c2ccc(C(=O)NN)cc2c1CC(=O)NN",
        "Cc1ccccc1C(=O)[C@@H]1CCCCC1=O",
        "COc1cc2occ(-c3ccc(O)c(O)c3)c(=O)c2cc1O",
        "CC[NH+]1C[C@@H](O)C2=C/C(=[NH+]/NC(N)=O)C(=O)C=C21",
        "COc1ccccc1[C@@H](C)c1ccc2ccccc2c1C(=O)[O-]",
        "COc1cccc([C@@H]2C3=C(COC3=O)N(CCO)c3cc4c(cc32)OCCO4)c1",
        "O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c(O)c1",
        "COc1ccc2c(c1)OC/C(=C\\c1ccc([N+](=O)[O-])o1)C2=O",
        "COc1c(O)ccc2c1C[NH+]1CCc3cc4c(cc3[C@@H]1C2)OCO4",
    ],
    [
        "C[C@]12CCC(=O)C=C1CC[C@@H]1[C@@H]2CC[C@]2(C)[C@@H](C(=O)CO)CC[C@@]12O",
        "C(=[NH+]/[NH+]=C/c1cccs1)\\c1cccs1",
        "Cn1c2c(c3ccccc31)CCN(CCCC[NH+]1CCCCC1)C2=O",
        "C/C(=[NH+]\\NC(N)=S)c1ccc2c(c1)Cc1cc(/C(C)=[NH+]/NC(N)=S)ccc1-2",
        "CC(=O)N[C@H](C)C(=O)N(C)/N=N/c1ccc(C#N)cc1",
        "CCCCCCOc1ccccc1CO",
        "CC(=O)c1c(COc2ccc(Cl)cc2)[n+]([O-])c2ccccc2[n+]1[O-]",
        "CCOC(=O)CNC(=O)Oc1cccc2cccnc12",
        "COc1ccc([C@H]2COc3c(ccc(O)c3O)C2)cc1OC",
        "COc1ccc([C@H](O)[C@@H](C)C(O)(C(F)(F)F)C(F)(F)F)cc1",
    ],
    [
        "C=C1[C@H](O)C[C@@H]([C@@H](C)[C@H](O)CC=C(C)C)[C@@H](O)[C@@H]2C(C)=CC[C@@H]12",
        "COC(=O)C[C@@]1(C)[C@H](O)[C@H]2OC(C)(C)O[C@H]2[C@@H]1O",
        "c1ccc(/C(=[NH+]\\[NH+]=c2\\[nH]c3ccccc3s2)c2ccncc2)cc1",
        "Cc1cccc(Cl)c1",
        "CSC[C@H]1Cc2c(cc3c(c2O)C(=O)c2ccccc2C3=O)O1",
        "O=C1NCc2nnn(Cc3ccccc3)c2N1",
        "N#CCN(Cc1ccccc1)[C@@H]1CCC[C@]1(O)C#Cc1ccc2c(c1)OCO2",
        "Cc1ccccc1C1=[NH+]/C(=C/c2c(O)ccc3ccccc23)C(=O)O1",
        "COC(=O)[C@H](CC=O)c1ccc(OC)cc1",
        "CC(C)(CC(=O)[O-])NC(=O)CN",
    ],
    [
        "CC1(C)CC(=O)c2c(oc(=O)c3ccccc23)C1",
        "CCOC(=O)c1cnc2c(OC)cccc2c1O",
        "O=C(N/[NH+]=C\\c1ccc2c(c1)CCC2)c1cccc2ccccc12",
        "COc1ccc(C)cc1S(=O)(=O)c1ccc(C)cc1[N+](=O)[O-]",
        "Cc1ccc(O)c(C2=CC3=[NH+]NC(=O)[C@@H]3[C@@H](c3cccc(Cl)c3)C2)c1",
        "COc1cc2c(c(O)c1C)C(=O)C[C@H](c1ccccc1)O2",
        "Cc1cc(O)c(C(C)C)cc1C[NH+]1CCCCC1",
        "COc1cc([C@H](O)C(=O)c2nc3ccc([N+](=O)[O-])cc3nc2O)ccc1O",
        "C=C(C)[C@H]1C[C@@H]2O[C@]2(C)[C@@H](O)C1",
        "O=[N+]([O-])c1cc/c(=[NH+]\\[NH+]=C/c2ccc(O)c(S(=O)(=O)[O-])c2)[nH]c1",
    ],
]


- Experiment:
    name: Enrich 4(RF MQN padre greedy)

    dataset: datasets/DTP_MQN.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy
        use_pairwise: True

    metrics: 
        names: [top-k, top-k-acquired]
        k: [1320]
