- unique_initial_sample:
    seeds: [
    [
        "O=C(Nc1ccc(Nc2ncccn2)cc1)c1cn[nH]c1-c1ccco1",
        "O=C1CCc2cc(CC(=O)N[C@H]3C[C@H](Cn4cccn4)C[C@@H]3O)ccc2N1",
        "COc1ccnc(NC[C@]23C[C@](NC(=O)[C@@H]4C[C@@H]4C)(C2)C(C)(C)O3)n1",
        "Cc1csc(N2CCN(C(=O)c3ccc(C(=O)NC4CC4)cc3)C[C@H]2C)n1",
        "CN1C(=O)CCc2cc(NC(=O)NC[C@@H](O)c3ccccc3)ccc21",
        "NC(=O)NC[C@@H]1CCCN(C(=O)NCCc2ccccc2C(F)(F)F)C1",
        "Cc1cccc2c(CCN3C(=O)[C@H]4C[C@@H]5CCCC[C@@H]5N4C3=O)c[nH]c12",
        "O=C(Nc1cc(C2CC2)nn1-c1ccccc1)N[C@H](Cn1ccccc1=O)c1ccccc1",
        "Cc1cccc([C@@H]2CCCN2C(=O)NCc2ccc(S(C)(=O)=O)cc2)n1",
        "COc1ccc(CNC(=O)[C@H]2CCCN2C(=O)[C@]23C[C@H]4C[C@H](C[C@H](C4)C2)C3)cn1",
    ],
    [
        "O=C(NCc1ccc(C(=O)N2CCCCC2)cc1)N1CCn2cncc2C1",
        "COc1cc(-c2noc([C@H]3NCCOc4ccccc43)n2)ccc1C",
        "Cc1ccccc1CNc1cc(C(N)=O)ccc1Cl",
        "COc1ccc(OC)c([C@@H]2CCCN2C(=O)c2ccnc(OC)n2)c1",
        "C=CCN(CC(=O)[O-])S(=O)(=O)c1ccc(OC)c(Cl)c1",
        "CCc1ccc(-c2ccc(C(=O)N(CC(=O)NC)C[C@H]3CCN(S(C)(=O)=O)C3)o2)cc1",
        "COC[C@@H]1CN(C(=O)c2ncoc2C2CC2)CCO1",
        "C[C@H]1C[C@H](CO)CN(C(=O)C(=O)N[C@H]2CC(C)(C)c3ccccc32)C1",
        "NC(=O)C[C@H]1CN(C(=O)NCC2(c3cccc(Br)c3)CC2)C[C@@H]1O",
        "CC[NH+]1CCN([C@@H]2CCN(C(=O)Cc3cncs3)C2)CC1",
    ],
    [
        "CC(C)C[C@H]1C(=O)NCCN1C(=O)c1cc(O)nc(C(C)C)c1",
        "O=C(Cc1ccc(-n2cnnn2)cc1)Nc1cnn(C[C@@H]2CCCO2)c1",
        "Cc1nc(NCc2cccc(N3CCCCC3=O)c2)cc(-c2ccccn2)n1",
        "O=C(c1ccnn1C1CCCC1)N1CCN(c2cncc3ccccc23)CC1",
        "O=C(NCc1ccc2c(c1)CCC2)c1ccc(NS(=O)(=O)c2ccc3[nH]c(=O)[nH]c3c2)cc1",
        "Cc1noc(C2CCN(C(=O)[C@H](Cc3ccccc3)NC(N)=O)CC2)n1",
        "Cc1cc(C)n(CC(=O)NC[C@@H]2CC[C@@H](c3ncn[nH]3)O2)n1",
        "COc1ccc(CC2CCN(C(=O)[C@H](O)c3cccnc3)CC2)cc1",
        "O=C(CCNC(=O)[C@H]1CCCN1C(=O)Cc1ccccc1)NCc1cccnc1",
        "O=C1CC[C@H](C(=O)N2CCN(c3ccc(C(F)(F)F)cc3)CC2)N1",
    ],
    [
        "CCOc1cc2c(cc1CNC(=O)N1CCC(CC(=O)NC3CCCC3)CC1)O[C@H](C)C2",
        "Cc1c(C(=O)N[C@@H](CO)c2ccc(F)cc2)nnn1-c1cccc2cnccc12",
        "O=C(Nc1ccc2c(c1)C(=O)NCC2)N[C@H]1C[C@@H]2C[C@H]1[C@@H]1CCC[C@@H]21",
        "CC[C@@H](CC#N)NC(=O)c1nnc2ccc(Br)cn12",
        "O=C(c1cccc(Cn2ccnn2)c1)N1C[C@H]2COC[C@@H]2C1",
        "C[C@H](Cc1nc(-c2ccccc2)no1)NC(=O)c1cccc(C#N)c1",
        "CCc1ccc(CCNC(=O)c2ccc(C3(O)COC3)cc2)cc1",
        "C[C@H]1CN(c2nnc(-c3ccccc3)n2C[C@@H]2CCCO2)CCS1",
        "COCC1(C)CCN(C(=O)Nc2ccc(-n3cccn3)nc2)CC1",
        "O=C1C[C@@H](Cc2ccc(C(=O)N3CCC[C@@H]3CO)cc2)C(=O)N1",
    ],
    [
        "Cc1cc(C)cc(-n2nc(C(=O)N3CCCC[C@@H]3c3cn[nH]c3)cc2C)c1",
        "Cc1cc(C(=O)N[C@H]2[C@@H]3CCO[C@H]3C23CCC3)nc2nc(O)[nH]c(=O)c12",
        "O=C(CCc1nc(-c2ccoc2)no1)N1CCC[C@@](O)(C(F)(F)F)CC1",
        "O=C(NCc1oc2ccc(Cl)cc2c1-c1ccccc1)[C@H]1CCOC1",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "O=C(NC[C@H]1CCC[N@H+](Cc2ncon2)C1)c1cccc(-n2cncn2)c1",
        "Cc1cccc2nc(N3CC[C@H](S(C)(=O)=O)C3)sc12",
        "COCC1(O)CCN(C(=O)c2cc(C(F)(F)F)ccc2F)CC1",
        "CCc1onc(C)c1NS(=O)(=O)c1ccc(OCC(=O)[O-])c(Cl)c1",
        "Cn1c(=O)oc2ccc(CNC(=O)NC[C@H]3C[C@@H]3c3ccccc3)cc21",
    ],
    [
        "O=C([C@H](O)[C@@H](O)c1nc2ccccc2[nH]1)N1CCN(c2ncccn2)CC1",
        "C[C@H]([NH3+])[C@@H]1CCCN(c2ccc(-c3ccc(Cl)s3)nn2)C1",
        "CC(C)C(=O)NC[C@@H]1CCCN(C(=O)c2c3c(nc4ccccc24)CCC3)C1",
        "CNC(=O)[C@H](NC(=O)[C@@H]1C[C@@H]1c1ccc(C(F)(F)F)cc1)c1ccccc1",
        "O=C([C@@H](O)Cc1ccccc1)N1CCC(c2ccc(F)cc2)CC1",
        "CCc1onc(C)c1NC(=O)NCC1CCc2ccccc2CC1",
        "Cc1ccc(F)cc1C(=O)NC(C)(C)c1cn(C)nn1",
        "CCOc1c(Cl)cc(CNc2ccc3nc(C)nn3n2)cc1OC",
        "O=C(C[C@@H]1CCc2ccccc2C1)N1CCC(c2nnc3n2CC[NH2+]C3)CC1",
        "O=C(c1ccc(F)cc1)N1CCCN(C(=O)[C@@H](O)c2ccc(Cl)cc2F)CC1",
    ],
    [
        "NC(=O)c1cc(NC(=O)N2CCOC[C@@H]2[C@@H]2CCCC[C@H]2O)ccc1F",
        "CCc1ccsc1C(=O)N1CCC(N2CCNC2=O)CC1",
        "CCS(=O)(=O)N1CCN(c2nnc(-c3cccn3C)n2C)CC1",
        "Cn1cc(-n2cc(C(=O)N3CCN(c4cccc(C(F)(F)F)c4)CC3)ccc2=O)cn1",
        "O=C(c1ccccc1)N1CCN(C(=O)C2CCOCC2)CC1",
        "Cc1ccncc1N1CCN(C(=O)c2cc(N3CCCC3=O)ccc2F)CC1",
        "O=C(NCc1ccc(-n2ccnc2)nc1)Nc1ccc(CN2CCCC2=O)cc1",
        "Cn1cc(-c2ccc(F)c(C(=O)NC[C@@]3(C)CCCC[C@@H]3O)c2)cn1",
        "COc1ccc(CNC(=O)[C@H]2CCCN2C(=O)[C@]23C[C@H]4C[C@H](C[C@H](C4)C2)C3)cn1",
        "CS(=O)(=O)[C@@H]1CCN(C(=O)c2cccnc2N2CCCC2)C1",
    ],
    [
        "O=C(N[C@H]1COc2cc(F)cc(F)c21)c1occc1COc1ccccc1",
        "COC(=O)c1csc(NC(=O)[C@@]2(C)CCN(C(C)=O)C2)c1",
        "Cc1nc(N2CCOCC2)ccc1NC(=O)N1CC(CO)C1",
        "COc1ccccc1[C@@H](CNC(=O)N1CC[C@](F)(CO)C1)[NH+]1CCCC1",
        "O=C([C@@H]1C[C@@]12CCCc1ccccc12)N1CCC[C@H](N2CC[NH2+]CC2=O)C1",
        "NC(=O)C1(O)CCN(C(=O)c2cccc3cc[nH]c23)CC1",
        "O=C(Nc1ccccc1)N1CC[C@@H](Nc2nc(-c3cccnc3)nc3c2CCC3)C1",
        "CC1CCN(C(=O)C2CCN(C(=O)Nc3cccc(-c4ccc5c(c4)CCO5)c3)CC2)CC1",
        "NC(=O)c1cc(NC(=O)N2CCOC[C@@H]2[C@@H]2CCCC[C@H]2O)ccc1F",
        "CCn1cc(Cl)cc1C(=O)N[C@@H](C(=O)[O-])C(C)C",
    ],
    [
        "O=C(NCC1CC1)[C@@H]1CCCN(C(=O)Cn2nc(-c3ccccc3)oc2=O)C1",
        "O=C(Nc1cnn(C[C@H]2CCCO2)c1)N[C@H](CN1CCCC1=O)c1ccccc1",
        "CCc1nc2ccc(Cl)cn2c1C(=O)Nc1ccc(F)c(NC(N)=O)c1",
        "Cn1cc(-c2ccc(F)c(C(=O)NC[C@@]3(C)CCCC[C@@H]3O)c2)cn1",
        "COc1c(C)cc(S(=O)(=O)N2CCN(C(=O)C3CC3)C2)cc1C",
        "Cc1nc(C(=O)N(C)C)nc(N2CC[C@H](Nc3ncc(C#N)cc3F)C2)c1C",
        "O=C(NCc1cnn2ccccc12)N[C@H]1CCOC2(CCCC2)C1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COc1cccc(C(=O)NCC(=O)N[C@@H]2CCC(=O)N[C@H]2[C@@H]2CCCO2)c1",
        "NC(=O)c1ccccc1CCC(=O)N1Cc2ccc(O)cc2C2(CC2)C1",
    ],
    [
        "CC(=O)N1C[C@@H](O)C[C@H]1C(=O)N[C@H](C)c1ccc(NC(=O)C2CC2)cc1",
        "Cc1ccccc1C(=O)NC1CCN(C(=O)[C@@H]2COc3ccccc32)CC1",
        "COC[C@H](Nc1ccc2nc(C3CC3)oc2c1)C1CCOCC1",
        "Cc1cc(S(N)(=O)=O)cc(C(=O)NC[C@@H]2CCCO2)c1C",
        "CC[C@@H](CO)NC(=O)Nc1ccc(S(=O)(=O)NC(C)(C)C)cn1",
        "Cc1ccc([C@@H](C)N(C)C(=O)NCc2cc(-c3ccccc3)on2)cc1",
        "COc1ccc(-c2nc(CCNC(=O)c3sc(C)nc3C)co2)cc1",
        "CCc1ccccc1N1C[C@H](C(=O)Nc2ccc(CC(=O)N(C)C)cc2)CC1=O",
        "CC(C)C(=O)Nc1cccc(NC(=O)c2cccc(-c3ncn[nH]3)c2)c1",
        "Cc1csc([C@H]2CCCN2C(=O)c2ccc3cc[nH]c3n2)n1",
    ],
    [
        "Cc1ccc(C(=O)N2CCC(NC(=O)Cc3ccc4c(c3)NC(=O)C4)CC2)cc1",
        "COC(=O)[C@@H]1CCc2nnc(C(=O)N3CCCC3)n2C1",
        "O=C(CNC(=O)[C@@H]1CCC[NH2+]1)Nc1ccc2c[nH]nc2c1",
        "FC(F)(F)c1cc(-c2cncc(-c3nnn[nH]3)c2)ccc1Cl",
        "COc1ccc(C(=O)N2CCC[C@@H]2C(=O)NC[C@H]2CCO[C@@H]2C(C)C)cc1",
        "CCOc1ccccc1C(=O)N1CCC[C@H]1C(=O)NCCc1ccc(O)cc1",
        "CC1(C)C[C@@H](NC(=O)CCc2nc(-c3cccs3)no2)c2ccc(F)cc2O1",
        "O=C(CC[C@@H]1CCCOC1)NS(=O)(=O)Cc1cccc(F)c1",
        "Cc1nnc(-c2ccc(NC(=O)N3CCCC3)cc2)o1",
        "CC(C)C(=O)Nc1cc(C(=O)N2CCC(O)(c3ccccc3)CC2)ccn1",
    ],
    [
        "Cc1nc2c(C(=O)NC3(c4ccccc4)CCC3)cccc2[nH]1",
        "CC(C)Cc1cc(N2CCC(Cc3nncn3C)CC2)ncn1",
        "CCNC(=O)N1CCC[C@@H]1c1nc(-c2ccccc2)c(C(C)C)o1",
        "Cn1cc(C(=O)Nc2cccc(-c3cn[nH]c3)c2)c(C(C)(C)C)n1",
        "CC(C)N(C)C(=O)C1CCN(C(=O)CCc2ccc(C(=O)[O-])cc2)CC1",
        "COc1ccc2c(N[C@@H]3CCOC4(CCCC4)C3)ncnc2c1F",
        "Cc1ccc(-c2nn(Cc3ccccc3)cc2C(=O)N2CCC[C@](C)(CO)C2)cc1",
        "C[NH+]1CCC(CNC(=O)CNC(=O)c2ccc3ccccc3c2)CC1",
        "CCn1cc(C(=O)NCC2([C@H](O)c3ccccc3)CC2)c2ccccc21",
        "CN(C)c1cccc(CCc2nc([C@H]3CC(=O)N(c4ccccc4)C3)no2)c1",
    ],
    [
        "C[C@@H](c1ccc(F)c(F)c1)N(C)C(=O)c1cn(Cc2cccc(F)c2)nn1",
        "O=C(NCc1ncccn1)c1ccc2c(c1)C[C@H](c1ccccc1)OC2=O",
        "Cc1cc(S(=O)(=O)NOCC(=O)[O-])ccc1OC(C)C",
        "CC1CCN(S(=O)(=O)N[C@H]2CCN(c3ccccc3)C2=O)CC1",
        "NC(=O)C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1Cl)c1ccccc1",
        "O=C(N[C@H]1CCCCC[C@@H]1CO)[C@@H](c1ccccc1)n1cnc2ccccc21",
        "C[C@H]1C[C@H](CO)CN(C(=O)C(=O)N[C@H]2CC(C)(C)c3ccccc32)C1",
        "Cc1cc(Oc2ccncc2)ccc1NC(=O)NC[C@]12CC[C@](CO)(CC1)OC2",
        "O=C(NCC1(c2ccccc2)CCOCC1)[C@@H](O)c1cc(Cl)cc(Cl)c1",
        "C[C@]1(C(=O)[O-])CCC[N@@H+]1CC(=O)Nc1ccc(F)cc1Cl",
    ],
    [
        "C[C@H](NC(=O)c1ccc(Nc2ncccn2)cc1)[C@H](O)c1ccccc1",
        "NC(=O)N1CCc2cc(NC(=O)c3cc(N4CCNC4=O)ccc3Cl)ccc21",
        "C[C@@H](NC(=O)N[C@H]1CCCN(Cc2ccccc2)C1=O)c1ccccn1",
        "O=C(N[C@@H](CN1CCCC1=O)c1ccccc1)[C@H]1CCCN(C(=O)Cc2ccc(F)cc2)C1",
        "CS(=O)(=O)c1ccc(NC(=O)NC2CCOCC2)cn1",
        "O=C(Nc1cccc2ccccc12)N[C@H]1CC[NH2+]C1",
        "O=C(Nc1ccc2[nH]nc(NC(=O)[C@H]3CCn4ccnc4C3)c2c1)[C@@H]1CCn2ccnc2C1",
        "Cc1ccc(S(=O)(=O)CCCN2C(=O)N[C@](C)(c3ccc(F)cc3F)C2=O)cc1",
        "C=C(C)CCNC(=O)[C@H]1CC(c2ccccc2)=[NH+]O1",
        "O=C(NCc1cccc(Cn2cnc3ccccc32)c1)N[C@H]1CC[N@@H+]2CCC[C@@H]2C1",
    ],
    [
        "Cc1ccc(CC(=O)N2CCC[C@H](c3nc(=O)[nH][nH]3)C2)cc1O",
        "CCc1cccc(C[NH2+][C@H]2CCC(=O)N[C@@H]2c2cnn(C)c2)c1",
        "O=C(COc1ccc2ccccc2c1)NCCc1cccc(O)c1",
        "O[C@H]1CC[C@@H](Nc2ccc(Br)cn2)CC1",
        "O=C(NCc1ccc(Cn2ccccc2=O)cc1)N1CC[N@@H+]2CCCC[C@H]2C1",
        "Cc1nn(C)c2nc(-c3cccs3)cc(C(=O)NCc3ccccc3Cn3cncn3)c12",
        "O=C(NCCC(c1ccccc1)c1ccccc1)c1n[nH]c(=O)[nH]c1=O",
        "Cc1cc(N2CCC(CO)CC2)nc(-c2cccnc2)n1",
        "COc1ccccc1OCCN(C)C(=O)c1cc(=O)[nH]c2ccccc12",
        "O=C(NC1(c2ccc(F)cc2)CCOCC1)c1ccn(-c2ccccc2F)n1",
    ],
    [
        "O=C(c1n[nH]c2ccc([N+](=O)[O-])cc12)N1CC[C@H](C(F)(F)F)[C@H](CO)C1",
        "COCC(=O)N1CCN(C(=O)c2cccc(NCc3nc(C)cs3)c2)CC1",
        "OC[C@@]1(F)CCN(c2nc(-c3ccccn3)nc3scc(-c4ccccc4)c23)C1",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "Cc1ccc(NC(=O)[C@H]2CCCN2C(=O)Cc2ccccc2)c(O)c1",
        "Cc1ccc(CCC(=O)N[C@@H]2CCCCNC2=O)c(C)c1",
        "C[C@@H]1Cc2ccccc2[C@H]1NC(=O)c1c[nH]c(=O)c2ccccc12",
        "COc1ccccc1[C@H]1CCCN1C(=O)c1cccc(C(N)=O)c1",
        "CC1(C)CCC(CNC(=O)Cc2nc3ncccn3n2)CC1",
        "CN(CCCNc1cccc2c1NC(=O)CO2)c1ccccc1",
    ],
    [
        "Cc1cc(COCC(=O)N(C)c2ccc(Br)cn2)no1",
        "O=C(c1cnc2ccccc2c1)N1CCC[C@@](O)(C(F)(F)F)CC1",
        "Cc1nocc1NC(=O)NC[C@](C)(O)c1ccc(F)cc1",
        "O=C1C[C@@]2(CCN(C(=O)CCc3nnc(C4CCCC4)o3)C2)CN1",
        "COC(=O)c1c(NC(=O)NCCCC(C)C)nc2n1CCOC2",
        "CCc1nnc([C@@H]2C[C@@H](O)CN2C(=O)Cc2coc3cc(C)c(C)cc23)o1",
        "COc1cccc(C[C@]2(C(=O)N[C@H]3CCCC[C@@H]3O)C[C@H]3CC[C@@H]2C3)c1",
        "Cc1cc(C)c(S(=O)(=O)N2CCC=C(c3cnn(C)c3)C2)s1",
        "C[C@@](O)(CCc1ccccc1)C(=O)N1CCCc2n[nH]cc21",
        "O=C(NCCc1c(F)cccc1F)[C@@H]1CCCN1C(=O)c1ccccc1",
    ],
    [
        "CCc1nc(CNc2cccc3c2C(=O)NC3)no1",
        "Cc1nc(C(F)(F)F)ccc1C(=O)N1CC[C@@H](O)C12CCCC2",
        "O=C(CCc1nc(-c2ccoc2)no1)N1CCC[C@@](O)(C(F)(F)F)CC1",
        "COc1cccc2c1OC[C@H](NC(=O)c1cc(=O)[nH]c3ccc(F)cc13)C2",
        "CCOC(=O)Cn1cnc2cc(Cl)ccc2c1=O",
        "C[C@H]([NH2+]Cc1ccc2cn[nH]c2c1)c1ccccc1F",
        "C[C@H](Cc1cccc(Cl)c1)C(=O)N1CCCN(C(N)=O)CC1",
        "O=C([C@@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "Cc1cc(F)ccc1C(=O)N1Cc2ccccc2C[C@@H]1C(N)=O",
        "C[C@@H](NC(=O)N1CCc2nccnc2C1)c1cccc(Cl)c1",
    ],
    [
        "O=C(COc1ccccc1F)N1CCCCC[C@@H]1c1ncon1",
        "CNC(=O)[C@H](NC(=O)[C@@H]1C[C@@H]1c1ccc(C(F)(F)F)cc1)c1ccccc1",
        "Cc1[nH]c(=O)[nH]c(=O)c1CCC(=O)N1CCOC[C@@H]1c1ccccc1",
        "O=C1[C@@H]([N@H+]2CCC[C@@H](Cn3ccnn3)C2)CCN1C1CC1",
        "NC(=O)C[C@@H](Nc1nc2c(cnn2-c2ccccc2)c(=O)[nH]1)c1ccccc1",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "CCc1nnc([C@@H]2C[C@@H](O)CN2C(=O)[C@H]2C[C@@H]2c2ccc(Cl)cc2Cl)o1",
        "CC1(C)OCC[C@H]1NC(=O)c1ccc(C(=O)[O-])cc1",
        "O=C(Nc1ccc(F)cc1)N[C@H]1CCN(C(=O)N2CCc3ccccc32)C1",
        "Cc1nn(C)cc1[C@@H](C)NS(=O)(=O)N1CCOCC1",
    ],
    [
        "C[C@H](NC(=O)N1CCC(c2ccc(O)cc2)CC1)c1cccc(OC(F)F)c1",
        "COc1ccc(Cl)cc1C(=O)N[C@H]1CCC(=O)NC1=O",
        "CC(C)S(=O)(=O)CC(=O)Nc1c2c(nn1C)CCC2",
        "Cc1ccc(-n2nc(C(=O)Nc3cccc([C@@]4(C)NC(=O)NC4=O)c3)c3c2CCC3)c(F)c1",
        "Cn1cc(CNc2cccc(CN3CCCC3=O)c2)c(-c2cc(F)ccc2F)n1",
        "Cn1nc2c(c1NC(=O)[C@H]1CCCN(C(=O)Cc3ccccc3)C1)CCC2",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "O=C1CCc2cc(NC(=O)c3ccc4c(c3)OCC(=O)N4)ccc2N1",
        "CC(C)c1ncncc1C(=O)Nc1cccc(-c2nncn2C)c1",
        "Cc1noc2nc(-c3ccc(F)cc3)cc(C(=O)N3CCO[C@@H](c4cccc(F)c4)C3)c12",
    ],
    [
        "Cc1ccc([C@@H](C)N(C)C(=O)NCc2cc(-c3ccccc3)on2)cc1",
        "COc1cc(CCO)ccc1NC(=O)[C@H]1CC1(C)C",
        "Cc1cc([C@@H]2CCCN(C(=O)CCn3cnc4sc(C)c(C)c4c3=O)C2)[nH]n1",
        "Cc1c(C2CC2)n[nH]c1NC(=O)c1cc(C#N)cc(N(C)C)c1",
        "Cc1ccc(C2(CNc3nc(=O)c4cn[nH]c4[nH]3)CCCC2)c(C)c1",
        "CC(C)(C(=O)NCc1ccc(OCc2cccc(F)c2)cc1)N1CCOCC1",
        "COc1cc(OC)cc(C2(F)CCN(C(=O)c3ccc(=O)n(-c4cnn(C)c4)c3)CC2)c1",
        "O=C([C@@H]1Cc2ccccc2CN1C(=O)Cc1ccc(C(F)F)cc1)N1CCCC1",
        "[NH3+][C@H](CC(=O)NCC(=O)NC1CC1)Cc1cc(F)c(F)cc1F",
        "CN(CC1CC1)C(=O)Cn1ccc(-c2ccccc2)nc1=O",
    ],
    [
        "O=C(CCCc1c[nH]c2ccccc12)NCC(=O)NCc1ccco1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)N[C@H](C)c1cn(C)nc1C",
        "O=c1c2ccc(Cl)cc2ncn1C[C@@]1(O)CCCOC1",
        "CCc1sc(C(=O)NCc2nc(C)c(C(=O)[O-])s2)cc1C",
        "C[C@@H](C[C@@H]1CCOC1)NC(=O)NCc1ccc(COCC(F)(F)F)cc1",
        "CC(C)COc1cccc(C(=O)N2CCCC[C@H]2[C@@H]2CNC(=O)C2)c1",
        "Cc1cccc(C(=O)N2CCOC[C@H]2CC(=O)[O-])c1Cl",
        "CC(C)(C)c1cnc(NC(=O)N[C@H]2C[C@@H](O)C2(C)C)s1",
        "Cc1noc([C@@H]2C[C@H](CNc3cnccn3)[C@@H](O)C2)n1",
        "NC(=O)[C@@H]1Cc2ccccc2CN1C(=O)c1cccc(-n2nnnc2N)c1",
    ],
    [
        "Cc1ccc(S(=O)(=O)NC(=O)c2ccco2)cc1C",
        "O=C(Nc1ccccc1N1CCCC1)N[C@H]1[C@H]2CCO[C@H]2C12CCC2",
        "COc1cccc(N2C[C@H](NC(=O)c3cccc(C(N)=O)c3)CC2=O)c1",
        "O=C(c1cccc(-c2c(F)cccc2F)c1)N1CCC[C@H](O)C1",
        "COc1cc(C)cc(CNC(=O)[C@@H]2Cc3ccccc3N2C(C)=O)c1",
        "Cc1nc(NC(=O)N2CC(=O)N[C@@H]3CCCC[C@H]32)ccc1-c1ccccc1",
        "Cc1ccncc1N1CCN(C(=O)c2cc(N3CCCC3=O)ccc2F)CC1",
        "O=C(NC[C@H]1Cc2ccccc2C[NH2+]1)N1CCC2(CC1)CC2(F)F",
        "C[NH+]1CCN(c2ccc(CNC(=O)N[C@H]3c4ccccc4C[C@@H]3O)cn2)CC1",
        "Cc1nc(C(=O)N2CC=CCC23CCOCC3)nc(N2CC[C@@H]([NH3+])C2)c1C",
    ],
    [
        "CO[C@H]1C[C@H](COc2cccnc2)[N@@H+](Cc2ccnn2C)C1",
        "C[C@H]1C[C@H](CO)CN(C(=O)C(=O)N[C@H]2CC(C)(C)c3ccccc32)C1",
        "COc1ccccc1CC(=O)N1CCC(CC(=O)[O-])CC1",
        "COC(=O)c1cc(C)nc(N2CC[C@H](c3ccccc3)C2)n1",
        "O[C@@]1(c2nc(Cc3ccccc3)no2)CCc2ccccc2C1",
        "C[C@@H]1Cc2cc(-c3ccc(CNC(=O)[C@H]4CC[C@@]5(CC4)NC(=O)NC5=O)cc3)ccc2O1",
        "COC(=O)Nc1ccc(NC(=O)[C@@H]2CCCN(c3cnccn3)C2)cc1",
        "Cc1ccc(CNc2nccc(C(C)(C)C)n2)c(N2CCCC2)n1",
        "COc1ccc(C)cc1[C@@H](C)NC(=O)[C@H](N)CC1CCCCC1",
        "CC(=O)N1CCN(c2ccccc2CNC(=O)c2c(-c3ccccc3Cl)noc2C)CC1",
    ],
    [
        "CC(C)(C)c1ccc(C2(NC(=O)CN3CCS(=O)(=O)CC3)CCCC2)cc1",
        "O=C1C[C@H](CNC(=O)c2cccc(Nc3nccc(C(F)(F)F)n3)c2)CN1",
        "O=C(NCc1ccn(C2CCCC2)n1)c1cncnc1",
        "N[C@H](Cc1n[nH]c2ccccc12)C(=O)NCc1cccc2c1CCCN2",
        "COc1cc(C)c([C@H](C)NC(=O)CN2CCOC3(CCC3)C2)cc1OC",
        "C[C@H](NC(=O)c1ccc(-n2cccn2)cc1)[C@@H](C)C(=O)[O-]",
        "O=C1NCc2nccc(N3CCC(c4ccccc4)CC3)c21",
        "Cc1ccnc2ccc(C(=O)N3Cc4ccccc4C[C@@H]3C(N)=O)cc12",
        "O=C(NCC(=O)N1CCc2ccccc2C1)c1ccc2c(=O)n3c(nc2c1)CCCCC3",
        "O=C(N[C@H]1CCCN(c2ccccc2F)C1)c1cnn2cccnc12",
    ],
    [
        "CN(CC1(C)COC1)C(=O)Nc1cccc2nc(C(F)F)sc12",
        "COc1ccc([C@@H]2[C@@H](C(=O)Nc3cccc(C(=O)NC(N)=O)c3)CCC(=O)N2C)cc1",
        "C[C@]1(CNC(=O)c2cccc(S(=O)(=O)Cc3ccccc3)c2)CCO[C@@H]1C1CC1",
        "CO[C@H]1C[C@@H](N(C)S(=O)(=O)c2ccc(OCC(=O)[O-])c(Cl)c2)C1",
        "O=C(C[C@@H]1CCCC(=O)N1)NCc1nnc(C2CC2)n1C1CC1",
        "[NH3+]Cc1nnc(N2CCCCC2)o1",
        "O=C(N[C@@H](CN1CCCC1=O)c1ccccc1)[C@H]1CCCN(C(=O)Cc2ccc(F)cc2)C1",
        "FC(F)(F)c1cc(-c2cncc(-c3nnn[nH]3)c2)ccc1Cl",
        "COc1ccc([C@H](NC(=O)NCc2nc(-c3ccco3)n[nH]2)c2ccc(C)cc2)cc1",
        "C[C@H]1CN(C(=O)NCc2ccc(C(N)=O)o2)CCN1CC(F)(F)F",
    ],
    [
        "COc1cc(F)cc(CNC(=O)N2CC[C@@]3(C2)C(=O)Nc2ccccc23)c1",
        "CNC(=O)[C@H](NC(=O)[C@@H]1C[C@@H]1c1ccc(C(F)(F)F)cc1)c1ccccc1",
        "CC[C@@H](NC(=O)c1ccc(C)cc1C)c1c(C)noc1C",
        "CC1(C)C[C@@H](NC(=O)Nc2nnc(C(C)(C)C)s2)CCO1",
        "Cc1ccc(CC(=O)N2CCC(NC(=O)c3ccccc3)CC2)cn1",
        "O=C(NCC1(c2cc(F)cc(C(F)(F)F)c2)CC1)Nc1cc(C2CCOCC2)on1",
        "Cc1cccc(-c2nnc([C@H](C)[N@H+](C)CC3CCOCC3)o2)c1",
        "CCc1nnc([C@@H]2C[C@@H](O)CN2C(=O)[C@H]2C[C@@H]2c2ccc(Cl)cc2Cl)o1",
        "FC(F)[C@H]1Oc2ccccc2C[C@H]1c1nc(-c2nnc[nH]2)no1",
        "COc1ccc([C@H](NC(=O)NCc2nc(-c3ccco3)n[nH]2)c2ccc(C)cc2)cc1",
    ],
    [
        "C[C@@H]1CCCN1C(=O)c1ccc(-c2nnn[nH]2)cc1",
        "Cc1ccc(-c2cccc(CNC(=O)Nc3cccc(N4C(=O)CNC4=O)c3)c2)cc1",
        "Cn1cc(-c2cncc(C(=O)N[C@H]3CC[C@H](O)CC3)c2)cn1",
        "CCCc1nc(C)c(CNC(=O)N[C@H]2C[C@@H]2C2CCCCC2)o1",
        "Fc1ccc(OCc2noc([C@H]3C[C@]34CC[NH2+]C4)n2)cc1",
        "Cc1nn(Cc2ncc(-c3ccccc3)o2)c(C)c1[C@@H]1COCCN1C",
        "O=C(NCC1([C@H](O)c2ccccc2)CC1)c1cc(Cl)cc2cccnc12",
        "O=C(N[C@@H](CO)Cc1c[nH]c2ccccc12)c1ccc(Cl)cc1",
        "C[C@H](CCNC(=O)N1CC(C(C)(C)O)C1)c1cccc(C(F)(F)F)c1",
        "O=C(c1ccc(-n2ccc(C(F)(F)F)n2)cc1)N1CCC([C@H](O)c2ccccc2)CC1",
    ],
    [
        "O=C1CCc2cc(NC(=O)c3ccc4c(c3)OCC(=O)N4)ccc2N1",
        "Cc1[nH]c2ccccc2c1NC(=O)CCC(C)(C)C",
        "CNC(=O)CNC(=O)c1cccc(N[C@H]2CCN(c3ccc(Cl)c(F)c3)C2=O)c1",
        "O=C(NCc1ccc(Oc2cccnc2)c(F)c1)NC[C@@H](O)c1ccc(F)cc1",
        "CC1CN(C(=O)c2ccnc(N3CC[C@H](C)C3)c2)C1",
        "CC[C@@H]1C[N@H+](C)CCCN1S(=O)(=O)c1nc(C)c(C)s1",
        "COc1ccc(C[NH2+]Cc2nnc3n2CCOCC3)c(Cl)c1",
        "NC(=O)C[C@@H](Nc1nc2c(cnn2-c2ccccc2)c(=O)[nH]1)c1ccccc1",
        "Cc1cc([C@@H]2CCCN(C(=O)CCn3cnc4sc(C)c(C)c4c3=O)C2)[nH]n1",
        "O=C(OCc1ccccc1)N1CCC[C@](O)(CN2CCOCC2)C1",
    ],
    [
        "O=C(c1cccnc1C(F)(F)F)N1CCS(=O)(=O)CC1",
        "O=C(Nc1ccc(F)cc1)N[C@H]1CCN(C(=O)N2CCc3ccccc32)C1",
        "CCc1ncnc(N(C)CC2CCN(C(=O)c3[nH]c4ccccc4c3OC)CC2)c1F",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "C[C@@]1(c2ccc(CNC(=O)c3cc4c(C(F)(F)F)cc(=O)[nH]c4o3)cc2)NC(=O)NC1=O",
        "Cc1nc(NC(=O)[C@@H]2CCC[C@H](C(=O)[O-])C2)n[nH]1",
        "CCc1cnccc1CNC(=O)[C@H]1C[C@@H](O)CN1C(=O)Cc1ccccc1F",
        "O=C([O-])[C@]1(O)CCCN(S(=O)(=O)c2ccccc2Cl)C1",
        "O=C(NCCc1c[nH]c2ccccc12)N1CCCC[C@@H]1c1ncc[nH]1",
        "Cc1nnc(-c2cccc(C(=O)N3CC(O)C3)c2)o1",
    ],
]


- Experiment:
    name: 5 known

    dataset: datasets/DDS10_MQN.pkl

    model:
        name: MLP
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]
