- unique_initial_sample:
    seeds: [
    [
        "O=C(N[C@@H](Cc1ccccc1)C(=O)N1CCCC1)[C@@H](O)[C@@H](O)c1nc2ccccc2s1",
        "NC(=O)c1ccc(C(=O)N2CCC[C@H](Cn3ccnn3)C2)nc1",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c(C)c1",
        "Cc1csc(N2CCN(C(=O)c3ccc(C(=O)NC4CC4)cc3)C[C@H]2C)n1",
        "CN1C(=O)CCc2cc(NC(=O)NC[C@@H](O)c3ccccc3)ccc21",
        "O=C(Nc1cccnc1)c1cccc(S(=O)(=O)N2CCCCC2)c1",
        "CS(=O)(=O)c1ccc(F)c(C(=O)Nc2ccc(-c3nc(-c4ccccc4)n[nH]3)cc2)c1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s1",
        "Cc1cccc([C@@H]2CCCN2C(=O)NCc2ccc(S(C)(=O)=O)cc2)n1",
        "Cc1ccc(C[C@@H](C)NC(=O)N2CCS(=O)(=O)CC2)s1",
    ],
    [
        "O=C([O-])c1cccc(CS(=O)(=O)N2CC[C@H](O)C2)c1",
        "O=C(CCc1cccc(Br)c1)N[C@H]1C[C@H](Cn2ccnc2)C[C@@H]1O",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "COc1ccc(OC)c([C@@H]2CCCN2C(=O)c2ccnc(OC)n2)c1",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
        "O=C(N[C@H]1C[C@@H](Cn2ccnc2)C[C@H]1O)c1ccc2ccccc2c1",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "COCCN1C(=O)N[C@H]2CN(C(=O)c3cccc(C#N)c3)CC[C@@H]21",
        "CCc1nocc1CN(C)C(=O)c1ccc2[nH]c(=O)n(C)c2c1",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2cccc",
    ],
    [
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)no",
        "O=C(Cc1ccc(-n2cnnn2)cc1)Nc1cnn(C[C@@H]2CCCO2)c1",
        "Cc1nc(NCc2cccc(N3CCCCC3=O)c2)cc(-c2ccccn2)n1",
        "O=C(c1n[nH]c2ccc([N+](=O)[O-])cc12)N1CC[C@H](C(F)(F)F)[C@",
        "COc1ccc(-c2noc(-c3ccc(NC(=O)c4cc(F)cc(F)c4)cc3O)n2)cn1",
        "N#Cc1ccc(C(=O)N2CCCC[C@H]2C(=O)[O-])cc1",
        "Cc1cc(C)n(CC(=O)NC[C@@H]2CC[C@@H](c3ncn[nH]3)O2)n1",
        "O=C(Nc1cccc(C(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1)[C@@H]1Cc2",
        "CC(C)CCOC1CCN(C(=O)c2ccc(C(=O)[O-])cn2)CC1",
        "CN(C)c1cccc(S(=O)(=O)N2CCC[C@@H](n3cc(C(=O)[O-])cn3)C2)c1",
    ],
    [
        "CCc1nn(C)cc1C(=O)N[C@@H]1c2ccccc2C[C@@H]1O",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
        "C[C@H](NC(=O)N[C@@H](CO)C[C@@H](O)C(C)(C)C)c1ccc(-c",
        "O=C1O[C@H](c2ccccc2)Cc2cc(C(=O)N3CC[C@H](c4ccccc4F)",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "C[C@H](Cc1nc(-c2ccccc2)no1)NC(=O)c1cccc(C#N)c1",
        "C#Cc1cc(F)c(NC(=O)C(=O)N2CC=C(c3c[nH]c4ncccc34)CC2)",
        "C[C@H]1CN(c2nnc(-c3ccccc3)n2C[C@@H]2CCCO2)CCS1",
        "COCC1(C)CCN(C(=O)Nc2ccc(-n3cccn3)nc2)CC1",
        "O=C(c1ncsc1Nc1ccccc1)N1C[C@@H](CO)[C@@H](CO)C1",
    ],
    [
        "Cc1cc(C)cc(-n2nc(C(=O)N3CCCC[C@@H]3c3cn[nH]c3)cc2C)c1",
        "CCc1cccc(C)c1NS(=O)(=O)c1cnc2n1CCC2",
        "O=C1Cc2cc(CCCC(=O)Nc3ccccc3N3CCCC3=O)ccc2N1",
        "CCn1c(=O)c(=O)[nH]c2cc(C(=O)NC[C@H]3CN(C)CCO3)ccc21",
        "CNc1cccc(-c2cn(Cc3cc(C(F)(F)F)nn3C)nn2)c1",
        "O=C(NC[C@H]1CCC[N@H+](Cc2ncon2)C1)c1cccc(-n2cncn2)c1",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
        "CS(=O)(=O)c1ccc(F)c(C(=O)Nc2ccc(-c3nc(-c4ccccc4)n[nH]",
        "CCc1onc(C)c1NS(=O)(=O)c1ccc(OCC(=O)[O-])c(Cl)c1",
        "CC(=O)Nc1ccc(NC(=O)c2cccc3ncn(C)c23)cc1",
    ],
    [
        "O=C(Nc1cccc(C(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1)[C@@H]1Cc2ccc",
        "O=C(Cc1cccnc1)NCc1cn(-c2ccccc2)nc1-c1ccc(F)cc1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)[C@@H]2CC(=O)N(c3ccc4c(c3)CCC",
        "CCc1cc(N2CC[C@@H](n3cc(C(=O)[O-])nn3)C2)c2ccccc2n1",
        "C[C@@]1(c2cnccn2)NC(=O)N(Cc2noc3c2CCCC3)C1=O",
        "CCc1onc(C)c1NC(=O)NCC1CCc2ccccc2CC1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](C",
        "CCOc1c(Cl)cc(CNc2ccc3nc(C)nn3n2)cc1OC",
        "O=C(C[C@@H]1CCc2ccccc2C1)N1CCC(c2nnc3n2CC[NH2+]C3)CC1",
        "Cc1ccsc1S(=O)(=O)NC(=O)C(F)(F)C1CCOCC1",
    ],
    [
        "O=C(COc1ccc(F)cc1)N[C@H]1CCC(=O)N[C@H]1c1ccccc1",
        "CCc1ccsc1C(=O)N1CCC(N2CCNC2=O)CC1",
        "CCS(=O)(=O)N1CCN(c2nnc(-c3cccn3C)n2C)CC1",
        "COCC1(C)CCN(C(=O)Nc2cnn(-c3ncccn3)c2)CC1",
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[n",
        "C[C@H]1Cc2c(C(=O)N3CCc4[nH]nc(C(F)(F)F)c4C3)n[n",
        "COc1ccc([C@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CC",
        "O=C([O-])C[C@H](NC(=O)c1ccc2cc[nH]c2c1)c1cccs1",
        "Cc1nc(CN(C)C(=O)C[C@H]2CCCC[C@H]2O)no1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(",
    ],
    [
        "CCn1nc(C)c(C[N@H+]2CCc3[nH]cnc3[C@@H]2c2ccc(F)cc2)n1",
        "C[C@@](O)(CNC(=O)[C@@H]1CCCN(C(=O)Cc2ccccc2)C1)c1ccc(F)cc1",
        "Cc1nc(N2CCOCC2)ccc1NC(=O)N1CC(CO)C1",
        "COc1ccccc1[C@@H](CNC(=O)N1CC[C@](F)(CO)C1)[NH+]1CCCC1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)Nc1cnn(CCOC)c1",
        "C[C@H]1Cc2c(C(=O)N3CCc4[nH]nc(C(F)(F)F)c4C3)n[nH]c2[C@@H](",
        "CC(C)N(C)C(=O)C1CCN(C(=O)CCc2ccc(C(=O)[O-])cc2)CC1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc",
        "Nc1nccc([C@H]2CCCN(C(=O)c3cccc(NS(=O)(=O)c4ccc(F)c(F)c4)c3",
        "CCn1cc(Cl)cc1C(=O)N[C@@H](C(=O)[O-])C(C)C",
    ],
    [
        "O=C(N[C@H]1CCO[C@@H]1c1ccc(Cl)c(F)c1)[C@@H]1C[C@@H]1c1c(F)cc",
        "O=C(Nc1cnn(C[C@H]2CCCO2)c1)N[C@H](CN1CCCC1=O)c1ccccc1",
        "O=C(Cc1ccc(O)cc1)N1CCC[C@@H]1C[C@H](O)c1ccccc1",
        "NC(=O)[C@H](Sc1nc2c(cnn2-c2cccc(Cl)c2)c(=O)[nH]1)c1ccc(F)cc1",
        "COc1c(C)cc(S(=O)(=O)N2CCN(C(=O)C3CC3)C2)cc1C",
        "Cc1nc(C(=O)N(C)C)nc(N2CC[C@H](Nc3ncc(C#N)cc3F)C2)c1C",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COc1cccc(C(=O)NCC(=O)N[C@@H]2CCC(=O)N[C@H]2[C@@H]2CCCO2)c1",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
    ],
    [
        "CC(=O)N1c2ccc(S(=O)(=O)N3CC4(CCC4)c4c(F)cccc43)cc2C[C@@H]1C",
        "Cn1ccnc1[C@H]1CCN(C(=O)Cc2n[nH]c(=O)c3ccccc23)C1",
        "COC[C@H](Nc1ccc2nc(C3CC3)oc2c1)C1CCOCC1",
        "Cc1cc(S(N)(=O)=O)cc(C(=O)NC[C@@H]2CCCO2)c1C",
        "CC[C@@H](CO)NC(=O)Nc1ccc(S(=O)(=O)NC(C)(C)C)cn1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s1",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "CCc1csc(CC(=O)N[C@@H](CN2CCOCC2)c2ccc(C)cc2)n1",
        "C[C@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(F)c1",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
    ],
    [
        "O=C(CN1CCc2ccccc2C1=O)NCc1ccccc1",
        "O=C(CCCc1c[nH]c2ccccc12)N[C@@H]1C[C@H](Cn2ccnc2)C[C@@H",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2ccccc2)",
        "C[C@@](O)(CNC(=O)[C@@H]1CCCN(C(=O)Cc2ccccc2)C1)c1ccc(F",
        "C[C@H]1C[C@@H]1C(=O)Nc1n[nH]c2nc(C(F)(F)F)ccc12",
        "Cn1ccnc1[C@]1(CNC(=O)c2ccc(-c3nnn[nH]3)cn2)NC(=O)NC1=O",
        "Cc1n[nH]c(C)c1CC(=O)N1CCO[C@H](c2ccccc2)C1",
        "O=C1O[C@H](c2ccccc2)Cc2cc(C(=O)N3CC[C@H](c4ccccc4F)C3)",
        "Cc1nnc(-c2ccc(NC(=O)N3CCCC3)cc2)o1",
        "CC(C)C(=O)Nc1cc(C(=O)N2CCC(O)(c3ccccc3)CC2)ccn1",
    ],
    [
        "O=C(O[C@H]1CCN(c2ccccc2Cl)C1=O)c1n[nH]c(=O)c2ccccc",
        "CC(C)Cc1cc(N2CCC(Cc3nncn3C)CC2)ncn1",
        "CCNC(=O)N1CCC[C@@H]1c1nc(-c2ccccc2)c(C(C)C)o1",
        "C[C@H](Nc1nc(-c2cccnc2)nc2c1CCC2)c1cccc(S(N)(=O)=O",
        "CC(C)N(C)C(=O)C1CCN(C(=O)CCc2ccc(C(=O)[O-])cc2)CC1",
        "CC(C)Cn1ncc(C(=O)NCC2(O)CCCCCC2)c1C(F)F",
        "Cc1nccn1-c1ncccc1CNC(=O)C1(c2ccccc2Cl)CCOCC1",
        "NC(=O)C1(c2ccccc2)CCN(C(=O)N[C@@H]2CCN(c3ccc(Cl)c(",
        "O=C(Nc1cccc(Cn2nc3ccccn3c2=O)c1)N1CCC[C@H](c2cc3cc",
        "Cc1ccc(S(=O)(=O)N[C@@H]2C=C[C@H](C(=O)[O-])C2)cc1C",
    ],
    [
        "C[C@@H](c1ccc(F)c(F)c1)N(C)C(=O)c1cn(Cc2cccc(F)c2)nn1",
        "O=C(NCc1ncccn1)c1ccc2c(c1)C[C@H](c1ccccc1)OC2=O",
        "Cc1cc(S(=O)(=O)NOCC(=O)[O-])ccc1OC(C)C",
        "C[C@@H](C(=O)NCc1ccc(C(=O)N2CCOCC2)cc1)N1CCc2ccccc21",
        "CCc1nc([C@@H](C)NC(=O)N[C@@H]2CCCc3cn[nH]c32)n[nH]1",
        "Cn1ccc2ccc(NC(=O)N3CC[C@H](C(C)(C)C)C3)cc2c1=O",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(",
        "Cc1ccc(NC(=O)N2CCN(C(=O)c3ccoc3C(F)(F)F)CC2)cc1",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
    ],
    [
        "C[C@H](NC(=O)c1ccc(Nc2ncccn2)cc1)[C@H](O)c1ccccc1",
        "COc1cccc(CNC(=O)N2CCC(C(=O)NCc3ccc(F)cc3)CC2)c1",
        "CCCNC(=O)C[NH+]1CCC(Nc2cc(C(F)(F)F)nc3ncnn23)CC1",
        "C[C@@H](NC(=O)C(Cc1ccccc1)Cc1ccccc1)c1ccc2c(c1)CC(=O)N2",
        "CS(=O)(=O)c1ccc(NC(=O)NC2CCOCC2)cn1",
        "O=C(Nc1cccc2ccccc12)N[C@H]1CC[NH2+]C1",
        "Cc1ccc(-c2cc(C(=O)NC[C@H]3CCC[C@]34NC(=O)NC4=O)c3c(C)noc3n2)",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)[C@@H]2CC(=O)N(c3ccc4c(c3)CCC",
        "C=C(C)CCNC(=O)[C@H]1CC(c2ccccc2)=[NH+]O1",
        "O=C(NCc1cccc(Cn2cnc3ccccc32)c1)N[C@H]1CC[N@@H+]2CCC[C@@H]2C1",
    ],
    [
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[nH]4)C",
        "CCc1cccc(C[NH2+][C@H]2CCC(=O)N[C@@H]2c2cnn(C)c2)c1",
        "C[C@H](COc1ccc(F)cc1F)NC(=O)N1CCC2(CCO2)CC1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)[C@@H]2CC(=O)N(c3ccc4",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
        "Cc1nn(C)c2nc(-c3cccs3)cc(C(=O)NCc3ccccc3Cn3cncn3)c12",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)NCc1nc2ccccc2n1CC",
        "Cc1cc(N2CCC(CO)CC2)nc(-c2cccnc2)n1",
        "COc1ccccc1OCCN(C)C(=O)c1cc(=O)[nH]c2ccccc12",
        "CNC(=O)[C@H]1CCCCN1C(=O)Cc1ccc2c(c1)CCO2",
    ],
    [
        "Cc1ccc(S(=O)(=O)Cc2nnc(C)n2C)cc1C",
        "Cc1nc([C@H](NC(=O)[C@H]2C[C@H]2c2ccc(C(F)(F)F)cc2)c2c",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "CCS(=O)(=O)N1CCN(C(=O)C2(c3ccccc3)CC2)CC1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4",
        "C[C@H]1C[N@@H+](C2CC2)C[C@@H]1NC(=O)N1Cc2ccc(Br)cc2C1",
        "Cc1nc2c(cc1C(=O)N[C@H](C)c1ccc3c(c1)CCC(=O)N3)c(C)nn2",
        "CC1(C)CCC(CNC(=O)Cc2nc3ncccn3n2)CC1",
        "CN(CCCNc1cccc2c1NC(=O)CO2)c1ccccc1",
    ],
    [
        "Cc1cc(COCC(=O)N(C)c2ccc(Br)cn2)no1",
        "NC(=O)c1cn(CC(=O)N2CCC[C@@H]2c2ccc(F)cc2)c2ccccc12",
        "C[C@@H](C(=O)NCc1ccc(C(=O)N2CCOCC2)cc1)N1CCc2ccccc21",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2ccccc2)c1",
        "Cn1cc(NC(=O)N2CCOC3(CCCC3)C2)c(-c2ccccc2)n1",
        "Cc1cc(C)c(S(=O)(=O)N2CCC=C(c3cnn(C)c3)C2)s1",
        "C[C@@](O)(CCc1ccccc1)C(=O)N1CCCc2n[nH]cc21",
        "O=C([O-])c1cc(F)ccc1NS(=O)(=O)c1c[nH]c2ncccc12",
    ],
    [
        "O=C1Cc2cc(CCCc3nc(-c4ccc(F)cc4)no3)ccc2N1",
        "Cc1ccn2c(NC(=O)c3cc(F)ccc3Cl)nnc2c1",
        "N#Cc1cc(Br)cc(S(=O)(=O)NC(=O)Cc2ccc(F)cn2)c1",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "CCOC(=O)Cn1cnc2cc(Cl)ccc2c1=O",
        "C[C@H]([NH2+]Cc1ccc2cn[nH]c2c1)c1ccccc1F",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)NCc1nc2ccccc2n1CC",
        "O=C(Nc1ccc2c(c1)COC2)c1coc(C2CCOCC2)n1",
        "COc1cc(C)c(C(=O)N2CCC[C@H]2c2nncn2C)cc1C(=O)[O-]",
        "C[C@@H](NC(=O)N1C[C@H](c2ccccc2)[C@H]2COCC[C@H]21)c1c",
    ],
    [
        "O=C(COc1ccccc1F)N1CCCCC[C@@H]1c1ncon1",
        "CCc1cccc2c1N(C(=O)c1cc(OC)no1)CC2",
        "Cc1ccc(CNC(=O)CN2CCCC[C@@H](O)C2=O)cc1F",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)c",
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[nH]",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "Cc1c(CCC(=O)N2CCN(C(=O)c3ccccc3)CC2)cnn1C",
        "CC1(C)OCC[C@H]1NC(=O)c1ccc(C(=O)[O-])cc1",
        "CC[C@H]1OCC[C@H]1NC(=O)Nc1nnn(C(C)C)n1",
        "C[C@H](NC(=O)N[C@@H](CO)C[C@@H](O)C(C)(C)C)c1ccc(",
    ],
    [
        "CCCC(=O)N1CCC[C@H]1C(=O)N[C@@H]1COc2ccccc2C1",
        "COc1ccc(Cl)cc1C(=O)N[C@H]1CCC(=O)NC1=O",
        "CC(C)S(=O)(=O)CC(=O)Nc1c2c(nn1C)CCC2",
        "O=C1CCCN1Cc1ccc(C(=O)N2CCC[C@@H](N3CCCS3(=O)=O)C2)cc1",
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F)(F)F)c",
        "O=C(c1n[nH]c2ccc([N+](=O)[O-])cc12)N1CC[C@H](C(F)(F)F)[C@@H",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](",
        "Cc1cc(C)c(NC(=O)[C@H]2C[C@@H]2c2ccccc2C)c(C)n1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)c",
        "CC1=[NH+]NC(=O)[C@@H]1CCNC(=O)c1nn(C)c2c1C[C@H](C)O[C@@H]2C",
    ],
    [
        "Cc1c[nH]cc1C(=O)N1CCC(c2ccc(S(N)(=O)=O)cc2)CC1",
        "COc1cc(CCO)ccc1NC(=O)[C@H]1CC1(C)C",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@@H]3C[C@H](O)c3ccc(F)cc3)n2)ccc",
        "C[C@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(F)c1",
        "Cn1ccnc1[C@@]1(CNC(=O)c2ccc(O[C@H]3CC3(F)F)cc2)NC(=O)NC1=O",
        "Cc1ccc(-c2cc(C(=O)NC[C@H]3CCC[C@]34NC(=O)NC4=O)c3c(C)noc3n2",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](",
        "CC(C)CC(=O)N1CCC(NC(=O)NC2CCOCC2)CC1",
        "[NH3+][C@H](CC(=O)NCC(=O)NC1CC1)Cc1cc(F)c(F)cc1F",
        "CN(CC1CC1)C(=O)Cn1ccc(-c2ccccc2)nc1=O",
    ],
    [
        "CNc1cccc(-c2cn(Cc3cc(C(F)(F)F)nn3C)nn2)c1",
        "O=C([O-])CCC1CCN(C(=O)CCc2cccs2)CC1",
        "O=c1c2ccc(Cl)cc2ncn1C[C@@]1(O)CCCOC1",
        "O=C1C[C@@H](C(=O)Nc2c(F)cccc2Oc2ccccc2)c2ccccc2N1",
        "O=C(NC[C@@H]1CC[N@H+]1C1CCOCC1)c1cc(F)c2ncccc2c1",
        "COc1ccccc1NC(=O)Cc1noc([C@@H]2Cc3ccccc3N2C(C)=O)n1",
        "O=C(O[C@H]1CCN(c2ccccc2Cl)C1=O)c1n[nH]c(=O)c2ccccc",
        "COc1ccc([C@@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CCOC",
        "Cc1noc([C@@H]2C[C@H](CNc3cnccn3)[C@@H](O)C2)n1",
        "Cc1cnc(C(=O)Nc2cccc(-c3nc(C)c(C)[nH]3)c2)cn1",
    ],
    [
        "Cc1ccc(S(=O)(=O)NC(=O)c2ccco2)cc1C",
        "O=C(Nc1ccccc1N1CCCC1)N[C@H]1[C@H]2CCO[C@H]2C12CCC2",
        "O=C1CN(C(=O)C2CCN(c3ccc4nncn4n3)CC2)CCN1",
        "OCCn1cc(Nc2ccnc(-c3ccccc3)n2)cn1",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
        "CN(C(=O)CS(=O)(=O)c1cc(F)ccc1F)C1CC1",
        "NC(=O)[C@H](Sc1nc2c(cnn2-c2cccc(Cl)c2)c(=O)[nH]1)c1ccc(",
        "O=C(NCc1ccc(-c2ccccc2)cc1)[C@@H]1C[C@@H](O)CN1C(=O)c1cc",
        "NC(=O)c1cn(CC(=O)N2CCC[C@@H]2c2ccc(F)cc2)c2ccccc12",
        "Cc1nc(C(=O)N2CC=CCC23CCOCC3)nc(N2CC[C@@H]([NH3+])C2)c1C",
    ],
    [
        "CO[C@H]1C[C@H](COc2cccnc2)[N@@H+](Cc2ccnn2C)C1",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "COc1ccccc1CC(=O)N1CCC(CC(=O)[O-])CC1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "O=C(CC[C@@H]1CC[NH2+]C1)Nc1cc(-c2cc(F)cc(F)c2)[nH]n1",
        "O=C(c1n[nH]c2ccc([N+](=O)[O-])cc12)N1CC[C@H](C(F)(F)",
        "COC(=O)Nc1ccc(NC(=O)[C@@H]2CCCN(c3cnccn3)C2)cc1",
        "Cc1ccc(CNc2nccc(C(C)(C)C)n2)c(N2CCCC2)n1",
        "NC(=O)NC[C@H]1CCCN(C(=O)NCc2ccccc2Oc2ccccc2)C1",
        "CN(c1ccccc1)S(=O)(=O)c1csc(C(=O)[O-])c1",
    ],
    [
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@H]3C[C@H](O)c3ccc(F)cc",
        "Cc1cc(C(=O)[O-])ccc1S(=O)(=O)N[C@H](C)c1c(C)noc1C",
        "O=C(NCc1ccn(C2CCCC2)n1)c1cncnc1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "COc1cc(C)c([C@H](C)NC(=O)CN2CCOC3(CCC3)C2)cc1OC",
        "C[C@H](NC(=O)c1ccc(-n2cccn2)cc1)[C@@H](C)C(=O)[O-]",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "CN(C(=O)N1CCC(c2nc(-c3ccccc3)n[nH]2)CC1)C1CCOCC1",
        "CC(C)n1cccc1C(=O)N[C@@H]1CC(=O)N(C(C)(C)C)C1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c",
    ],
    [
        "O=C(N[C@@H](Cc1ccccc1)C(=O)N1CCCC1)[C@@H](O)[C@@H](O)c1nc",
        "CN(C)C(=O)N1CCN(C(=O)c2ncnc3ccsc23)CC1",
        "C[C@H](O)C(=O)N1CCN(C(=O)c2cn(Cc3cccs3)nn2)CC1",
        "CO[C@H]1C[C@@H](N(C)S(=O)(=O)c2ccc(OCC(=O)[O-])c(Cl)c2)C1",
        "Cn1nc(-c2ccccc2)c2c(NC(=O)[C@H]3C[C@@H]3C(F)F)n[nH]c21",
        "C#Cc1cc(F)c(NC(=O)C(=O)N2CC=C(c3c[nH]c4ncccc34)CC2)c(F)c1",
        "COCCn1cc(NS(=O)(=O)c2cnc3c(c2)c(C)nn3C)cn1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccc",
        "CCc1nc([C@@H]2CCCN2C(=O)Nc2ccncc2)no1",
        "O=C([O-])c1coc(C[N@@H+]2CC=C(c3ccc(F)cc3)CC2)n1",
    ],
    [
        "COc1cc(F)cc(CNC(=O)N2CC[C@@]3(C2)C(=O)Nc2ccccc23)c1",
        "O=C1Cc2cc(CCCC(=O)Nc3ccccc3N3CCCC3=O)ccc2N1",
        "O=C(NCCN1CCS(=O)(=O)CC1)[C@H]1CC(=O)N(c2ccc3c(c2)Cc",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4cccc",
        "Cc1ccc(CC(=O)N2CCC(NC(=O)c3ccccc3)CC2)cn1",
        "O=C([O-])[C@@H]1CCN(S(=O)(=O)c2cccc(Cl)c2)CC1(F)F",
        "Cc1cccc(-c2nnc([C@H](C)[N@H+](C)CC3CCOCC3)o2)c1",
        "Cc1c(N2C(=O)[C@H]3C[C@H](O)CN3C2=O)nnn1-c1ccc(F)cc1",
        "Cc1cc(C)cc(C(=O)N2CCC[C@H](C(=O)NCc3cccc([C@@]4(C)N",
        "CS(=O)(=O)N1CC[C@H](CNc2ncnc3ccccc23)C1",
    ],
    [
        "C[C@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(",
        "Cc1nc2c(cc1C(=O)N[C@H](C)c1ccc3c(c1)CCC(=O)N3)c(",
        "Cn1cc(-c2cncc(C(=O)N[C@H]3CC[C@H](O)CC3)c2)cn1",
        "C[C@]1(c2cccc(-c3noc([C@H]4C[C@H]4c4ccc(F)cc4)n3",
        "Fc1ccc(OCc2noc([C@H]3C[C@]34CC[NH2+]C4)n2)cc1",
        "O=C(NCc1ccc2c(n1)CCCC2)C1CCN(C(=O)N2CCCC2)CC1",
        "O=C(NCC1([C@H](O)c2ccccc2)CC1)c1cc(Cl)cc2cccnc12",
        "CCN(CC)C(=O)CCCNC(=O)Cc1cc2ccccc2c(=O)[nH]1",
        "Cc1c(F)cccc1S(=O)(=O)NCCc1cnoc1",
        "Cn1cc(S(=O)(=O)N[C@@H]2CCc3c(Cl)cccc32)cn1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "Cc1[nH]c2ccccc2c1NC(=O)CCC(C)(C)C",
        "COc1ccc(CNC(=O)c2cnn(C(C)C)c2C)cc1",
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[nH]4)CC3)cc2",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)",
        "O=C(N[C@H]1CCO[C@@H]1c1ccc(Cl)c(F)c1)[C@@H]1C[C@@H]1c1c(F)",
        "COc1ccc(C[NH2+]Cc2nnc3n2CCOCC3)c(Cl)c1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "COc1nc(C)cc(N(C)CC2(O)CCCC2)n1",
        "C[C@@H](NC(=O)C(Cc1ccccc1)Cc1ccccc1)c1ccc2c(c1)CC(=O)N2",
    ],
    [
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "C[C@@H](NC(=O)C(Cc1ccccc1)Cc1ccccc1)c1ccc2c(c1)CC(=O)N2",
        "Cc1ccncc1NC(=O)CC(C)(C)c1ccccc1",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1F)c1ccc(NC(=O)c2ccncc2)cc1",
        "Cc1nc(NC(=O)[C@@H]2CCC[C@H](C(=O)[O-])C2)n[nH]1",
        "O=C(NCc1ccc(-c2ccccc2)cc1)[C@@H]1C[C@@H](O)CN1C(=O)c1ccc(F",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc",
        "CCOc1ccccc1CNC(=O)[C@@H]1C[C@@H](C)[C@@H](C(=O)[O-])O1",
        "Cc1nnc(-c2cccc(C(=O)N3CC(O)C3)c2)o1",
    ],
]



- Experiment:
    name: Enrich 4(CDDD)

    dataset: datasets/DDS10_CDDD.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy
        use_pairwise: True

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]
