- unique_initial_sample:
    seeds: [
    [
        "O=C(CCl)NCc1cnccn1",
        "Cn1cnc([N+](=O)[O-])c1SSc1c([N+](=O)[O-])ncn1C",
        "Cc1ccc(S(=O)(=O)N2Cc3ccc([N+](=O)[O-])cc3C2)cc1",
        "NC(=O)/N=N/c1c(F)c(F)c(F)c(F)c1F",
        "O=C(O[C@H]1C[NH+]2CCC1CC2)[C@@](O)(/C=C/c1ccccc1)c1ccccc1",
        "CC(=O)NC(CCC(=O)c1ccc(Cl)cc1)(C(=O)[O-])C(=O)[O-]",
        "CC[C@H](C)[C@H](N)C(=O)NCC(=O)OC",
        "Cc1cc(C)c(Cn2c(=O)[nH][nH]c2=O)cc1Cn1c(=O)[nH][nH]c1=O",
        "COc1ccc(/C=N/n2c(-c3ccccc3)n[nH]c2=O)c(OC)c1",
        "CC(=O)Nc1ccc(S(=O)(=O)F)cc1Cl",
    ],
    [
        "COc1c(O)cc(Br)c(C=O)c1N",
        "CCCCN1C(=O)NC(=O)[C@@]1(C)c1ccccc1",
        "COC(=O)C[C@H](c1ccc(O)cc1)[C@@H](CC(=O)OC)c1ccc(O)cc1",
        "CCCCCC1(C(C)C)C(=O)NC(=O)NC1=O",
        "c1c2c(cc3c1OCN(C1CC1)C3)OCN(C1CC1)C2",
        "CCCCc1cc(O)ccc1O",
        "COc1cc([O-])c2c(=O)cc(-c3ccc(O)cc3O)oc2c1CC=C(C)C",
        "O=C(CSc1ncc[nH]1)c1ccc(Br)cc1",
        "C/C=C/[C@H](C(=O)NC(N)=O)C(C)C",
        "C=CCNC(=S)NCc1cccc2ccccc12",
    ],
    [
        "O=C1C=C([C@@H](O)c2cccc3c2OCO3)C(=O)c2ccccc21",
        "COc1ccc2nc(C)c(COC(C)=O)cc2c1",
        "C[NH+]1C=c2c3c(ccc2=C2C=C[C@H]4C=C5OCOC5=CC4=C21)OCO3",
        "O=C([O-])c1cccc(O)c1O",
        "O=CNc1cc(Br)cc2c1[nH]c(=O)c1ccccc12",
        "CCO/C=C1\\SC(=S)N(c2ccc(C(=O)[O-])cc2)C1=O",
        "CC(C)(C)C[NH+]1CCCN(c2ccc(Cl)cc2)C1",
        "O=C1c2ccccc2C(=O)N1Cc1cc([N+](=O)[O-])ccc1Cl",
        "COc1cccc(P(c2cccc(OC)c2)c2cccc(OC)c2)c1",
        "CS[C@@H]1NNC2(C(=O)N1)c1ccccc1-c1ccccc12",
    ],
    [
        "CC(=O)C(C(C)=O)[C@@H]1c2ccccc2-n2nc(-c3ccccc3)c(O)c21",
        "O=C1C=C(c2ccccc2)O[C@H]1[C@@H]1Sc2ccccc2NC1=O",
        "O=C([O-])[C@H](c1ccccc1)c1cccc([C@@H](C(=O)[O-])c2ccccc2)n1",
        "COc1ccc(CC2=[N+](C)CCc3cc(OC)c(OC)cc32)cc1OC",
        "O=C1/C(=C/c2ccc(O)c(O)c2)Cc2ccccc21",
        "C1=Nc2c(ncnc2SCc2ccccc2)NN1",
        "CC1(C)O[C@@H]1C(=O)[O-]",
        "OC[C@H]1COc2cc(Cl)c(Cl)cc2O1",
        "c1nc2c3c4c(sc3ncn2n1)CCCC4",
        "COc1ccc(CCc2nccn2C)cc1OC",
    ],
    [
        "COc1ccc(Cl)c(S(N)(=O)=O)c1",
        "Cc1cc(SCc2ccc([N+](=O)[O-])cc2)nc(N)n1",
        "CCOC(=O)/C=C/c1ccc(N)cc1",
        "O=c1[nH]nc2c3cccc4cccc(c5ccc([O-])c1c52)c43",
        "CN(C=O)c1cc([N+](=O)[O-])ccc1OCc1ccccc1",
        "O=C(Nn1c(-c2ccccc2)nc2ccccc2c1=O)c1ccc([N+](=O)[O-])cc1",
        "CC(C)(CO)CNc1nc(N)nc(Cl)c1N",
        "CCOC(=O)N[C@H]1[C@@H]2OC(C)(C)O[C@@H]2O[C@H]1CC(=O)OC",
        "CCOC(=O)[C@H]1Cc2c(cc3c4c(cccc24)N(C(C)=O)C3)N(C)C1",
        "NC(=O)CNC(=O)c1ccccc1SC(=O)c1ccccc1C(F)(F)F",
    ],
    [
        "CS(=O)(=O)Oc1ccc([N+](=O)[O-])cc1",
        "CCCC1(C)[C@@H](C#N)C(=O)NC(=O)[C@@H]1C#N",
        "O=[N+]([O-])c1cccc([C@@H]2CC(c3ccccc3)=[NH+]N2c2ccccc2)c1",
        "O=S(=O)([O-])CC[C@@H](O)S(=O)(=O)[O-]",
        "Cc1c([N+](=O)[O-])ccc2cccnc12",
        "CCn1c(=O)c2c(ncn2CC)n(CC)c1=O",
        "CC(=O)Nc1ccc(C(=O)NN2C(=O)[C@@H](Cl)[C@H]2c2ccccc2)cc1",
        "N#Cc1c(-c2ccccc2)c(-c2ccccc2)nn(Cc2nnn[nH]2)c1=O",
        "O=c1oc2ccccc2cc1-n1nnc2cc([N+](=O)[O-])ccc21",
        "CCOc1ccc(/N=C/c2cccc([N+](=O)[O-])c2)c(O)c1",
    ],
    [
        "CCn1c(=O)c(C#N)c2n(CC)c3cc(C)c(C)cc3n2c1=O",
        "O=C1c2ccccc2C(=O)c2c(OC[C@H]3CO3)ccc(OC[C@@H]3CO3)c21",
        "O=Cc1cc(O)c(O)c(O)c1-c1c(C=O)cc(O)c(O)c1O",
        "CC(=O)c1ccccc1Br",
        "COc1c2c(c(OC)c3c1C(=O)c1ccccc1[C@@H]3O)CC=CC2",
        "C=C(Br)C[NH2+]CCCCCC",
        "CCOC(=O)c1[nH]c(CO)c(C(=O)OCC)c1C",
        "C[C@H]1CN(c2ccncc2[N+](=O)[O-])CCN1c1ccc(Cl)cc1",
        "CCC[C@H]1OCCN1CC",
        "CC1([N+](=O)[O-])COP(=O)(NCc2cccnc2)OC1",
    ],
    [
        "CCC(=O)Oc1cccc(OC(=O)CC)c1",
        "COc1cc(NC/C(C)=[NH+]/NC(N)=O)c2ncccc2c1",
        "Nc1nc(Cl)c2c(n1)CCC2",
        "Nc1ncnc2c1ncn2-c1ccccc1Cl",
        "COc1ccc(-c2nnc(-c3c(C)n(C)n(-c4ccccc4)c3=O)o2)cc1",
        "COc1cc2cccc(O)c2cc1OC",
        "Oc1ccc2c(c1)-c1c(c3ccccc3n1CCN1CCOCC1)CC2",
        "CCOC(=O)c1c(-c2ccccc2)n2c(=O)cc(C)c3c(O)c(O)cc1c32",
        "COc1cc2c3c(c4cc(OC)c(OC)cc4c2cc1OC)C[NH+]1CCC[C@H]1C3",
        "CCN(CC)C(=O)Nc1cccc(O)c1",
    ],
    [
        "COc1cc2ccc(C[C@H]3[NH2+]CCc4cc5c(cc43)OCO5)cc2cc1OC",
        "C(=[NH+]/Nc1nnc2c3cccnc3c3ccccc3c2n1)\\c1ccc2c(c1)OCO2",
        "C[NH+]1C(C)(C)CC(O)(C(=O)[O-])CC1(C)C",
        "Nc1ncc2[nH]c(=O)[nH]c2n1",
        "Cn1cc(C(=O)c2ccccc2)cc(C(=O)c2ccccc2)c1=O",
        "CCCCCCC[C@@H]1OCC[C@H](C)O1",
        "CCC(=[NH+]\\NC(=S)NC)/C(C)=[NH+]\\NC(=S)NC",
        "Nc1ccc(CCOc2ccc(N)cc2)cc1",
        "CCOc1ccc(N)c(SCC(=O)[O-])c1",
        "S=C1Nc2ccccc2CS1",
    ],
    [
        "O=C([O-])[C@@H]1CCc2nc(NCc3ccccc3)nc(NCc3ccccc3)c2C1",
        "COc1ccccc1/C=C(/C)C(C)=O",
        "O=C(N/[NH+]=C\\c1cccnc1)Nc1ccc(/N=N/c2ccccc2)cc1",
        "CCOC(=O)CCN1C(=O)CC[C@H]1C(=O)OCC",
        "NC(=O)N/[NH+]=C\\c1ccc(O)cn1",
        "C1CSC(N2CCOCC2)=N1",
        "CCO[N+]([O-])=C1C=C(C(C)(C)C)C(=O)C(C(C)(C)C)=C1",
        "COc1cccc([C@@H]2CCCC[C@@H]2O)c1",
        "CCCn1c(N)c(Cl)c(=O)n(CC)c1=O",
        "COC(=O)/C=C/CC(=O)NS(C)(=O)=O",
    ],
    [
        "C[C@H](CC(=O)c1ccc(F)cc1)[NH+]1CCCCC1",
        "CSCC[C@H]([NH3+])[P@](C)(=O)[O-]",
        "N#C/C(=C\\Nc1ccccn1)C(=O)C1CC1",
        "C(=[NH+]/Nc1nncn2cccc12)\\c1ccccc1",
        "C[C@@]1(CCCOc2cccc(N)c2)[NH+]=C(N)[NH+]=C(N)N1c1ccccc1",
        "CC1(C(Cl)(Cl)Cl)C=CC(=[NH+]OCC(=O)[O-])C=C1",
        "Cc1ccc2c(c1)nc1c([n+]2[N-]C(=O)CC[NH+](C)C)-c2cccc3cccc-1c23",
        "CCO/[NH+]=C(\\C)C(=O)NNS(=O)(=O)c1ccc(C)cc1",
        "Nc1cccc2c1C(=O)c1c(c(O)c3ccccc3c1O)C2=O",
        "Cc1ccc(/C=[NH+]/NC(N)=[NH2+])cc1",
    ],
    [
        "COc1cccc2c1CC[C@H]1C(C)(C)C(=O)CC[C@]21CC(=O)[O-]",
        "O=C(CCl)Nc1nncs1",
        "C[S@@](=O)CCC[NH+]=C=S",
        "CS(=O)(=O)Oc1ccccc1C(=O)[O-]",
        "F[B-](F)(F)[NH2+]c1ccc(CCc2ccc([NH2+][B-](F)(F)F)cc2)cc1",
        "C[C@H](NC(=O)NCCCl)c1ccsc1",
        "CC[C@H](Cc1ccco1)C(=O)[O-]",
        "CC(C)[C@H](C)C1=CC(=O)C=CC1=O",
        "COc1c(O)cc2oc(-c3ccc(O)c(O)c3)cc(=O)c2c1[O-]",
        "NC(=O)c1ccc[n+](Cc2ccccc2)c1",
    ],
    [
        "O=C1N[C@@](O)(c2ccccc2)c2ccccc21",
        "COc1cc(O)c(C(=O)[C@@H]2Cc3ccccc32)c(OC)c1",
        "Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2",
        "CCOC(=O)[C@@H](C)Sc1n[nH]c(=O)[nH]c1=O",
        "O=C([O-])c1nc2ccccc2c2ncccc12",
        "COC(=O)[C@H]1Cc2cncn2C(=O)N1",
        "CCOC(=O)N/[NH+]=C/c1ccc(OC)c(O)c1",
        "O=c1cccc2n1Cc1cc3ccccc3nc1-2",
        "O=C1[C@@H](Cl)[C@@H](c2ccc(O)cc2)N1n1cnc2ccccc2c1=O",
        "CCOC(=O)C(Cc1cc2c(n1C)CCCC2)(NC(C)=O)C(=O)OCC",
    ],
    [
        "CCCCC=C1C(=O)NC(=S)NC1=O",
        "O=C1NC(=O)C(=Cc2cn(C(=O)c3ccccc3)c3ccccc23)C(=O)N1",
        "CCCCOC(=O)[C@@H]([NH3+])Cc1ccc(OC)c(Cl)c1",
        "CC(=O)Oc1cccnc1",
        "O=C1c2c(O)ccc(Cl)c2C(=O)c2c(O)ccc(Cl)c21",
        "CCCC(=O)Nc1ccc(C)cc1",
        "CN1[NH+]=C2c3ccccc3CC[C@H]2[C@@H]1c1cccc(O)c1",
        "Cc1ccc(NC(=S)NC(=O)COc2ccccc2)cc1C",
        "CCOC(=O)NC(=O)CBr",
        "CCO/C=[NH+]\\C1=C(C#N)SC2=N/C(=C\\c3ccco3)C(=O)N21",
    ],
    [
        "Fc1cc(Cl)ccc1Cl",
        "CCOC(=O)/C(=C\\c1ccc(Cl)cc1)C(C)=O",
        "Cc1cccc(CNc2cccc(C)n2)n1",
        "N#CCN1CCCN(CC#N)C1",
        "CC(C)(C)[Si](C)(C)OC[C@]12CC[C@H]3C[NH2+][C@H]([C@H]31)[C@H](c1ccccc1)N2",
        "COc1cc(C(=O)[C@@H](O)c2ccc(O)c(OC)c2)ccc1O",
        "CCn1cc(C(=O)[O-])c(=O)c2ccc(C)[n+](C)c21",
        "CC(=O)C(=Cc1cccc([N+](=O)[O-])c1)C(C)=O",
        "O=C1OCC2=C1[C@H](c1ccccc1)c1cc3c(cc1N2CCO)OCCO3",
        "CCc1nn2c(=O)nc(SC)nc2s1",
    ],
    [
        "N/C(=N/c1ccc(O)cc1)S(=O)(=O)[O-]",
        "CC(=O)Nc1nc(-c2nnc(S)n2-c2ccc(Cl)cc2)cs1",
        "COc1ccc(C(=O)NCC[NH+](C)C)c2nc3ccccc3cc12",
        "CC(=O)Nc1ccc(S(=O)(=O)CCBr)cc1",
        "O=C1c2ccccc2C(=O)N1/N=N/N1C(=O)c2ccccc2C1=O",
        "CCOC(=O)c1c2c(c(C)n1Cc1ccccc1)-c1nc(N)ncc1CC2",
        "C=CC[C@@]1(O)c2ccccc2C(=O)c2c(NCCO)cccc21",
        "O=c1cc(-c2ccc(O)cc2)oc2ccccc12",
        "CCc1nnn(-c2ccccc2)c1C",
        "O=C(Cl)c1ccc(C(F)(F)F)cc1",
    ],
    [
        "CN[C@H](C#N)c1ccc(OC)cc1",
        "CC(=O)NCC[C@H]1CN(C(=O)/C=C\\C#C[Si](C)(C)C)c2ccccc21",
        "CC(=O)N[C@H](CS(=O)(=O)Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "CC(=S)NC(=O)NC(=O)c1ccc(C)cc1",
        "Nc1nccc2snnc12",
        "CCOC(=O)/C(C#N)=C(\\C)c1ccccc1",
        "O=C1C2=C(C(=O)c3ncccc31)[C@H]1C=C[C@H]2CC1",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)[C@@H]([C@]1(C)CO1)CO2",
        "NC(=O)N(CCc1ccccc1)N=O",
        "COc1cc(C)c(Cl)c(C)c1C(C)=O",
    ],
    [
        "N#C[C@@H](OC(=O)c1ccccc1)c1cccc([N+](=O)[O-])c1",
        "O=C1CS[C@H](c2cc([N+](=O)[O-])ccc2Cl)N1c1nncs1",
        "COc1c(O)cc2c(c1O)[C@H]1O[C@H](CO)[C@@H](O)[C@H](O)[C@@H]1OC2=O",
        "CCOc1ccc(C2[N@]3CCC[N@H+]2CC3)cc1OC",
        "CC(C)[C@@H](NC(=O)c1cnc2ccccc2n1)C(=O)N[C@@H](C)C(=O)[O-]",
        "CCN(O)CC",
        "O=c1c2ccccc2sc2c1c(N(CCO)CCO)cc1ccccc12",
        "COc1ccc2c(c1)C(=O)c1c-2n(CCC[NH2+]CCO)c(=O)c2ccccc12",
        "COc1cc(O)c2c(c1)C(=O)c1cc(C)cc(O)c1C2=O",
        "O=C(Nc1ccc(S(=O)(=O)[O-])cc1)c1ccco1",
    ],
    [
        "Cc1ccc(-n2cnc3c(Cl)ncnc32)cc1[N+](=O)[O-]",
        "COc1ccc([C@]2(C(OC)OC)NC(=O)N(C)C2=O)cc1",
        "CC(C)C(=O)C(C)(C)C(=O)N1CCCC1",
        "CCOC(=O)c1ccc(=O)n(Cc2ccccc2)c1",
        "CC(C)(O)[C@@H]1CCCC[C@H]1Cl",
        "Cn1c(=O)nc2n(-c3ccc(Cl)cc3)c3ccc(Cl)cc3nc-2c1=O",
        "c1ccc2c(C[NH+]3CCCCC3)cccc2c1",
        "O=C(CCCc1ccncc1)c1ccccc1",
        "CC1=C(CC(=O)[O-])c2cc(F)ccc2/C1=C\\c1ccc(S(C)(=O)=O)cc1",
        "O=C1CS[C@H](c2ccccc2O)N1c1nnc(-c2ccccc2)o1",
    ],
    [
        "CC(=O)Nc1ccc(CO[C@H](O)C[NH+]2CCCCC2)cc1[N+](=O)[O-]",
        "NC(=O)COc1c(Cl)cc(Cl)cc1Cl",
        "CN1C(=O)/C(=C2\\Nc3ccccc3C2=O)c2ccccc21",
        "ClCC(CCl)(CCl)CCl",
        "Cc1ccc([S@@](=O)c2ccc([N+](=O)[O-])cc2[N+](=O)[O-])cc1[N+](=O)[O-]",
        "C[C@H](O)CNC(=O)Nc1c(C(F)(F)F)cc(-c2ccccc2)[nH]c1=O",
        "COc1ccc(CC[NH2+]C2=CC(=O)CC2)cc1OC",
        "Cc1ccc(C(=[NH2+])c2ccccc2Cc2ccccc2)cc1C",
        "O=C1NC(=O)/C(=C/c2ccc(Cl)cc2Cl)N1",
        "C/N=N\\C(C)C",
    ],
    [
        "N#Cc1sc(=S)n(-c2ccccc2)c1N",
        "CO[C@@H]1C[C@H](NC(C)=O)C=C(C2N(c3ccccc3)CCN2c2ccccc2)O1",
        "Nc1ncnc2c1ncn2Cc1cccnc1",
        "C=Cc1c(C)cc(C)cc1C",
        "CN(C)c1nc(Oc2nc(N(C)C)nc(N(C)C)n2)nc(N(C)C)n1",
        "Cc1nc(NC(=O)Nc2ccccc2)sc1C(=O)NN",
        "O=C(N[C@H]1CCC[C@@H]1O)c1ccccc1",
        "O=c1c(O)c(-c2ccc(O)c(O)c2)oc2cc(O)cc([O-])c12",
        "C[NH+](C)Cc1cc(Cl)ccc1O",
        "O=NN(CC(=O)[O-])Cc1ccccc1",
    ],
    [
        "O=C1c2ccccc2CCc2ccccc21",
        "CN(C)c1ccc(/[N+]([O-])=C/c2cc(=O)c(OS(C)(=O)=O)co2)cc1",
        "COc1cccc2oc([N+](=O)[O-])cc12",
        "Cn1cnc(C(N)=S)c1N",
        "C[NH2+]C1(c2ccc(F)cc2)CCCCC1",
        "Nc1ccc(CCc2nc(N)nc(O)c2-c2ccc(Cl)cc2)cc1",
        "O=C(c1ccc([N+](=O)[O-])cc1)c1ccc(O)cc1O",
        "Cc1cccc(Cl)c1OCC(N)=O",
        "COc1cc2c(c(O)c1OC)C(=O)[C@@H]1CCC(=O)N1[C@@H]2c1ccccc1",
        "CCO[C@H]([C@@H](OCC)[n+]1ccccc1)[n+]1ccccc1",
    ],
    [
        "CCOC(=O)[C@H]1C[C@@H]1C(=O)OCC",
        "CCCCCC#C[C@@](O)(C(=O)OC1CC[NH+](C)CC1)c1ccccc1",
        "CN(C)C(=O)OCCOc1ccc(Cl)cc1",
        "O=C(OCCO)N1CC[NH+](CCO)CC1",
        "S=C(N/[NH+]=C(\\c1ccccc1)c1ccccn1)SCc1ccccc1",
        "O=C([O-])C(=Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "O=C/C=C/[C@@H]1C=Cc2c3c(c(O)c(O)c2C(=O)[C@@H]1O)OCC=C3",
        "C[C@H](COC(=O)c1ccccc1)[NH2+]C1CCCCC1",
        "NC(=O)N[C@H]1C[C@@H]1c1ccc(Cl)c(Cl)c1",
        "N#CC(C#N)C1c2ccccc2-c2ccccc21",
    ],
    [
        "CCOC(=O)[C@H]1C[C@H](O)C[NH2+]1",
        "Cc1ncc(C(=O)[O-])s1",
        "CN1C(=O)N(C)C(=O)C(Nc2ccc([N+](=O)[O-])cc2)(SCCO)C1=O",
        "O=NN(CCCl)C(=O)Nc1ccc(CC(=O)[O-])cc1",
        "CN1COc2ccc(Br)cc2C1",
        "CCOC(=O)c1c2c(c(C)n1Cc1ccccc1)-c1nc(N)ncc1CC2",
        "COc1cc2ccccc2[n+](C)c1-c1ccccc1F",
        "COc1ccc(OC)c([C@H]2CCCc3c2cnc2nc(N)nc(N)c32)c1",
        "[O-][n+]1cc[n+]([O-])c2c3ccccc3ccc21",
        "O=C(NN1CCCCC1)c1ccccc1",
    ],
    [
        "CCOC(=O)/C=C1\\Nc2ccccc2C(c2ccccc2)=[NH+][C@H]1OC(C)=O",
        "C/C(CCO)=[NH+]\\NC(N)=S",
        "CC(=O)[C@@H]1Cc2c(O)c3c(c(O)c2[C@@H](O)C1)C(=O)c1ccccc1C3=O",
        "C[S+](C)CCO",
        "O=C1N=C(N2CCN(c3ccccc3)CC2)N[C@@H]2CCCC[C@H]12",
        "CC1(C)CC[C@H](c2cc(O)c3c(c2O)C(=O)C=CC3=O)O1",
        "CCCCc1ccc([I+]c2cccc([N+](=O)[O-])c2)cc1",
        "CCN(CC)CC#CCN(CC)CC",
        "C[C@H](Oc1ccc2cc(C(=O)c3ccccc3)c(=O)oc2c1)C(=O)[O-]",
        "COC(=O)c1ccccc1NC(=S)NC(=O)COc1ccccc1",
    ],
    [
        "O=C(C[NH+](Cc1ccccc1)Cc1ccccc1)NC(=O)c1ccccc1",
        "CCCCN(CC)CC#N",
        "N#Cc1cccc(F)c1",
        "Cc1cc2ccccc2nc1Cl",
        "CN(C=O)COCN(C)C=O",
        "Cc1ccc(N2CC[NH+](C[C@H](O)COc3ccccc3)CC2)cc1",
        "O=c1oc(-c2ccc(O)c(O)c2)cc2cc(O)cc([O-])c12",
        "COc1ccc(/C=C2/SC(=O)NC2=O)cc1OC",
        "O=S(=O)(NCc1ccco1)c1ccc(F)cc1",
        "O=C1/C(=C/c2ccc(O)c(O)c2)Cc2ccccc21",
    ],
    [
        "O=c1[nH]c(=O)ss1",
        "COC(=O)C[C@H](c1ccc(O)cc1)[C@@H](CC(=O)OC)c1ccc(O)cc1",
        "Cc1ccccc1C(=O)[C@@H]1CCCCC1=O",
        "COc1cc(CCl)cc(OC)c1OC",
        "Cc1ccccc1C(=O)Sc1c(C)cccc1C(=O)NCCC(N)=O",
        "COc1ccccc1[C@@H](C)c1ccc2ccccc2c1C(=O)[O-]",
        "O=C(NCCc1cnc[nH]1)C(F)(F)F",
        "C[N+](C)(C)CCOC(=O)c1ccc(CBr)cc1",
        "COc1ccc2c(c1)OC/C(=C\\c1ccc([N+](=O)[O-])o1)C2=O",
        "COc1c(O)ccc2c1C[NH+]1CCc3cc4c(cc3[C@@H]1C2)OCO4",
    ],
    [
        "O=C(NC(=O)c1cc(-c2ccccc2)n[nH]1)c1ccccc1",
        "C(=[NH+]/[NH+]=C/c1cccs1)\\c1cccs1",
        "Cn1c2c(c3ccccc31)CCN(CCCC[NH+]1CCCCC1)C2=O",
        "C[C@H]1CC(=O)[C@@H]2CC(CO)=CCC[C@@H]2[C@]1(C)CC/C(=C/CO)CO",
        "CC(=O)N[C@H](C)C(=O)N(C)/N=N/c1ccc(C#N)cc1",
        "Nc1ccc2ccccc2c1/N=N/c1ccc([C@H](O)[C@H]([NH3+])CO)cc1",
        "CC(=O)c1c(COc2ccc(Cl)cc2)[n+]([O-])c2ccccc2[n+]1[O-]",
        "CCOC(=O)CNC(=O)Oc1cccc2cccnc12",
        "O=C1N[C@@H](Cc2ccccc2)C(=O)O1",
        "CCOC(=O)C(=O)NCc1ccc(Cl)cc1Cl",
    ],
    [
        "CC(=O)c1cc(=O)[nH]c(=O)[nH]1",
        "COC(=O)C[C@@]1(C)[C@H](O)[C@H]2OC(C)(C)O[C@H]2[C@@H]1O",
        "c1ccc(/C(=[NH+]\\[NH+]=c2\\[nH]c3ccccc3s2)c2ccncc2)cc1",
        "Cc1cccc(Cl)c1",
        "NC(=S)Nn1c(=O)c2ccccc2c2ccccc2c1=O",
        "Cc1ccccc1C(=O)NNC(=O)c1cccc2ccccc12",
        "O=c1[nH]nc(OCc2nnc(SCc3ccccc3)o2)c2ccccc12",
        "Cc1ccc(NC(=S)C#N)c(C)c1",
        "COC(=O)[C@H](CC=O)c1ccc(OC)cc1",
        "CC(C)(CC(=O)[O-])NC(=O)CN",
    ],
    [
        "CC1(C)CC(=O)c2c(oc(=O)c3ccccc23)C1",
        "CCOC(=O)c1cnc2c(OC)cccc2c1O",
        "OCc1c(CO)c(Br)c2ccccc2c1Br",
        "COc1ccc(C)cc1S(=O)(=O)c1ccc(C)cc1[N+](=O)[O-]",
        "COc1cc([C@H]2c3cc(O)c(OC)cc3C[C@H]3C(=O)OC[C@@H]23)ccc1O",
        "C1CCC[NH+](CCN2CCOCC2)CCC1",
        "Cc1cc(O)c(C(C)C)cc1C[NH+]1CCCCC1",
        "Cc1ccc2c(c1)nc1c([n+]2[N-]C(=O)CC[NH+](C)C)-c2cccc3cccc-1c23",
        "C=C(C)[C@H]1C[C@@H]2O[C@]2(C)[C@@H](O)C1",
        "O=[N+]([O-])c1cc/c(=[NH+]\\[NH+]=C/c2ccc(O)c(S(=O)(=O)[O-])c2)[nH]c1",
    ],
]


- Experiment:
    name: Enrich 2(MLP CDDD padre EI)

    dataset: datasets/DTP_CDDD.pkl

    model:
        name: MLP
        iterations: 5
        acquisition_size: 20
        acquisition_method: EI
        use_pairwise: True

    metrics: 
        names: [top-k, top-k-acquired]
        k: [1320]