- unique_initial_sample:
    seeds: [
    [
        "O=C(CCl)NCc1cnccn1",
        "Cn1cnc([N+](=O)[O-])c1SSc1c([N+](=O)[O-])ncn1C",
        "Cc1ccc(S(=O)(=O)N2Cc3ccc([N+](=O)[O-])cc3C2)cc1",
        "Nc1ccc(CC[C@H]2CCC/C=C/[C@@H]3C[C@H](O)C[C@H]3[C@H",
        "O=C1N[NH+]=C([C@H](O)c2ccccc2)[C@]1(O)c1ccccc1",
        "CC(=O)NC(CCC(=O)c1ccc(Cl)cc1)(C(=O)[O-])C(=O)[O-]",
        "CC[C@H](C)[C@H](N)C(=O)NCC(=O)OC",
        "C/C(=[NH+]\\S(=O)(=O)c1cccc([N+](=O)[O-])c1)OCC(C)C",
        "COc1ccc(/C=N/n2c(-c3ccccc3)n[nH]c2=O)c(OC)c1",
        "CC(=O)Nc1ccc(S(=O)(=O)F)cc1Cl",
    ],
    [
        "C/C(=[NH+]/NC(=O)Nc1ccc(/N=N/c2ccccc2)cc1)c1ccc",
        "CCCCN1C(=O)NC(=O)[C@@]1(C)c1ccccc1",
        "c1ccc(C2=[NH+]N[C@@H]3c4ccccc4-c4ccccc4N3C2)cc1",
        "OCCCNC(=S)Nc1ccc(-c2nc3ccccc3[nH]2)cc1",
        "c1c2c(cc3c1OCN(C1CC1)C3)OCN(C1CC1)C2",
        "CCCCc1cc(O)ccc1O",
        "COc1ccc2cc(N3CCCC3)ccc2c1",
        "O=C(CSc1ncc[nH]1)c1ccc(Br)cc1",
        "C/C=C/[C@H](C(=O)NC(N)=O)C(C)C",
        "C=CCNC(=S)NCc1cccc2ccccc12",
    ],
    [
        "CCN(CC)/[NH+]=C/C[C@H](C)Nc1ccnc2cc(Cl)ccc12",
        "COc1ccc2nc(C)c(COC(C)=O)cc2c1",
        "C[NH+]1C=c2c3c(ccc2=C2C=C[C@H]4C=C5OCOC5=CC4=C21)OCO3",
        "O=C([O-])c1cccc(O)c1O",
        "Cc1c(O)c2c(c(O)c1Cc1cccc(C[NH3+])c1)C(=O)c1ccccc1C2=O",
        "CCO/C=C1\\SC(=S)N(c2ccc(C(=O)[O-])cc2)C1=O",
        "CC(C)(C)C[NH+]1CCCN(c2ccc(Cl)cc2)C1",
        "C[C@@H]1C[C@H]([C@@H](O)CC2CC(=O)N(Cc3ccccc3)C(=O)C2)",
        "COc1cccc(P(c2cccc(OC)c2)c2cccc(OC)c2)c1",
        "Cc1cccn2ncnc12",
    ],
    [
        "CC(=O)NC1=C([NH3+])C(=O)c2ccccc2C1=O",
        "O=C1C=C(c2ccccc2)O[C@H]1[C@@H]1Sc2ccccc2NC1=O",
        "O=C([O-])[C@H](c1ccccc1)c1cccc([C@@H](C(=O)[O-])c2ccccc2)n1",
        "COc1ccc(CC2=[N+](C)CCc3cc(OC)c(OC)cc32)cc1OC",
        "OCCCCC[NH2+]C1CCCCC1",
        "COc1c(-c2ccc(O)c(O)c2)oc2c(O)c(O)cc([O-])c2c1=O",
        "CC1(C)O[C@@H]1C(=O)[O-]",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)NCc1ccc(C(F)(F)F)cc1",
        "c1nc2c3c4c(sc3ncn2n1)CCCC4",
        "COc1ccc(CCc2nccn2C)cc1OC",
    ],
    [
        "COc1ccc(Cl)c(S(N)(=O)=O)c1",
        "Cc1cc(SCc2ccc([N+](=O)[O-])cc2)nc(N)n1",
        "CCOC(=O)/C=C/c1ccc(N)cc1",
        "O=c1[nH]nc2c3cccc4cccc(c5ccc([O-])c1c52)c43",
        "CN(C=O)c1cc([N+](=O)[O-])ccc1OCc1ccccc1",
        "O=C(N/[NH+]=C\\C(F)(F)F)c1ccncc1",
        "CC(C)(CO)CNc1nc(N)nc(Cl)c1N",
        "CC(=O)Nc1ccc2c(c1)/C(=N/c1ccc(C(=O)[O-])cc1)c1ccccc1-",
        "Nc1ccc(CC[C@H]2CCC/C=C/[C@@H]3C[C@H](O)C[C@H]3[C@H](O",
        "O=C(Nc1ccccc1CO)c1ccccc1",
    ],
    [
        "CS(=O)(=O)Oc1ccc([N+](=O)[O-])cc1",
        "CCCC1(C)[C@@H](C#N)C(=O)NC(=O)[C@@H]1C#N",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)cc([O-])c12",
        "O=S(=O)([O-])CC[C@@H](O)S(=O)(=O)[O-]",
        "Cc1c([N+](=O)[O-])ccc2cccnc12",
        "CCn1c(=O)c2c(ncn2CC)n(CC)c1=O",
        "CCn1c(Cl)c(/C=[NH+]\\Nc2ccc([N+](=O)[O-])cc2)c2ccccc21",
        "N#CS/C=C\\C(N)=O",
        "O=c1oc2ccccc2cc1-n1nnc2cc([N+](=O)[O-])ccc21",
        "O=C(CCc1ccc(O)c(O)c1)c1ccc(O)c(O)c1O",
    ],
    [
        "CCn1c(=O)c(C#N)c2n(CC)c3cc(C)c(C)cc3n2c1=O",
        "O=C1c2ccccc2C(=O)c2c(OC[C@H]3CO3)ccc(OC[C@@H]3CO3)c21",
        "NC(=O)c1cccc(NC=O)c1",
        "COc1c(-c2ccc(O)c(O)c2)oc2c(O)c(O)cc([O-])c2c1=O",
        "CC(=O)Nc1nnc(SC[NH+](C)C)s1",
        "C=C(Br)C[NH2+]CCCCCC",
        "O=C1/C(=C/c2ccc(O)c(O)c2)CC/C1=C\\c1ccc(O)c(O)c1",
        "C[C@H]1CN(c2ccncc2[N+](=O)[O-])CCN1c1ccc(Cl)cc1",
        "CCC[C@H]1OCCN1CC",
        "CC1([N+](=O)[O-])COP(=O)(NCc2cccnc2)OC1",
    ],
    [
        "OCCCc1cc(O)c2c(c1)[C@@H](CO)[C@@H](c1ccc(O)c(O)c1)O2",
        "COc1cc(NC/C(C)=[NH+]/NC(N)=O)c2ncccc2c1",
        "Nc1nc(Cl)c2c(n1)CCC2",
        "CSC(=[NH2+])c1cccc(CCCCc2ccc(NC(C)=O)cc2)c1",
        "COc1ccc(-c2nnc(-c3c(C)n(C)n(-c4ccccc4)c3=O)o2)cc1",
        "COc1cc2cccc(O)c2cc1OC",
        "O=C(NNC(=O)c1cccc2ccccc12)c1ccc(F)cc1",
        "CCOC(=O)[C@@H](C/[N+]([O-])=C/c1ccccc1)NC(C)=O",
        "COc1cc2c3c(c4cc(OC)c(OC)cc4c2cc1OC)C[NH+]1CCC[C@H]1C3",
        "CCN(CC)C(=O)Nc1cccc(O)c1",
    ],
    [
        "CNC(=O)NN",
        "C=C(C)[C@@H]1C[C@H](O)Cc2cc(F)ccc2N1",
        "C[NH+]1C(C)(C)CC(O)(C(=O)[O-])CC1(C)C",
        "Oc1cc(O)c2c(c1)O[C@H](c1cc(O)c(O)c(O)c1)[",
        "Cn1cc(C(=O)c2ccccc2)cc(C(=O)c2ccccc2)c1=O",
        "CCCCCCC[C@@H]1OCC[C@H](C)O1",
        "CCC(=[NH+]\\NC(=S)NC)/C(C)=[NH+]\\NC(=S)NC",
        "Nc1ccc(CCOc2ccc(N)cc2)cc1",
        "Cc1cc(Cc2cc(C)c(O)c(CO)c2)cc(CO)c1O",
        "S=C1Nc2ccccc2CS1",
    ],
    [
        "CC[C@](O)(c1ccc(O)cc1)[C@](O)(CC)c1ccc(O)cc1",
        "COc1ccccc1/C=C(/C)C(C)=O",
        "O=C1C=C(C2=CC(=O)c3cccc(O)c3C2=O)C(=O)c2c(O)cccc",
        "CCOC(=O)CCN1C(=O)CC[C@H]1C(=O)OCC",
        "NC(=O)N/[NH+]=C\\c1ccc(O)cn1",
        "C1CSC(N2CCOCC2)=N1",
        "CCO[N+]([O-])=C1C=C(C(C)(C)C)C(=O)C(C(C)(C)C)=C1",
        "COc1cccc([C@@H]2CCCC[C@@H]2O)c1",
        "CCCn1c(N)c(Cl)c(=O)n(CC)c1=O",
        "COC(=O)/C=C/CC(=O)NS(C)(=O)=O",
    ],
    [
        "C[C@H](CC(=O)c1ccc(F)cc1)[NH+]1CCCCC1",
        "CSCC[C@H]([NH3+])[P@](C)(=O)[O-]",
        "N#C/C(=C\\Nc1ccccn1)C(=O)C1CC1",
        "C(=[NH+]/Nc1nncn2cccc12)\\c1ccccc1",
        "O=C1C=C2C[C@@]3(O)COc4c(ccc(O)c4O)C3=C2C=C1O",
        "CC1(C(Cl)(Cl)Cl)C=CC(=[NH+]OCC(=O)[O-])C=C1",
        "C[NH+]1CCN(c2ccc3[nH]c(-c4c5cccccc-5[nH]c4=O)nc3c2)CC1",
        "CCO/[NH+]=C(\\C)C(=O)NNS(=O)(=O)c1ccc(C)cc1",
        "CCOC(=O)[C@@H](CC(C)C)NC(=O)c1cc2ccccc2[n+](C)c1",
        "O=C1/C(=C/c2ccc(O)c(O)c2)CC/C1=C\\c1ccc(O)c(O)c1",
    ],
    [
        "COc1cccc2c1CC[C@H]1C(C)(C)C(=O)CC[C@]21CC(=O)[O-]",
        "O=C(CCl)Nc1nncs1",
        "C[S@@](=O)CCC[NH+]=C=S",
        "CS(=O)(=O)Oc1ccccc1C(=O)[O-]",
        "COc1ccc(C[C@H](CO)NC(=O)c2ccccc2)cc1",
        "COc1cc(C[C@@H]2COC(=O)[C@]2(O)Cc2ccc(O)c(OC)c2)ccc1O",
        "COc1cc(C[C@@H]2COC(=O)[C@]2(O)Cc2ccc(O)c(OC)c2)ccc1O",
        "CC(C)[C@H](C)C1=CC(=O)C=CC1=O",
        "S=C(N/[NH+]=C/c1c[nH]c2ccccc12)NC12CC3CC(CC(C3)C1)C2",
        "NC(=O)c1ccc[n+](Cc2ccccc2)c1",
    ],
    [
        "O=C1N[C@@](O)(c2ccccc2)c2ccccc21",
        "COc1cc(O)c(C(=O)[C@@H]2Cc3ccccc32)c(OC)c1",
        "O=C(c1ccccc1)N1[NH+]=CCC[C@@H]1O",
        "CCOC(=O)[C@@H](C)Sc1n[nH]c(=O)[nH]c1=O",
        "O=C([O-])c1nc2ccccc2c2ncccc12",
        "COC(=O)[C@H]1Cc2cncn2C(=O)N1",
        "CCOC(=O)N/[NH+]=C/c1ccc(OC)c(O)c1",
        "O=c1cccc2n1Cc1cc3ccccc3nc1-2",
        "O=C(N/[NH+]=C\\c1ccccn1)Nc1ccc(/N=N/c2ccccc2)c",
        "O=C1c2cc(O)c(O)cc2O[C@H](c2ccc(O)c(O)c2)[C@H]",
    ],
    [
        "CCCCC=C1C(=O)NC(=S)NC1=O",
        "O=C(CCl)Nc1cccc2c1C(=O)c1c(c(O)c3ccccc3c1O)C2=O",
        "CCCCOC(=O)[C@@H]([NH3+])Cc1ccc(OC)c(Cl)c1",
        "CCc1ccc2c(O)c3c(cc2c1C(=O)OC)C(=O)c1cccc(O)c1C3=O",
        "Cc1nnc2c(S)nccn12",
        "CCCC(=O)Nc1ccc(C)cc1",
        "CN1[NH+]=C2c3ccccc3CC[C@H]2[C@@H]1c1cccc(O)c1",
        "Cc1ccc(NC(=S)NC(=O)COc2ccccc2)cc1C",
        "CCOC(=O)NC(=O)CBr",
        "CCO/C=[NH+]\\C1=C(C#N)SC2=N/C(=C\\c3ccco3)C(=O)N21",
    ],
    [
        "Fc1cc(Cl)ccc1Cl",
        "CCOC(=O)/C(=C\\c1ccc(Cl)cc1)C(C)=O",
        "Cc1cccc(CNc2cccc(C)n2)n1",
        "N#CCN1CCCN(CC#N)C1",
        "CC(C)(C)[Si](C)(C)OC[C@]12CC[C@H]3C[NH2+][C@H]([C@H]31)[C@H](c1ccccc1)N2",
        "C[C@H](Cc1ccccc1)NC(N)=O",
        "O=C1c2cc(O)cc(O)c2C(=O)c2c1cc1c(c2O)[C@@H]2C=CO[C@@H]2O1",
        "Oc1ccc([C@H]2Oc3c(ccc(O)c3O)[C@@H](O)[C@H]2O)cc1O",
        "CC(=O)Oc1cccc2c1[nH]c(=O)c1c(OC(C)=O)c3c(cc12)OCO3",
        "CCc1nn2c(=O)nc(SC)nc2s1",
    ],
    [
        "Cc1cccc(-n2c(C)nc3ccc(NC(=O)NCCCl)cc3c2=O)c",
        "CC(=O)Nc1nc(-c2nnc(S)n2-c2ccc(Cl)cc2)cs1",
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C",
        "CC(=O)Nc1ccc(S(=O)(=O)CCBr)cc1",
        "O=C1c2ccccc2C(=O)N1/N=N/N1C(=O)c2ccccc2C1=O",
        "O=C([O-])c1ccc(Oc2ccccc2)cc1",
        "CCOC(=O)C1CCc2ccccc2CC1",
        "O=c1cc(-c2ccc(O)cc2)oc2ccccc12",
        "CCc1nnn(-c2ccccc2)c1C",
        "O=C(Cl)c1ccc(C(F)(F)F)cc1",
    ],
    [
        "CN[C@H](C#N)c1ccc(OC)cc1",
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
        "COc1cc(C[C@@]2(O)C(=O)OC[C@H]2Cc2ccc(OC)c(OC)c2)ccc1O",
        "CC(=S)NC(=O)NC(=O)c1ccc(C)cc1",
        "Nc1nccc2snnc12",
        "CCOC(=O)/C(C#N)=C(\\C)c1ccccc1",
        "O=C1C2=C(C(=O)c3ncccc31)[C@H]1C=C[C@H]2CC1",
        "COC(Cn1cnc2c(N)ncnc21)OC",
        "NC(=O)N(CCc1ccccc1)N=O",
        "COc1cc(C)c(Cl)c(C)c1C(C)=O",
    ],
    [
        "N#C[C@@H](OC(=O)c1ccccc1)c1cccc([N+](=O)[O-])c1",
        "O=Cc1cc(O)c(O)c(O)c1-c1c(C=O)cc(O)c(O)c1O",
        "O=C([O-])c1cccc(N2C(=O)CSC2=S)c1",
        "COc1cccc(NC(=O)CSc2nnc(-c3ccc(NC(C)=O)cc3)o2)c1",
        "CC(C)[C@@H](NC(=O)c1cnc2ccccc2n1)C(=O)N[C@@H](C)C(=O)[O-]",
        "CCN(O)CC",
        "O=c1c2ccccc2sc2c1c(N(CCO)CCO)cc1ccccc12",
        "Cc1nc2[nH]nc(N)c2c(C)c1Br",
        "COc1cc(O)c2c(c1)C(=O)c1cc(C)cc(O)c1C2=O",
        "O=C(Nc1ccc(S(=O)(=O)[O-])cc1)c1ccco1",
    ],
    [
        "Cc1ccc(-n2cnc3c(Cl)ncnc32)cc1[N+](=O)[O-]",
        "COc1ccc([C@]2(C(OC)OC)NC(=O)N(C)C2=O)cc1",
        "CC(C)C(=O)C(C)(C)C(=O)N1CCCC1",
        "CC[C@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(O)c(O)cc",
        "CC(C)(O)[C@@H]1CCCC[C@H]1Cl",
        "Cn1c(=O)nc2n(-c3ccc(Cl)cc3)c3ccc(Cl)cc3nc-2c1=O",
        "c1ccc2c(C[NH+]3CCCCC3)cccc2c1",
        "O=C(CCCc1ccncc1)c1ccccc1",
        "O=C1c2ccc(O)cc2O[C@@H](c2cc(O)c(O)c(O)c2)[C@@H]1",
        "O=C(/C=C/c1ccccc1)C1=C([O-])C(=O)O[C@H]1c1ccccc1",
    ],
    [
        "O=C1OCC(c2ccc(O)cc2)=C1c1cc(O)c(O)c(O)c1",
        "NC(=O)COc1c(Cl)cc(Cl)cc1Cl",
        "CN1C(=O)/C(=C2\\Nc3ccccc3C2=O)c2ccccc21",
        "ClCC(CCl)(CCl)CCl",
        "Cc1ccc([S@@](=O)c2ccc([N+](=O)[O-])cc2[N+](=O)[O-])cc1[N+](=O)[O-]",
        "C[C@H]1Oc2c3c(cc(O)c2C(=O)[C@@H]1C)OC(C)(C)CC3",
        "COc1ccc(CC[NH2+]C2=CC(=O)CC2)cc1OC",
        "C[NH+](CCCl)C[C@@H]1CSCO1",
        "O=C1NC(=O)/C(=C/c2ccc(Cl)cc2Cl)N1",
        "Cc1cc(Cc2cc(C)c(O)c(CO)c2)cc(CO)c1O",
    ],
    [
        "O=C1N[NH+]=C([C@H](O)c2ccccc2)[C@]1(O)c1ccccc",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)ccc12",
        "Nc1ncnc2c1ncn2Cc1cccnc1",
        "C=Cc1c(C)cc(C)cc1C",
        "CN(C)c1nc(Oc2nc(N(C)C)nc(N(C)C)n2)nc(N(C)C)n1",
        "Cc1nc(NC(=O)Nc2ccccc2)sc1C(=O)NN",
        "O=C(N[C@H]1CCC[C@@H]1O)c1ccccc1",
        "CN(N=O)C(=O)NCCOC(=O)N(C)N=O",
        "C[NH+](C)Cc1cc(Cl)ccc1O",
        "O=NN(CC(=O)[O-])Cc1ccccc1",
    ],
    [
        "O=C1c2ccccc2CCc2ccccc21",
        "CN(C)c1ccc(/[N+]([O-])=C/c2cc(=O)c(OS(C)(=O)=O)co2)cc1",
        "COc1cccc2oc([N+](=O)[O-])cc12",
        "COc1cc(C[C@@H]2COC(=O)[C@@H]2Cc2ccc(O)c(OC)c2)ccc1O",
        "C[NH2+]C1(c2ccc(F)cc2)CCCCC1",
        "O=C([O-])c1cc(I)cc(I)c1",
        "O=C(c1ccc([N+](=O)[O-])cc1)c1ccc(O)cc1O",
        "COc1cc([C@H]2c3cc(O)c(OC)cc3C[C@]3(O)[C@@H]2CO[C@@H]3O",
        "COc1ccc(S(=O)(=O)N(CC(=O)[O-])c2ccccc2)cc1",
        "CCO[C@H]([C@@H](OCC)[n+]1ccccc1)[n+]1ccccc1",
    ],
    [
        "CCOC(=O)[C@H]1C[C@@H]1C(=O)OCC",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)ccc12",
        "CN(C)C(=O)OCCOc1ccc(Cl)cc1",
        "O=C(OCCO)N1CC[NH+](CCO)CC1",
        "S=C(N/[NH+]=C(\\c1ccccc1)c1ccccn1)SCc1ccccc1",
        "O=C([O-])C(=Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "C/C(=[NH+]/C(C)(C)C)N1CCCCC1",
        "C[C@H](COC(=O)c1ccccc1)[NH2+]C1CCCCC1",
        "NC(=O)N[C@H]1C[C@@H]1c1ccc(Cl)c(Cl)c1",
        "NC(=O)C[C@@H]1OC(=O)Cc2cc3c(c(O)c21)C(=O)c1c(",
    ],
    [
        "Fc1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3ccccc3)C2)",
        "Cc1ncc(C(=O)[O-])s1",
        "CN1C(=O)N(C)C(=O)C(Nc2ccc([N+](=O)[O-])cc2)(SCCO)C1=O",
        "CCc1ccc2c(O)c3c(cc2c1C(=O)OC)C(=O)c1cccc(O)c1C3=O",
        "CN1COc2ccc(Br)cc2C1",
        "C[N+](C)(C)CC(=O)N/[NH+]=C/c1ccc([N+](=O)[O-])o1",
        "COc1cc2ccccc2[n+](C)c1-c1ccccc1F",
        "Nc1nc(N)c2c(ccc3ccc(Cl)cc32)n1",
        "[O-][n+]1cc[n+]([O-])c2c3ccccc3ccc21",
        "O=C(NN1CCCCC1)c1ccccc1",
    ],
    [
        "CCOC(=O)/C=C1\\Nc2ccccc2C(c2ccccc2)=[NH+][C@H]1OC(C)=O",
        "C/C(CCO)=[NH+]\\NC(N)=S",
        "Cc1c(C)c(C)c(C[NH+]2CCCC2)c(C)c1C",
        "C[S+](C)CCO",
        "O=C1N=C(N2CCN(c3ccccc3)CC2)N[C@@H]2CCCC[C@H]12",
        "COc1cc(C[C@@]2(O)C(=O)OC[C@H]2Cc2ccc(OC)c(OC)c2)ccc1O",
        "CCCCc1ccc([I+]c2cccc([N+](=O)[O-])c2)cc1",
        "CCN(CC)CC#CCN(CC)CC",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)C[C@@H]([C@@](C)(O)CO",
        "COC(=O)c1ccccc1NC(=S)NC(=O)COc1ccccc1",
    ],
    [
        "COc1ccc(OC)c(/C=C/C=O)c1",
        "CCCCN(CC)CC#N",
        "N#Cc1cccc(F)c1",
        "Oc1ccc2c(c1)OC[C@@]1(O)Cc3cc(O)c(O)cc3[C@H]2",
        "CN(C=O)COCN(C)C=O",
        "Cc1ccc(N2CC[NH+](C[C@H](O)COc3ccccc3)CC2)cc1",
        "O=c1oc(-c2ccc(O)c(O)c2)cc2cc(O)cc([O-])c12",
        "COc1ccc(/C=C2/SC(=O)NC2=O)cc1OC",
        "O=S(=O)(NCc1ccco1)c1ccc(F)cc1",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)C[C@@H]([C@@",
    ],
    [
        "O=c1[nH]c(=O)ss1",
        "Cc1[nH]c2ccc(C(=O)NN)cc2c1CC(=O)NN",
        "Cc1ccccc1C(=O)[C@@H]1CCCCC1=O",
        "COc1cc(CCl)cc(OC)c1OC",
        "CC[NH+]1C[C@@H](O)C2=C/C(=[NH+]/NC(N)=O)C(=O)C=C21",
        "COc1ccccc1[C@@H](C)c1ccc2ccccc2c1C(=O)[O-]",
        "O=C(NCCc1cnc[nH]1)C(F)(F)F",
        "C[N+](C)(C)CCOC(=O)c1ccc(CBr)cc1",
        "O=C1CC[C@H](O)Cc2ccc(O)c(c2)-c2cc(ccc2O)C[C@@H]1O",
        "C/C(=[NH+]/NC(=O)Nc1ccc(/N=N/c2ccccc2)cc1)c1ccccn1",
    ],
    [
        "O=C(NC(=O)c1cc(-c2ccccc2)n[nH]1)c1ccccc1",
        "C(=[NH+]/[NH+]=C/c1cccs1)\\c1cccs1",
        "Cn1c2c(c3ccccc31)CCN(CCCC[NH+]1CCCCC1)C2=O",
        "CC(=O)CC(=O)OC[C@H]1COCO1",
        "CC(=O)N[C@H](C)C(=O)N(C)/N=N/c1ccc(C#N)cc1",
        "CCCCCCOc1ccccc1CO",
        "c1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3ccccc3)C2)",
        "COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)cc2)ccc1O",
        "O=C1N[C@@H](Cc2ccccc2)C(=O)O1",
        "CCOC(=O)C(=O)NCc1ccc(Cl)cc1Cl",
    ],
    [
        "CC(=O)c1cc(=O)[nH]c(=O)[nH]1",
        "COC(=O)C[C@@]1(C)[C@H](O)[C@H]2OC(C)(C)O[C@H]2[C@@H]1O",
        "c1ccc(/C(=[NH+]\\[NH+]=c2\\[nH]c3ccccc3s2)c2ccncc2)cc1",
        "Cc1cccc(Cl)c1",
        "NC(=S)Nn1c(=O)c2ccccc2c2ccccc2c1=O",
        "O=C1NCc2nnn(Cc3ccccc3)c2N1",
        "CC[C@]1(O)CCc2c(cc3c(c2O)C(=O)c2c(O)cccc2C3=O)[C@H]1C(",
        "Cc1ccc(NC(=S)C#N)c(C)c1",
        "COC(=O)[C@H](CC=O)c1ccc(OC)cc1",
        "CSC(=[NH2+])c1cccc(CCCCc2ccc(NC(C)=O)cc2)c1",
    ],
    [
        "CC1(C)CC(=O)c2c(oc(=O)c3ccccc23)C1",
        "CCOC(=O)c1cnc2c(OC)cccc2c1O",
        "OCc1c(CO)c(Br)c2ccccc2c1Br",
        "O=C(c1ccc(C(=O)c2ccc(O)cc2O)cc1)c1ccc(O)cc1O",
        "COC(=O)CCc1cc(O)c2c(c1)[C@@H](C(=O)OC)[C@@H](c1ccc(O)c(O)c1)O2",
        "C1CCC[NH+](CCN2CCOCC2)CCC1",
        "Cc1cc(O)c(C(C)C)cc1C[NH+]1CCCCC1",
        "O=C([O-])/C(=C\\c1cccc(Br)c1)c1ccccc1",
        "C=C(C)[C@H]1C[C@@H]2O[C@]2(C)[C@@H](O)C1",
        "O=[N+]([O-])c1cc/c(=[NH+]\\[NH+]=C/c2ccc(O)c(S(=O)(=O)[O-])c2)[nH]c1",
    ],
]


- Experiment:
    name: Enrich 2(rdkit2D)

    dataset: datasets/DTP_RDKIT2D.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [1320]
