- unique_initial_sample:
    seeds: [
    [
        "O=C(Nc1ccc(Nc2ncccn2)cc1)c1cn[nH]c1-c1ccco1",
        "Cc1c[nH]c(=O)n1-c1cccc(C(=O)N2CCc3c(ncn3-c3ccc(F)cc3)C2)c1",
        "COc1ccnc(NC[C@]23C[C@](NC(=O)[C@@H]4C[C@@H]4C)(C2)C(C)(C)O3)n1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "C[C@@H]1Cc2ccccc2N1C1CCN(C(=O)[C@H]2CCCN(C(=O)c3ccc4[nH]ncc4c3)C2)CC1",
        "O=C(Nc1cccnc1)c1cccc(S(=O)(=O)N2CCCCC2)c1",
        "Cc1cc([N+](=O)[O-])c(C)c(S(=O)(=O)N(C)[C@@H]2C[N@H+]3CC[C@@H]2CC3)c1",
        "Cc1ccc(C(=O)N2CC[C@H](c3cc(O)[nH]n3)C2)cc1",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)CC1)C2=O",
    ],
    [
        "C#Cc1cc(F)c(NC(=O)C(=O)N2CC=C(c3c[nH]c4ncccc34)CC2)c(F)c1",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "Cc1ccccc1CNc1cc(C(N)=O)ccc1Cl",
        "COc1ccc(OC)c([C@@H]2CCCN2C(=O)c2ccnc(OC)n2)c1",
        "C=CCN(CC(=O)[O-])S(=O)(=O)c1ccc(OC)c(Cl)c1",
        "Cn1nc(-c2ccccc2)c2c(NC(=O)[C@H]3C[C@@H]3C(F)F)n[nH]c21",
        "COC[C@@H]1CN(C(=O)c2ncoc2C2CC2)CCO1",
        "CC(C)[C@@H](O)CC(=O)N1CC=C(c2c[nH]c3ncccc23)CC1",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "CC[NH+]1CCN([C@@H]2CCN(C(=O)Cc3cncs3)C2)CC1",
    ],
    [
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
        "O=C(Cc1ccc(-n2cnnn2)cc1)Nc1cnn(C[C@@H]2CCCO2)c1",
        "Cc1nc(NCc2cccc(N3CCCCC3=O)c2)cc(-c2ccccn2)n1",
        "O=C(c1ccnn1C1CCCC1)N1CCN(c2cncc3ccccc23)CC1",
        "O=C(NCC1([C@@H](O)c2ccccc2)CC1)c1cnn2c(=O)cc[nH]c12",
        "O=C(NCCN1CCS(=O)(=O)CC1)[C@H]1CC(=O)N(c2ccc3c(c2)Cc2ccccc2-3)C1",
        "O=C([C@@H]1C[C@@H]2CC[C@H]1O2)N1CCC(c2nc(=O)[nH][nH]2)CC1",
        "O=C(Cc1ccc(O)cc1)N1CCC[C@@H]1C[C@H](O)c1ccccc1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "CN(C)c1cccc(S(=O)(=O)N2CCC[C@@H](n3cc(C(=O)[O-])cn3)C2)c1",
    ],
    [
        "CCc1nn(C)cc1C(=O)N[C@@H]1c2ccccc2C[C@@H]1O",
        "Cc1ccc(NC(=O)CCn2c(=O)[nH]c(=O)c3ccccc32)cc1NS(=O)(=O)c1ccccc1",
        "C=CCC1(C(=O)N2CC[C@@H](c3nc(C)no3)C2)CCOCC1",
        "CC[C@@H](CC#N)NC(=O)c1nnc2ccc(Br)cn12",
        "O=C1CCCc2cc(C(=O)N3C[C@@H](c4ccccc4)[C@@H]4CCC[C@H]43)ccc2N1",
        "C[C@@H]1Cc2ccccc2N1C1CCN(C(=O)[C@H]2CCCN(C(=O)c3ccc4[nH]ncc4c3)C2)CC1",
        "CSC[C@@H](C)C(=O)N1CCOC[C@H]1CC(=O)[O-]",
        "O=C(c1ccnn1C1CCCC1)N1CCC(c2c[nH]c3ccccc23)CC1",
        "COCC1(C)CCN(C(=O)Nc2ccc(-n3cccn3)nc2)CC1",
        "O=C1Cc2cc(CCCC(=O)Nc3ccccc3N3CCCC3=O)ccc2N1",
    ],
    [
        "Cc1cc(F)ccc1-n1ccc(C(=O)N2CCc3ccccc3[C@H]2CO)n1",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)CC1)C2=O",
        "C[C@@H](NC(=O)c1c[nH]nc1-c1cccnc1)c1ccc(Cl)cc1",
        "CCn1c(=O)c(=O)[nH]c2cc(C(=O)NC[C@H]3CN(C)CCO3)ccc21",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "O=C(NC[C@H]1CCC[N@H+](Cc2ncon2)C1)c1cccc(-n2cncn2)c1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](C)O1",
        "O=C(Nc1cccc(C(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1)[C@@H]1Cc2ccccc2O1",
        "CCc1onc(C)c1NS(=O)(=O)c1ccc(OCC(=O)[O-])c(Cl)c1",
        "CC(=O)Nc1ccc(NC(=O)c2cccc3ncn(C)c23)cc1",
    ],
    [
        "NC(=O)C1(c2ccccc2)CCN(C(=O)N[C@@H]2CCN(c3ccc(Cl)c(F)c3)C2)CC1",
        "C[C@]1(c2cccc(-c3noc([C@H]4C[C@H]4c4ccc(F)cc4)n3)c2)NC(=O)NC1=O",
        "CNC(=O)[C@@H]1CCC[C@H]1[NH2+][C@H]1[C@@H]2CCO[C@@H]2C12CCCC2",
        "CCc1cc(N2CC[C@@H](n3cc(C(=O)[O-])nn3)C2)c2ccccc2n1",
        "Cc1nc2c(cc1C(=O)N[C@H](C)c1ccc3c(c1)CCC(=O)N3)c(C)nn2C",
        "CCc1onc(C)c1NC(=O)NCC1CCc2ccccc2CC1",
        "Cc1ccc(F)cc1C(=O)NC(C)(C)c1cn(C)nn1",
        "CCOc1c(Cl)cc(CNc2ccc3nc(C)nn3n2)cc1OC",
        "O=C([C@@H]1C[C@@H]2CC[C@H]1O2)N1CCC(c2nc(=O)[nH][nH]2)CC1",
        "Cc1cc(C)cc(C(=O)N2CCC[C@H](C(=O)NCc3cccc([C@@]4(C)NC(=O)NC4=O)c3)C2)c1",
    ],
    [
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[nH]4)CC3)cc2)C1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)NCc1nc2ccccc2n1CC",
        "CCS(=O)(=O)N1CCN(c2nnc(-c3cccn3C)n2C)CC1",
        "Cc1cc(NC(=O)c2nn(C)c3ccccc23)ccc1NC(=O)c1cnc2n1CCC2",
        "O=C(c1ccccc1)N1CCN(C(=O)C2CCOCC2)CC1",
        "O=C(c1ccnn1C1CCCC1)N1CCC(c2c[nH]c3ccccc23)CC1",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "O=C([O-])C[C@H](NC(=O)c1ccc2cc[nH]c2c1)c1cccs1",
        "Cc1nc(CN(C)C(=O)C[C@H]2CCCC[C@H]2O)no1",
        "CS(=O)(=O)[C@@H]1CCN(C(=O)c2cccnc2N2CCCC2)C1",
    ],
    [
        "CCn1nc(C)c(C[N@H+]2CCc3[nH]cnc3[C@@H]2c2ccc(F)cc2)n1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](C)O1",
        "Cc1nc(N2CCOCC2)ccc1NC(=O)N1CC(CO)C1",
        "COc1ccccc1[C@@H](CNC(=O)N1CC[C@](F)(CO)C1)[NH+]1CCCC1",
        "O=C1NCCN(C(=O)c2cc(C3CC3)on2)[C@H]1c1ccc(C(F)(F)F)cc1",
        "Cn1c(=O)[nH]c2ccc(C(=O)NCC[C@H]3CN(c4ncnc5[nH]ncc45)c4ccccc43)cc21",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "CC1CCN(C(=O)C2CCN(C(=O)Nc3cccc(-c4ccc5c(c4)CCO5)c3)CC2)CC1",
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F)(F)F)cc2)C1",
        "CCn1cc(Cl)cc1C(=O)N[C@@H](C(=O)[O-])C(C)C",
    ],
    [
        "CCn1nc(C)c(Cn2cnc3c(sc4ncccc43)c2=O)n1",
        "O=C(Nc1cnn(C[C@H]2CCCO2)c1)N[C@H](CN1CCCC1=O)c1ccccc1",
        "Cc1c(Br)cc(F)cc1C(=O)N(CC(N)=O)CC(C)C",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "O=C(Cc1ccc(O)cc1)N1CCC[C@@H]1C[C@H](O)c1ccccc1",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "C[C@@H](NC(=O)N1C[C@H](c2ccccc2)[C@H]2COCC[C@H]21)c1ccc(NC(=O)NC2CC2)cc1",
        "O=C(Cn1cnc2scc(-c3ccc(Br)cc3)c2c1=O)N1CCCC1",
    ],
    [
        "O=C(Nc1cccc(Cn2nc3ccccn3c2=O)c1)N1CCC[C@H](c2cc3ccccc3[nH]2)C1",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2ccccc2)c1",
        "COC[C@H](Nc1ccc2nc(C3CC3)oc2c1)C1CCOCC1",
        "Cc1cc(S(N)(=O)=O)cc(C(=O)NC[C@@H]2CCCO2)c1C",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "C[C@@H]1Cc2ccccc2N1C1CCN(C(=O)[C@H]2CCCN(C(=O)c3ccc4[nH]ncc4c3)C2)CC1",
        "COc1ccc(-c2nc(CCNC(=O)c3sc(C)nc3C)co2)cc1",
        "CCc1csc(CC(=O)N[C@@H](CN2CCOCC2)c2ccc(C)cc2)n1",
        "O=C(NCCc1ccc2cn[nH]c2c1)N1CCCC1",
        "Cc1cc(NC(=O)c2nn(C)c3ccccc23)ccc1NC(=O)c1cnc2n1CCC2",
    ],
    [
        "O=C(CN1CCc2ccccc2C1=O)NCc1ccccc1",
        "O=C(Nc1cccc(C(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1)[C@@H]1Cc2ccccc2O1",
        "O=C(CNC(=O)[C@@H]1CCC[NH2+]1)Nc1ccc2c[nH]nc2c1",
        "C[C@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(F)c1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "Cn1ccnc1[C@]1(CNC(=O)c2ccc(-c3nnn[nH]3)cn2)NC(=O)NC1=O",
        "Cc1n[nH]c(C)c1CC(=O)N1CCO[C@H](c2ccccc2)C1",
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F)(F)F)cc2)C1",
        "O=C(c1ccnn1C1CCCC1)N1CCC(c2c[nH]c3ccccc23)CC1",
        "CC(C)C(=O)Nc1cc(C(=O)N2CCC(O)(c3ccccc3)CC2)ccn1",
    ],
    [
        "Cc1ccccc1Cc1noc(C2CCN(C(=O)N(C)C)CC2)n1",
        "O=C(Cc1c[nH]c2ccc(F)cc12)N[C@H]1CCCN(Cc2ccc(F)cc2F)C1=O",
        "CCNC(=O)N1CCC[C@@H]1c1nc(-c2ccccc2)c(C(C)C)o1",
        "C#Cc1cc(F)c(NC(=O)C(=O)N2CC=C(c3c[nH]c4ncccc34)CC2)c(F)c1",
        "CC(C)N(C)C(=O)C1CCN(C(=O)CCc2ccc(C(=O)[O-])cc2)CC1",
        "O=C1C[C@@H](C(=O)Nc2c(F)cccc2Oc2ccccc2)c2ccccc2N1",
        "Cc1nccn1-c1ncccc1CNC(=O)C1(c2ccccc2Cl)CCOCC1",
        "C[NH+]1CCC(CNC(=O)CNC(=O)c2ccc3ccccc3c2)CC1",
        "CNc1cccc(-c2cn(Cc3cc(C(F)(F)F)nn3C)nn2)c1",
        "C[C@H](NC(=O)N[C@@H](CO)C[C@@H](O)C(C)(C)C)c1ccc(-c2ccncc2)cc1",
    ],
    [
        "C[C@@H](c1ccc(F)c(F)c1)N(C)C(=O)c1cn(Cc2cccc(F)c2)nn1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](C)O1",
        "Cc1ccc(NC(=O)CCn2c(=O)[nH]c(=O)c3ccccc32)cc1NS(=O)(=O)c1ccccc1",
        "CC1CCN(S(=O)(=O)N[C@H]2CCN(c3ccccc3)C2=O)CC1",
        "CCc1nc([C@@H](C)NC(=O)N[C@@H]2CCCc3cn[nH]c32)n[nH]1",
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[nH]4)CC3)cc2)C1",
        "Cc1nc(C2CC2)nc(C)c1C(=O)NCC1CCC1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)c2)CC1",
        "O=C(NCc1noc2c1CCCC2)N[C@H]1CCCN(Cc2ccc(F)cc2F)C1=O",
        "C[C@]1(C(=O)[O-])CCC[N@@H+]1CC(=O)Nc1ccc(F)cc1Cl",
    ],
    [
        "C[C@H](NC(=O)c1ccc(Nc2ncccn2)cc1)[C@H](O)c1ccccc1",
        "O=C(NCc1ccc(Oc2cccnc2)c(F)c1)N1CC[C@H](C2CCOCC2)C1",
        "CCCNC(=O)C[NH+]1CCC(Nc2cc(C(F)(F)F)nc3ncnn23)CC1",
        "COc1ccc([C@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CCOCC2)cc1OC",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)NCc1nc2ccccc2n1CC",
        "O=C(Cc1ccc(O)cc1)N1CCC[C@@H]1C[C@H](O)c1ccccc1",
        "CCOc1ccc(CNC(=O)N2CCC[C@H](C(=O)NC)C2)cc1F",
        "C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1F)c1ccc(NC(=O)c2ccncc2)cc1",
        "C=C(C)CCNC(=O)[C@H]1CC(c2ccccc2)=[NH+]O1",
        "Cn1c(=O)[nH]c2ccc(C(=O)NCC[C@H]3CN(c4ncnc5[nH]ncc45)c4ccccc43)cc21",
    ],
    [
        "NC(=O)[C@H](Sc1nc2c(cnn2-c2cccc(Cl)c2)c(=O)[nH]1)c1ccc(F)cc1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc3n2)c(C)o1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)c2)CC1",
        "O[C@H]1CC[C@@H](Nc2ccc(Br)cn2)CC1",
        "CS(=O)(=O)c1ccccc1N1CCC[C@H]1c1cccnc1",
        "Cc1nn(C)c2nc(-c3cccs3)cc(C(=O)NCc3ccccc3Cn3cncn3)c12",
        "COc1ccc([C@@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CCOCC2)cc1OC",
        "Cc1cc(N2CCC(CO)CC2)nc(-c2cccnc2)n1",
        "Cc1n[nH]c(-c2ccc(NC(=O)CN3C(=O)N[C@](C)(c4ccc5ccccc5c4)C3=O)cc2)n1",
        "CNC(=O)[C@H]1CCCCN1C(=O)Cc1ccc2c(c1)CCO2",
    ],
    [
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "COCC(=O)N1CCN(C(=O)c2cccc(NCc3nc(C)cs3)c2)CC1",
        "O=C(c1ccc(-c2ccc(F)cc2)s1)N1CCN(c2cccnn2)CC1",
        "NC(=O)[C@H]1CCCN(c2ccc(C(=O)N3CCC(c4cc5ccccc5[nH]4)CC3)cc2)C1",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "Cc1ccc(CCC(=O)N[C@@H]2CCCCNC2=O)c(C)c1",
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
        "Cc1cccc(F)c1CNC(=O)[C@H]1CC(=O)N(C2CCCC2)C1",
        "CC1(C)CCC(CNC(=O)Cc2nc3ncccn3n2)CC1",
        "NC(=O)NC[C@H]1CCCN(C(=O)NCc2ccccc2Oc2ccccc2)C1",
    ],
    [
        "Cc1cc(COCC(=O)N(C)c2ccc(Br)cn2)no1",
        "COc1cc(NC(=O)CN2CCCCCC2=O)ccc1C(=O)[O-]",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "O=C(c1ccc2c(c1)CCCC2)N1CCCC[C@H]1c1nc(=O)[nH][nH]1",
        "C[C@]1(c2cccc(-c3noc([C@H]4C[C@H]4c4ccc(F)cc4)n3)c2)NC(=O)NC1=O",
        "Cc1c[nH]c(=O)n1-c1cccc(C(=O)N2CCc3c(ncn3-c3ccc(F)cc3)C2)c1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc3n2)c(C)o1",
        "C[C@@](O)(CCc1ccccc1)C(=O)N1CCCc2n[nH]cc21",
        "O=C([O-])c1cc(F)ccc1NS(=O)(=O)c1c[nH]c2ncccc12",
    ],
    [
        "O=C(Cc1ccc(O)cc1)N1CCC[C@@H]1C[C@H](O)c1ccccc1",
        "Cc1ccn2c(NC(=O)c3cc(F)ccc3Cl)nnc2c1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)c2)CC1",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "CCOC(=O)Cn1cnc2cc(Cl)ccc2c1=O",
        "O=C(NCCN1CCS(=O)(=O)CC1)[C@H]1CC(=O)N(c2ccc3c(c2)Cc2ccccc2-3)C1",
        "CC(C)[C@@H](O)CC(=O)N1CC=C(c2c[nH]c3ncccc23)CC1",
        "O=C(Nc1ccc2c(c1)COC2)c1coc(C2CCOCC2)n1",
        "COc1cc(C)c(C(=O)N2CCC[C@H]2c2nncn2C)cc1C(=O)[O-]",
        "O=C1CCCc2cc(C(=O)N(CCCO)Cc3cccc(Cl)c3)ccc2N1",
    ],
    [
        "C#Cc1cc(F)c(NC(=O)C(=O)N2CC=C(c3c[nH]c4ncccc34)CC2)c(F)c1",
        "C[C@@H](NC(=O)C(Cc1ccccc1)Cc1ccccc1)c1ccc2c(c1)CC(=O)N2",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s1",
        "O=C1[C@@H]([N@H+]2CCC[C@@H](Cn3ccnn3)C2)CCN1C1CC1",
        "CCc1c(NCc2ncnn2-c2ccccc2)cnn1-c1ccccc1C",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "Cc1c(CCC(=O)N2CCN(C(=O)c3ccccc3)CC2)cnn1C",
        "CC1(C)OCC[C@H]1NC(=O)c1ccc(C(=O)[O-])cc1",
        "C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1F)c1ccc(NC(=O)c2ccncc2)cc1",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c(C)c1",
    ],
    [
        "O=C(NCCN1CCS(=O)(=O)CC1)[C@H]1CC(=O)N(c2ccc3c(c2)Cc2ccccc2-3)C1",
        "COc1ccc(Cl)cc1C(=O)N[C@H]1CCC(=O)NC1=O",
        "CC(C)S(=O)(=O)CC(=O)Nc1c2c(nn1C)CCC2",
        "O=C1CCCN1Cc1ccc(C(=O)N2CCC[C@@H](N3CCCS3(=O)=O)C2)cc1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](C)O1",
        "Cc1cc(C)c(NC(=O)[C@H]2C[C@@H]2c2ccccc2C)c(C)n1",
        "CC(C)c1ncncc1C(=O)Nc1cccc(-c2nncn2C)c1",
        "Cc1cccc(-c2cccc(C(=O)N3C[C@H](CO)[C@@H](CO)C3)c2)c1",
    ],
    [
        "Cc1c[nH]cc1C(=O)N1CCC(c2ccc(S(N)(=O)=O)cc2)CC1",
        "COc1cc(CCO)ccc1NC(=O)[C@H]1CC1(C)C",
        "NC(=O)C1(c2ccccc2)CCN(C(=O)N[C@@H]2CCN(c3ccc(Cl)c(F)c3)C2)CC1",
        "Cc1c(C2CC2)n[nH]c1NC(=O)c1cc(C#N)cc(N(C)C)c1",
        "O=C(NCc1noc2c1CCCC2)N[C@H]1CCCN(Cc2ccc(F)cc2F)C1=O",
        "CN(Cc1ccc(F)cc1Cl)C(=O)c1cnns1",
        "O=C([C@@H]1C[C@@H]2CCCC[C@H]2N1C(=O)c1ccc2ccccc2c1)N1CCC[C@@H](O)CC1",
        "C[C@](O)(CCc1ccccc1)C(=O)N[C@@H]1CCCOc2ccccc21",
        "[NH3+][C@H](CC(=O)NCC(=O)NC1CC1)Cc1cc(F)c(F)cc1F",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1",
    ],
    [
        "CCOc1ccc(NC(=O)N[C@H]2CCc3[nH]ncc3C2)cc1OC",
        "O=C([O-])CCC1CCN(C(=O)CCc2cccs2)CC1",
        "Cc1cc(NC(=O)c2nn(C)c3ccccc23)ccc1NC(=O)c1cnc2n1CCC2",
        "O=C(c1ccnn1C1CCCC1)N1CCC(c2c[nH]c3ccccc23)CC1",
        "O=C(NC[C@@H]1CC[N@H+]1C1CCOCC1)c1cc(F)c2ncccc2c1",
        "COc1cccc(CNC(=O)N2CCC(C(=O)NCc3ccc(F)cc3)CC2)c1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "Cc1noc([C@@H]2C[C@H](CNc3cnccn3)[C@@H](O)C2)n1",
        "Cc1cnc(C(=O)Nc2cccc(-c3nc(C)c(C)[nH]3)c2)cn1",
    ],
    [
        "Cc1ccc(S(=O)(=O)NC(=O)c2ccco2)cc1C",
        "O=C1O[C@H](c2ccccc2)Cc2cc(C(=O)N3CC[C@H](c4ccccc4F)C3)ccc21",
        "O=C1CN(C(=O)C2CCN(c3ccc4nncn4n3)CC2)CCN1",
        "C[C@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(F)c1",
        "COc1cc(C)cc(CNC(=O)[C@@H]2Cc3ccccc3N2C(C)=O)c1",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c(C)c1",
        "C[N@H+]1CCn2nc(NC(=O)NCc3ccccc3C(F)(F)F)cc2C1",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
        "C[C@@H](C(=O)NCc1ccc(C(=O)N2CCOCC2)cc1)N1CCc2ccccc21",
        "Cc1nc(C(=O)N2CC=CCC23CCOCC3)nc(N2CC[C@@H]([NH3+])C2)c1C",
    ],
    [
        "CO[C@H]1C[C@H](COc2cccnc2)[N@@H+](Cc2ccnn2C)C1",
        "Cc1cc(C)cc(C(=O)N2CCC[C@H](C(=O)NCc3cccc([C@@]4(C)NC(=O)NC4=O)c3)C2)c1",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2ccccc2)c1",
        "Cc1n[nH]c(C)c1CC(=O)N[C@H]1CC(C)(C)Oc2ccccc21",
        "COC(=O)Nc1ccc(NC(=O)[C@@H]2CCCN(c3cnccn3)C2)cc1",
        "C[C@H](Nc1nc(-c2cccnc2)nc2c1CCC2)c1cccc(S(N)(=O)=O)c1",
        "Cc1cc(C(=O)N2CCC(CCC(=O)[O-])CC2)ccn1",
        "CN(c1ccccc1)S(=O)(=O)c1csc(C(=O)[O-])c1",
    ],
    [
        "O=C([O-])C1=[NH+]N(c2ccccc2Cl)C(=O)CC1",
        "Cc1cc(C(=O)[O-])ccc1S(=O)(=O)N[C@H](C)c1c(C)noc1C",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c(C)c1",
        "Cc1[nH]nc(C(=O)N2CCC(Oc3ccccc3Cl)CC2)c1C",
        "C[C@@H](NC(=O)c1c[nH]nc1-c1cccnc1)c1ccc(Cl)cc1",
        "O=C(NCc1ccc(C(=O)N2CCc3c(nc[nH]c3=O)C2)cc1)OCc1ccccc1",
        "O=C1NCc2nccc(N3CCC(c4ccccc4)CC3)c21",
        "O=C(NC[C@H]1C[C@@H]1c1ccccc1)[C@@H]1CC(=O)N(c2ccccc2)C1",
        "CC(C)n1cccc1C(=O)N[C@@H]1CC(=O)N(C(C)(C)C)C1",
        "C[C@H](Nc1nc(-c2cccnc2)nc2c1CCC2)c1cccc(S(N)(=O)=O)c1",
    ],
    [
        "CN(CC1(C)COC1)C(=O)Nc1cccc2nc(C(F)F)sc12",
        "O=C(Cc1c[nH]c2ccc(F)cc12)N[C@H]1CCCN(Cc2ccc(F)cc2F)C1=O",
        "C[C@H](O)C(=O)N1CCN(C(=O)c2cn(Cc3cccs3)nn2)CC1",
        "CO[C@H]1C[C@@H](N(C)S(=O)(=O)c2ccc(OCC(=O)[O-])c(Cl)c2)C1",
        "COc1ccc(-c2noc(-c3ccc(NC(=O)c4cc(F)cc(F)c4)cc3O)n2)cn1",
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F)(F)F)cc2)C1",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c(C)c1",
        "FC(F)(F)c1cc(-c2cncc(-c3nnn[nH]3)c2)ccc1Cl",
        "CCc1nc([C@@H]2CCCN2C(=O)Nc2ccncc2)no1",
        "O=C(CC[C@H]1Cc2ccccc2NC1=O)Nc1c(-c2ccccc2)[nH][nH]c1=O",
    ],
    [
        "COc1cc(F)cc(CNC(=O)N2CC[C@@]3(C2)C(=O)Nc2ccccc23)c1",
        "O=C(Nc1cccc(C(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1)[C@@H]1Cc2ccccc2O1",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "CC1(C)C[C@@H](NC(=O)Nc2nnc(C(C)(C)C)s2)CCO1",
        "Cc1ccc(CC(=O)N2CCC(NC(=O)c3ccccc3)CC2)cn1",
        "O=C([C@@H]1C[C@@H]2CC[C@H]1O2)N1CCC(c2nc(=O)[nH][nH]2)CC1",
        "Cc1cccc(-c2nnc([C@H](C)[N@H+](C)CC3CCOCC3)o2)c1",
        "C[C@](O)(CCc1ccccc1)C(=O)N[C@@H]1CCCOc2ccccc21",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)c2)CC1",
        "CS(=O)(=O)N1CC[C@H](CNc2ncnc3ccccc23)C1",
    ],
    [
        "C[C@@H]1CCCN1C(=O)c1ccc(-c2nnn[nH]2)cc1",
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](C)O1",
        "CCOc1cn(-c2ccccc2)nc1C(=O)N1CCN(c2ncccn2)CC1",
        "Fc1ccc(OCc2noc([C@H]3C[C@]34CC[NH2+]C4)n2)cc1",
        "C#Cc1cc(F)c(NC(=O)C(=O)N2CC=C(c3c[nH]c4ncccc34)CC2)c(F)c1",
        "O=C(NCC1([C@H](O)c2ccccc2)CC1)c1cc(Cl)cc2cccnc12",
        "CCN(CC)C(=O)CCCNC(=O)Cc1cc2ccccc2c(=O)[nH]1",
        "C[C@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(F)c1",
        "O=C(N[C@H]1CCO[C@@H]1c1ccc(Cl)c(F)c1)[C@@H]1C[C@@H]1c1c(F)cccc1F",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "Cc1[nH]c2ccccc2c1NC(=O)CCC(C)(C)C",
        "COc1ccc(CNC(=O)c2cnn(C(C)C)c2C)cc1",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "NC(=O)[C@H](Sc1nc2c(cnn2-c2cccc(Cl)c2)c(=O)[nH]1)c1ccc(F)cc1",
        "O=C1Cc2cc(CCCC(=O)Nc3ccccc3N3CCCC3=O)ccc2N1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "COc1nc(C)cc(N(C)CC2(O)CCCC2)n1",
        "C[C@@H](CO)NC(=O)Nc1cnc(-c2cccc(C(F)(F)F)c2)cn1",
    ],
    [
        "O=C(c1cccnc1C(F)(F)F)N1CCS(=O)(=O)CC1",
        "CCc1ncnc(N2CCN(C(=O)c3ccco3)CC2)c1F",
        "Cc1ccncc1NC(=O)CC(C)(C)c1ccccc1",
        "O=C(N[C@H]1CCO[C@@H]1c1ccc(Cl)c(F)c1)[C@@H]1C[C@@H]1c1c(F)cccc1F",
        "O=C(N[C@@H](Cc1ccccc1)C(=O)N1CCCC1)[C@@H](O)[C@@H](O)c1nc2ccccc2s1",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@@H]3C[C@H](O)c3ccc(F)cc3)n2)ccc1F",
        "CN1CC[C@@H](NC(=O)Nc2cnn(-c3ccccc3Br)c2)C1=O",
        "O=C([C@@H]1C[C@@H]2CCCC[C@H]2N1C(=O)c1ccc2ccccc2c1)N1CCC[C@@H](O)CC1",
        "CCOc1ccccc1CNC(=O)[C@@H]1C[C@@H](C)[C@@H](C(=O)[O-])O1",
        "O=C(NCc1ccc(C(=O)N2CCc3c(nc[nH]c3=O)C2)cc1)OCc1ccccc1",
    ],
]


- Experiment:
    name: 5 known

    dataset: datasets/DDS10_MQN.pkl

    model:
        name: MLP
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]
