- unique_initial_sample:
    seeds: [
    [
        "O=C(CCl)NCc1cnccn1",
        "Oc1ccc([C@H]2Oc3c(ccc(O)c3O)[C@@H](O)[C@H]2O)cc1O",
        "Cc1ccc(S(=O)(=O)N2Cc3ccc([N+](=O)[O-])cc3C2)cc1",
        "NC(=O)/N=N/c1c(F)c(F)c(F)c(F)c1F",
        "CCCOC(=O)NCCSC(=O)OCCC",
        "CC(=O)NC(CCC(=O)c1ccc(Cl)cc1)(C(=O)[O-])C(=O)[O-]",
        "Cc1ccccc1-c1c(N)nc(NC#N)nc1C(=O)Nc1ccccc1",
        "C/C(=[NH+]\\S(=O)(=O)c1cccc([N+](=O)[O-])c1)OCC(C)C",
        "OC[C@H]1O[C@@H](Oc2cc(/C=C/c3ccc(O)cc3)ccc2O)[C@H]",
        "CC(=O)Nc1ccc(S(=O)(=O)F)cc1Cl",
    ],
    [
        "COc1c(O)cc(Br)c(C=O)c1N",
        "CCCCN1C(=O)NC(=O)[C@@]1(C)c1ccccc1",
        "c1ccc(C2=[NH+]N[C@@H]3c4ccccc4-c4ccccc4N3C2)cc1",
        "Cc1cccc(-n2c(C)nc3ccc(NC(=O)NCCCl)cc3c2=O)c1",
        "c1c2c(cc3c1OCN(C1CC1)C3)OCN(C1CC1)C2",
        "CCCCc1cc(O)ccc1O",
        "COC(=O)CCc1cc(O)c2c(c1)[C@@H](C(=O)OC)[C@@H](c1",
        "O=C(CSc1ncc[nH]1)c1ccc(Br)cc1",
        "CC(C)=CCc1c(OC(=O)c2c(C)cc(O)cc2O)cc(CO)c(CO)c1",
        "C=CCNC(=S)NCc1cccc2ccccc12",
    ],
    [
        "CCN(CC)/[NH+]=C/C[C@H](C)Nc1ccnc2cc(Cl)ccc12",
        "Oc1ccc([C@H]2Oc3c(ccc(O)c3O)[C@@H](O)[C@H]2O)cc1O",
        "C[NH+]1C=c2c3c(ccc2=C2C=C[C@H]4C=C5OCOC5=CC4=C21)OCO3",
        "O=C([O-])c1cccc(O)c1O",
        "OCCCc1cc(O)c2c(c1)[C@@H](CO)[C@@H](c1ccc(O)c(O)c1)O2",
        "CCO/C=C1\\SC(=S)N(c2ccc(C(=O)[O-])cc2)C1=O",
        "CC(C)(C)C[NH+]1CCCN(c2ccc(Cl)cc2)C1",
        "O=C1c2ccccc2C(=O)N1Cc1cc([N+](=O)[O-])ccc1Cl",
        "COc1cccc(P(c2cccc(OC)c2)c2cccc(OC)c2)c1",
        "COC(=O)c1c(C)cc(OC(=O)c2c(C)cc(O)c(/C=[NH+]\\O)c2O)c(C",
    ],
    [
        "CC(=O)NC1=C([NH3+])C(=O)c2ccccc2C1=O",
        "COc1cccc2c1C(=O)C1=C(C2=O)c2c(O)cc(CO)cc2[C@@H](O)[C@H]1O",
        "O=C1/C(=C/c2ccc(O)c(O)c2)CC/C1=C\\c1ccc(O)c(O)c1",
        "COc1ccc(CC2=[N+](C)CCc3cc(OC)c(OC)cc32)cc1OC",
        "OCCCCC[NH2+]C1CCCCC1",
        "C1=Nc2c(ncnc2SCc2ccccc2)NN1",
        "CC1(C)O[C@@H]1C(=O)[O-]",
        "OC[C@H]1COc2cc(Cl)c(Cl)cc2O1",
        "O=c1c(O)c(-c2ccc(O)c(O)c2)oc2cc(O)c(O)c([O-])c12",
        "COc1ccc(CCc2nccn2C)cc1OC",
    ],
    [
        "COc1ccc(Cl)c(S(N)(=O)=O)c1",
        "Cc1cc(SCc2ccc([N+](=O)[O-])cc2)nc(N)n1",
        "O=C(N/[NH+]=C\\c1cccnc1)Nc1ccc(/N=N/c2ccccc2)cc1",
        "O=c1[nH]nc2c3cccc4cccc(c5ccc([O-])c1c52)c43",
        "CN(C=O)c1cc([N+](=O)[O-])ccc1OCc1ccccc1",
        "O=C(N/[NH+]=C\\C(F)(F)F)c1ccncc1",
        "O=C(CCc1ccc(O)c(O)c1)c1ccc(O)c(O)c1O",
        "CCOC(=O)N[C@H]1[C@@H]2OC(C)(C)O[C@@H]2O[C@H]1CC(=O)OC",
        "CCOC(=O)[C@H]1Cc2c(cc3c4c(cccc24)N(C(C)=O)C3)N(C)C1",
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
    ],
    [
        "O=C(c1cc(O)c(O)c(O)c1)c1ccc(O)c(O)c1O",
        "CCCC1(C)[C@@H](C#N)C(=O)NC(=O)[C@@H]1C#N",
        "Cc1cc(O)cc(O)c1-c1cc(=O)cc(-c2c(C)cc(O)cc2O)o1",
        "O=S(=O)([O-])CC[C@@H](O)S(=O)(=O)[O-]",
        "Cc1c([N+](=O)[O-])ccc2cccnc12",
        "CCOC(=O)/C=C/c1ccc2c(c1)O[C@@H](c1ccc(O)c(OC)c1)[C@H](CO)",
        "CCn1c(Cl)c(/C=[NH+]\\Nc2ccc([N+](=O)[O-])cc2)c2ccccc21",
        "N#CS/C=C\\C(N)=O",
        "O=c1oc2ccccc2cc1-n1nnc2cc([N+](=O)[O-])ccc21",
        "CCOc1ccc(/N=C/c2cccc([N+](=O)[O-])c2)c(O)c1",
    ],
    [
        "CCn1c(=O)c(C#N)c2n(CC)c3cc(C)c(C)cc3n2c1=O",
        "O=C1c2ccccc2C(=O)c2c(OC[C@H]3CO3)ccc(OC[C@@H]3CO3)c21",
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C@@H]1O",
        "Cc1cc(Cc2cc(C)c(O)c(CO)c2)cc(CO)c1O",
        "O=c1c(-c2ccc(O)c(O)c2)coc2cc(O)c(O)cc12",
        "C=C(Br)C[NH2+]CCCCCC",
        "CCOC(=O)c1[nH]c(CO)c(C(=O)OCC)c1C",
        "C[C@H]1CN(c2ccncc2[N+](=O)[O-])CCN1c1ccc(Cl)cc1",
        "CCC[C@H]1OCCN1CC",
        "CC1([N+](=O)[O-])COP(=O)(NCc2cccnc2)OC1",
    ],
    [
        "CCC(=O)Oc1cccc(OC(=O)CC)c1",
        "O=C1C[C@H](c2ccc(O)c(O)c2)Oc2cc(O)cc(O)c21",
        "Nc1nc(Cl)c2c(n1)CCC2",
        "Nc1ncnc2c1ncn2-c1ccccc1Cl",
        "COc1ccc(-c2nnc(-c3c(C)n(C)n(-c4ccccc4)c3=O)o2)cc1",
        "COc1cc2cccc(O)c2cc1OC",
        "O=C(NNC(=O)c1cccc2ccccc12)c1ccc(F)cc1",
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
        "OCCCNC(=S)Nc1ccc(-c2nc3ccccc3[nH]2)cc1",
        "CCN(CC)C(=O)Nc1cccc(O)c1",
    ],
    [
        "CNC(=O)NN",
        "Oc1cc(O)c2c(c1)O[C@H](c1cc(O)c(O)c(O)c1)[",
        "C[NH+]1C(C)(C)CC(O)(C(=O)[O-])CC1(C)C",
        "Nc1ncc2[nH]c(=O)[nH]c2n1",
        "Cn1cc(C(=O)c2ccccc2)cc(C(=O)c2ccccc2)c1=O",
        "COc1cc([C@H]2c3cc(O)c(OC)cc3C[C@]3(O)[C@@",
        "O=C1OC[C@@H](Cc2ccc(O)c(O)c2)[C@H]1Cc1ccc",
        "Nc1ccc(CCOc2ccc(N)cc2)cc1",
        "CCOc1ccc(N)c(SCC(=O)[O-])c1",
        "S=C1Nc2ccccc2CS1",
    ],
    [
        "CCOc1nc(C)cc(C(=O)[O-])c1C#N",
        "O=C(CCc1ccc(O)c(O)c1)c1ccc(O)c(O)c1O",
        "Cc1cccc(/C=[NH+]\\NC(=O)Nc2ccc(/N=N/c3ccccc3)cc2)",
        "CCOC(=O)CCN1C(=O)CC[C@H]1C(=O)OCC",
        "Cc1ccccc1-c1c(N)nc(NC#N)nc1C(=O)Nc1ccccc1",
        "C1CSC(N2CCOCC2)=N1",
        "CCO[N+]([O-])=C1C=C(C(C)(C)C)C(=O)C(C(C)(C)C)=C1",
        "COc1cccc([C@@H]2CCCC[C@@H]2O)c1",
        "CCCn1c(N)c(Cl)c(=O)n(CC)c1=O",
        "COC(=O)/C=C/CC(=O)NS(C)(=O)=O",
    ],
    [
        "C[C@H](CC(=O)c1ccc(F)cc1)[NH+]1CCCCC1",
        "CSCC[C@H]([NH3+])[P@](C)(=O)[O-]",
        "N#C/C(=C\\Nc1ccccn1)C(=O)C1CC1",
        "C(=[NH+]/Nc1nncn2cccc12)\\c1ccccc1",
        "CC(=O)[C@@H]1Cc2c(O)c3c(c(O)c2[C@@H](O)C1)C(=O)c1ccccc",
        "CC1(C(Cl)(Cl)Cl)C=CC(=[NH+]OCC(=O)[O-])C=C1",
        "C[NH+]1CCN(c2ccc3[nH]c(-c4c5cccccc-5[nH]c4=O)nc3c2)CC1",
        "COc1ccc2c(c1)CCC[C@@]2(O)C#C[C@]1(O)CCCc2cc(OC)ccc21",
        "CCOC(=O)[C@@H](CC(C)C)NC(=O)c1cc2ccccc2[n+](C)c1",
        "COc1cc([C@@H]2Oc3c(OC)cc4ccc(=O)oc4c3O[C@H]2CO)ccc1O",
    ],
    [
        "COc1cccc2c1CC[C@H]1C(C)(C)C(=O)CC[C@]21CC(=O)[O-]",
        "O=C(CCl)Nc1nncs1",
        "C[S@@](=O)CCC[NH+]=C=S",
        "CS(=O)(=O)Oc1ccccc1C(=O)[O-]",
        "COc1ccc(C[C@H](CO)NC(=O)c2ccccc2)cc1",
        "O=C(N/[NH+]=C\\c1ccccn1)Nc1ccc(/N=N/c2ccccc2)cc1",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)C[C@H]([C@]1(CO)CO1)",
        "O=C1c2cc(O)cc(O)c2C(=O)c2c1cc1c(c2O)[C@@H]2C=CO[C@@H",
        "S=C(N/[NH+]=C/c1c[nH]c2ccccc12)NC12CC3CC(CC(C3)C1)C2",
        "NC(=O)c1ccc[n+](Cc2ccccc2)c1",
    ],
    [
        "O=C1N[C@@](O)(c2ccccc2)c2ccccc21",
        "O=C1c2c(O)cc(O)cc2O[C@@H](c2ccc(O)c(O)c2)[C@@",
        "O=C(c1ccccc1)N1[NH+]=CCC[C@@H]1O",
        "CCOC(=O)[C@@H](C)Sc1n[nH]c(=O)[nH]c1=O",
        "O=C([O-])c1nc2ccccc2c2ncccc12",
        "COC(=O)[C@H]1Cc2cncn2C(=O)N1",
        "CCOC(=O)N/[NH+]=C/c1ccc(OC)c(O)c1",
        "O=c1[nH][nH]c(=O)c2c1nc(SCCc1ccccc1)n2Cc1cccc",
        "O=C1OC[C@@H](Cc2ccc(O)c(O)c2)[C@H]1Cc1ccc(O)c",
        "CCOC(=O)C(Cc1cc2c(n1C)CCCC2)(NC(C)=O)C(=O)OCC",
    ],
    [
        "CCCCC=C1C(=O)NC(=S)NC1=O",
        "CC1(C)CCC[NH+]1CCOC(=O)[C@H](c1ccccc1)[C@H]1C=CCC1",
        "CCCCOC(=O)[C@@H]([NH3+])Cc1ccc(OC)c(Cl)c1",
        "O=C1OCC(c2ccc(O)cc2)=C1c1cc(O)c(O)c(O)c1",
        "O=C1c2cc(O)c(O)cc2O[C@H](c2ccc(O)c(O)c2)[C@H]1O",
        "CCCC(=O)Nc1ccc(C)cc1",
        "CN1[NH+]=C2c3ccccc3CC[C@H]2[C@@H]1c1cccc(O)c1",
        "Cc1ccccc1-c1c(N)nc(NC#N)nc1C(=O)Nc1ccccc1",
        "CCOC(=O)NC(=O)CBr",
        "CCO/C=[NH+]\\C1=C(C#N)SC2=N/C(=C\\c3ccco3)C(=O)N21",
    ],
    [
        "Fc1cc(Cl)ccc1Cl",
        "CCOC(=O)/C(=C\\c1ccc(Cl)cc1)C(C)=O",
        "OCCCNC(=S)Nc1ccc(-c2nc3ccccc3[nH]2)cc1",
        "N#CCN1CCCN(CC#N)C1",
        "CC(C)(C)[Si](C)(C)OC[C@]12CC[C@H]3C[NH2+][C@H]([C@H]31)[C@H](c1ccccc1)N2",
        "COc1cc(CCCOC(=O)/C=C/c2ccc(O)c(O)c2)cc(O)c1O",
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
        "CC(=O)C(=Cc1cccc([N+](=O)[O-])c1)C(C)=O",
        "CC(=O)Oc1cccc2c1[nH]c(=O)c1c(OC(C)=O)c3c(cc12)OCO3",
        "CCc1nn2c(=O)nc(SC)nc2s1",
    ],
    [
        "N/C(=N/c1ccc(O)cc1)S(=O)(=O)[O-]",
        "COc1ccc2c(c1)CCC[C@@]2(O)C#C[C@]1(O)CCCc2cc",
        "C/C(=[NH+]/NC(=O)Nc1ccc(/N=N/c2ccccc2)cc1)c",
        "CC(=O)Nc1ccc(S(=O)(=O)CCBr)cc1",
        "O=C1c2ccccc2C(=O)N1/N=N/N1C(=O)c2ccccc2C1=O",
        "O=C([O-])c1ccc(Oc2ccccc2)cc1",
        "CCOC(=O)C1CCc2ccccc2CC1",
        "O=c1cc(-c2ccc(O)cc2)oc2ccccc12",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)c1ccc(O)c(O)c1",
        "O=C(Cl)c1ccc(C(F)(F)F)cc1",
    ],
    [
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)cc([O-])c12",
        "O=C(Oc1ccccc1)c1cc2ccccc2oc1=O",
        "CC(=O)N[C@H](CS(=O)(=O)Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "CC(=S)NC(=O)NC(=O)c1ccc(C)cc1",
        "COc1cc(C[C@@H]2COC(=O)[C@]2(O)Cc2ccc(O)c(OC)c2)ccc1O",
        "CCOC(=O)/C(C#N)=C(\\C)c1ccccc1",
        "O=C1C2=C(C(=O)c3ncccc31)[C@H]1C=C[C@H]2CC1",
        "O=C1OCC(c2ccc(O)c(O)c2)=C1c1cc(O)c(O)c(O)c1",
        "NC(=O)N(CCc1ccccc1)N=O",
        "COc1cc(C)c(Cl)c(C)c1C(C)=O",
    ],
    [
        "O=C1c2ccc(O)cc2O[C@@H](c2cc(O)c(O)c(O)c2)[C@@H]1O",
        "O=C1CS[C@H](c2cc([N+](=O)[O-])ccc2Cl)N1c1nncs1",
        "O=C([O-])c1cccc(N2C(=O)CSC2=S)c1",
        "COc1c(-c2ccc(O)c(O)c2)oc2c(O)c(O)cc([O-])c2c1=O",
        "CC(C)[C@@H](NC(=O)c1cnc2ccccc2n1)C(=O)N[C@@H](C)C(=O)[O-]",
        "CC(=O)Nc1ccc(C(=O)Sc2ccccc2C(=O)NCCC(N)=O)cc1",
        "O=c1c2ccccc2sc2c1c(N(CCO)CCO)cc1ccccc12",
        "Cc1nc2[nH]nc(N)c2c(C)c1Br",
        "COc1cc(O)c2c(c1)C(=O)c1cc(C)cc(O)c1C2=O",
        "O=C(Nc1ccc(S(=O)(=O)[O-])cc1)c1ccco1",
    ],
    [
        "Cc1ccc(-n2cnc3c(Cl)ncnc32)cc1[N+](=O)[O-]",
        "CCc1ccc2c(O)c3c(cc2c1C(=O)OC)C(=O)c1cccc(O)c1C3=",
        "O=C1C=C2C[C@@]3(O)COc4c(ccc(O)c4O)C3=C2C=C1O",
        "CCOC(=O)c1ccc(=O)n(Cc2ccccc2)c1",
        "CC(C)(O)[C@@H]1CCCC[C@H]1Cl",
        "Cn1c(=O)nc2n(-c3ccc(Cl)cc3)c3ccc(Cl)cc3nc-2c1=O",
        "Cn1cc(C2=C(c3cccc(OC[C@@H](O)CO)c3)C(=O)NC2=O)c2",
        "O=C(CCCc1ccncc1)c1ccccc1",
        "O=C([O-])CNC(=O)CCl",
        "O=C(/C=C/c1ccccc1)C1=C([O-])C(=O)O[C@H]1c1ccccc1",
    ],
    [
        "O=C(/C=C/c1ccc(O)c(O)c1)c1ccc(O)c(O)c1O",
        "O=c1cc2oc3cc(O)c(O)cc3c(-c3ccccc3O)c-2cc1O",
        "O=c1c(OC/C(=[NH+]/O)c2ccc(F)cc2)c(-c2ccccc2)oc2ccccc12",
        "ClCC(CCl)(CCl)CCl",
        "Cc1ccc([S@@](=O)c2ccc([N+](=O)[O-])cc2[N+](=O)[O-])cc1[N+](=O)[O-]",
        "C[C@H]1Oc2c3c(cc(O)c2C(=O)[C@@H]1C)OC(C)(C)CC3",
        "COc1ccc(CC[NH2+]C2=CC(=O)CC2)cc1OC",
        "C[NH+](CCCl)C[C@@H]1CSCO1",
        "O=C1NC(=O)/C(=C/c2ccc(Cl)cc2Cl)N1",
        "C/N=N\\C(C)C",
    ],
    [
        "N#Cc1sc(=S)n(-c2ccccc2)c1N",
        "C[C@@H](NC(=O)Oc1ccccc1)Oc1ccccc1",
        "O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)",
        "C=Cc1c(C)cc(C)cc1C",
        "CN(C)c1nc(Oc2nc(N(C)C)nc(N(C)C)n2)nc(N(C)C)n1",
        "O=C(N/[NH+]=C\\c1ccccn1)Nc1ccc(/N=N/c2ccccc2)c",
        "Nc1ccc(CC[C@H]2CCC/C=C/[C@@H]3C[C@H](O)C[C@H]",
        "CN(N=O)C(=O)NCCOC(=O)N(C)N=O",
        "C[NH+](C)Cc1cc(Cl)ccc1O",
        "O=NN(CC(=O)[O-])Cc1ccccc1",
    ],
    [
        "O=C1c2ccccc2CCc2ccccc21",
        "CN(C)c1ccc(/[N+]([O-])=C/c2cc(=O)c(OS(C)(=O)=O)co2)cc1",
        "COc1cccc2oc([N+](=O)[O-])cc12",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)C[C@H]([C@]1(CO)CO1)O2",
        "C[C@@H]1C[C@H]([C@@H](O)CC2CC(=O)N(Cc3ccccc3)C(=O)C2)[",
        "O=C([O-])c1cc(I)cc(I)c1",
        "O=C(c1ccc([N+](=O)[O-])cc1)c1ccc(O)cc1O",
        "Cc1cccc(Cl)c1OCC(N)=O",
        "CC(C)=CCc1ccc2[nH]c3c(c2c1)C(=O)C(=O)C(C)=C3[C@@H](O)[",
        "CCO[C@H]([C@@H](OCC)[n+]1ccccc1)[n+]1ccccc1",
    ],
    [
        "CCOC(=O)[C@H]1C[C@@H]1C(=O)OCC",
        "CC(=O)Nc1ccc2c(c1)/C(=N/c1ccc(C(=O)[O-])cc1)c",
        "CN(C)C(=O)OCCOc1ccc(Cl)cc1",
        "O=C(OCCO)N1CC[NH+](CCO)CC1",
        "S=C(N/[NH+]=C(\\c1ccccc1)c1ccccn1)SCc1ccccc1",
        "O=C([O-])C(=Cc1ccc([N+](=O)[O-])cc1)C(=O)[O-]",
        "C/C(=[NH+]/C(C)(C)C)N1CCCCC1",
        "O=C1c2cc(O)cc(O)c2C(=O)c2c1cc1c(c2O)[C@@H]2C=",
        "O=c1c(-c2ccc(O)c(O)c2)coc2cc(O)c(O)cc12",
        "N#CC(C#N)C1c2ccccc2-c2ccccc21",
    ],
    [
        "CCOC(=O)[C@H]1C[C@H](O)C[NH2+]1",
        "Cc1ncc(C(=O)[O-])s1",
        "O=C(NC(=S)NC(=O)c1cc(O)c(O)c(O)c1)c1cc(O)c(O)c(O)c1",
        "COc1cc(C[C@@H]2COC(=O)[C@]2(O)Cc2ccc(O)c(OC)c2)ccc1O",
        "CN1COc2ccc(Br)cc2C1",
        "C[N+](C)(C)CC(=O)N/[NH+]=C/c1ccc([N+](=O)[O-])o1",
        "COc1cc2ccccc2[n+](C)c1-c1ccccc1F",
        "Fc1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3ccccc3)C2)",
        "[O-][n+]1cc[n+]([O-])c2c3ccccc3ccc21",
        "O=C(NN1CCCCC1)c1ccccc1",
    ],
    [
        "c1ccc(C2=[NH+]N[C@H](c3cn(-c4ccccc4)nc3-c3ccccc3)C2)c",
        "C/C(CCO)=[NH+]\\NC(N)=S",
        "Cc1c(C)c(C)c(C[NH+]2CCCC2)c(C)c1C",
        "C[S+](C)CCO",
        "Oc1ccc2c(c1)OC[C@@]1(O)Cc3cc(O)c(O)cc3[C@H]21",
        "Cc1[nH]c(N)nc(=O)c1CCCNC(=O)c1ccc(N)cc1",
        "CCCCc1ccc([I+]c2cccc([N+](=O)[O-])c2)cc1",
        "CCN(CC)CC#CCN(CC)CC",
        "C[C@H](Oc1ccc2cc(C(=O)c3ccccc3)c(=O)oc2c1)C(=O)[O-]",
        "O=C(c1cc(O)c(O)c(O)c1)c1ccc(O)c(O)c1O",
    ],
    [
        "COc1ccc(OC)c(/C=C/C=O)c1",
        "CCCCN(CC)CC#N",
        "N#Cc1cccc(F)c1",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)ccc12",
        "Cc1cccc(/C=[NH+]\\NC(=O)Nc2ccc(/N=N/c3ccccc3)",
        "Cc1ccc(N2CC[NH+](C[C@H](O)COc3ccccc3)CC2)cc1",
        "O=c1oc(-c2ccc(O)c(O)c2)cc2cc(O)cc([O-])c12",
        "COc1ccc(/C=C2/SC(=O)NC2=O)cc1OC",
        "O=S(=O)(NCc1ccco1)c1ccc(F)cc1",
        "O=C(NN1C(=O)[C@H](Cl)[C@H]1c1c(O)ccc2ccccc12",
    ],
    [
        "O=c1[nH]c(=O)ss1",
        "Cc1[nH]c2ccc(C(=O)NN)cc2c1CC(=O)NN",
        "Cc1ccccc1C(=O)[C@@H]1CCCCC1=O",
        "COc1cc(CCl)cc(OC)c1OC",
        "CC[NH+]1C[C@@H](O)C2=C/C(=[NH+]/NC(N)=O)C(=O)C=C21",
        "CC[C@H]1c2cc3n(c(=O)c2CO[C@H]1O)Cc1c-3nc2ccccc2c1C",
        "CSC(=[NH2+])c1cccc(CCCCc2ccc(NC(C)=O)cc2)c1",
        "C[N+](C)(C)CCOC(=O)c1ccc(CBr)cc1",
        "COc1ccc2c(c1)OC/C(=C\\c1ccc([N+](=O)[O-])o1)C2=O",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)cc([O-])c12",
    ],
    [
        "COc1cc([C@@H]2Oc3c(OC)cc4ccc(=O)oc4c3O[C@H]2CO)ccc1O",
        "C(=[NH+]/[NH+]=C/c1cccs1)\\c1cccs1",
        "CC[C@H]1c2cc3n(c(=O)c2CO[C@H]1O)Cc1c-3nc2ccccc2c1Cl",
        "Oc1cc(O)c2c(c1)O[C@H](c1cc(O)c(O)c(O)c1)[C@@H](O)C2",
        "CC(=O)N[C@H](C)C(=O)N(C)/N=N/c1ccc(C#N)cc1",
        "CCCCCCOc1ccccc1CO",
        "CC(=O)c1c(COc2ccc(Cl)cc2)[n+]([O-])c2ccccc2[n+]1[O-]",
        "CCOC(=O)CNC(=O)Oc1cccc2cccnc12",
        "O=C1N[C@@H](Cc2ccccc2)C(=O)O1",
        "CCOC(=O)C(=O)NCc1ccc(Cl)cc1Cl",
    ],
    [
        "CC(=O)c1cc(=O)[nH]c(=O)[nH]1",
        "COC(=O)C[C@@]1(C)[C@H](O)[C@H]2OC(C)(C)O[C@H]2[C@@H]1O",
        "c1ccc(/C(=[NH+]\\[NH+]=c2\\[nH]c3ccccc3s2)c2ccncc2)cc1",
        "Cc1cccc(Cl)c1",
        "OCCCNC(=S)Nc1ccc(-c2nc3ccccc3[nH]2)cc1",
        "O=C1NCc2nnn(Cc3ccccc3)c2N1",
        "Nc1ccc(/N=N/c2ccc3nccc(N)c3c2)c(N)n1",
        "CC(C)=CCc1c(OC(=O)c2c(C)cc(O)cc2O)cc(CO)c(CO)c1O",
        "COC(=O)[C@H](CC=O)c1ccc(OC)cc1",
        "COc1cccc2c1C(=O)C1=C(C2=O)c2c(O)cc(CO)cc2[C@@H](O)[C@H",
    ],
    [
        "CC1(C)CC(=O)c2c(oc(=O)c3ccccc23)C1",
        "CCOC(=O)c1cnc2c(OC)cccc2c1O",
        "OCc1c(CO)c(Br)c2ccccc2c1Br",
        "C[C@@H]1C[C@H]([C@@H](O)CC2CC(=O)N(Cc3ccccc3)C(=O)C2)[C@H](O)[C@H](",
        "O=Cc1cc(O)c(O)c(O)c1-c1c(C=O)cc(O)c(O)c1O",
        "C1CCC[NH+](CCN2CCOCC2)CCC1",
        "Cc1cc(O)c(C(C)C)cc1C[NH+]1CCCCC1",
        "O=C(/C=C/c1ccc(O)c(O)c1)CC(=O)/C=C/c1ccc(O)c(O)c1",
        "C=C(C)[C@H]1C[C@@H]2O[C@]2(C)[C@@H](O)C1",
        "O=[N+]([O-])c1cc/c(=[NH+]\\[NH+]=C/c2ccc(O)c(S(=O)(=O)[O-])c2)[nH]c1",
    ],
]



- Experiment:
    name: Enrich 3(rdkit2D)

    dataset: datasets/DTP_RDKIT2D.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [1320]
