- unique_initial_sample:
    seeds: [
    [
        "C[C@H](Nc1nc(-c2cccnc2)nc2c1CCC2)c1cccc(S(N)(=O)=O)c1",
        "NC(=O)c1ccc(C(=O)N2CCC[C@H](Cn3ccnn3)C2)nc1",
        "COc1ccnc(NC[C@]23C[C@](NC(=O)[C@@H]4C[C@@H]4C)(C2)C(C)(C)O3)n1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "O=C([C@@H]1C[C@@H]2CCCC[C@H]2N1C(=O)c1ccc2ccccc2c1)N1CCC[C@@H](O)CC1",
        "O=C(Nc1cccnc1)c1cccc(S(=O)(=O)N2CCCCC2)c1",
        "Cc1cc([N+](=O)[O-])c(C)c(S(=O)(=O)N(C)[C@@H]2C[N@H+]3CC[C@@H]2CC3)c1",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "Cc1ccc(C[C@@H](C)NC(=O)N2CCS(=O)(=O)CC2)s1",
    ],
    [
        "O=C([O-])c1cccc(CS(=O)(=O)N2CC[C@H](O)C2)c1",
        "C[C@](O)(CCc1ccccc1)C(=O)N[C@@H]1CCCOc2ccccc21",
        "Cc1ccccc1CNc1cc(C(N)=O)ccc1Cl",
        "COc1ccc(OC)c([C@@H]2CCCN2C(=O)c2ccnc(OC)n2)c1",
        "C=CCN(CC(=O)[O-])S(=O)(=O)c1ccc(OC)c(Cl)c1",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2cccc",
        "O=C(c1ccc2c(c1)CCCC2)N1CCCC[C@H]1c1nc(=O)[nH][nH]1",
        "O=C([C@@H]1C[C@@H]2CC[C@H]1O2)N1CCC(c2nc(=O)[nH][nH",
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
        "CC[NH+]1CCN([C@@H]2CCN(C(=O)Cc3cncs3)C2)CC1",
    ],
    [
        "CC(C)C[C@H]1C(=O)NCCN1C(=O)c1cc(O)nc(C(C)C)c1",
        "O=C(Cc1ccc(-n2cnnn2)cc1)Nc1cnn(C[C@@H]2CCCO2)c1",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
        "COc1ccc(-c2noc(-c3ccc(NC(=O)c4cc(F)cc(F)c4)cc3O)n2)cn1",
        "O=C(NCC1([C@@H](O)c2ccccc2)CC1)c1cnn2c(=O)cc[nH]c12",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "Cc1cc(C)n(CC(=O)NC[C@@H]2CC[C@@H](c3ncn[nH]3)O2)n1",
        "O=C(NCc1ccc(-c2ccccc2)cc1)[C@@H]1C[C@@H](O)CN1C(=O)c1ccc(",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)CC1)C",
        "CN(C)c1cccc(S(=O)(=O)N2CCC[C@@H](n3cc(C(=O)[O-])cn3)C2)c1",
    ],
    [
        "Cn1c(=O)[nH]c2ccc(C(=O)NCC[C@H]3CN(c4ncnc5[nH]ncc45",
        "O=C1CCCc2cc(C(=O)N(CCCO)Cc3cccc(Cl)c3)ccc2N1",
        "C=CCC1(C(=O)N2CC[C@@H](c3nc(C)no3)C2)CCOCC1",
        "CC[C@@H](CC#N)NC(=O)c1nnc2ccc(Br)cn12",
        "O=C(c1cccc(Cn2ccnn2)c1)N1C[C@H]2COC[C@@H]2C1",
        "C[C@H](Cc1nc(-c2ccccc2)no1)NC(=O)c1cccc(C#N)c1",
        "O=C(N[C@@H](Cc1ccccc1)C(=O)N1CCCC1)[C@@H](O)[C@@H](",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "COCC1(C)CCN(C(=O)Nc2ccc(-n3cccn3)nc2)CC1",
        "Cc1ccc(NC(=O)CCn2c(=O)[nH]c(=O)c3ccccc32)cc1NS(=O)(",
    ],
    [
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)[C@@H]2CC(=O)N(c3ccc4c",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "O=C(Nc1cnn(-c2ncccc2F)c1)C1(F)CCC1",
        "CCn1c(=O)c(=O)[nH]c2cc(C(=O)NC[C@H]3CN(C)CCO3)ccc21",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "O=C1Cc2cc(CCCC(=O)Nc3ccccc3N3CCCC3=O)ccc2N1",
        "Cc1nc2c(cc1C(=O)N[C@H](C)c1ccc3c(c1)CCC(=O)N3)c(C)nn2",
        "CC(C)c1cccc(S(=O)(=O)NC(=O)CC[C@H]2Cc3ccccc3NC2=O)c1",
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc54",
        "CC(=O)Nc1ccc(NC(=O)c2cccc3ncn(C)c23)cc1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)c2",
        "CNC(=O)[C@@H]1CCC[C@H]1[NH2+][C@H]1[C@@H]2CCO[C@@H]2C12CCCC2",
        "O=C(NC[C@@H]1CCC[C@@]12NC(=O)NC2=O)Nc1ccn(-c2cccc(C(F)(F)F)c",
        "C[C@@]1(c2cnccn2)NC(=O)N(Cc2noc3c2CCCC3)C1=O",
        "O=C(CCCc1c[nH]c2ccccc12)N[C@@H]1C[C@H](Cn2ccnc2)C[C@@H]1O",
        "Cc1ccc(F)cc1C(=O)NC(C)(C)c1cn(C)nn1",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "O=C(C[C@@H]1CCc2ccccc2C1)N1CCC(c2nnc3n2CC[NH2+]C3)CC1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)[C@@H]2CC(=O)N(c3ccc4c(c3)CCC",
    ],
    [
        "O=C(COc1ccc(F)cc1)N[C@H]1CCC(=O)N[C@H]1c1ccccc1",
        "O=C1C[C@@H](C(=O)Nc2c(F)cccc2Oc2ccccc2)c2ccccc2",
        "O=C(NC[C@H]1C[C@@H]1c1ccccc1)[C@@H]1CC(=O)N(c2c",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2",
        "O=C(c1ccccc1)N1CCN(C(=O)C2CCOCC2)CC1",
        "O=C(Nc1cccc(C(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1)",
        "O=C(Cc1c[nH]c2ccc(F)cc12)N[C@H]1CCCN(Cc2ccc(F)c",
        "O=C([O-])C[C@H](NC(=O)c1ccc2cc[nH]c2c1)c1cccs1",
        "Cc1nc(CN(C)C(=O)C[C@H]2CCCC[C@H]2O)no1",
        "CS(=O)(=O)[C@@H]1CCN(C(=O)c2cccnc2N2CCCC2)C1",
    ],
    [
        "CCn1nc(C)c(C[N@H+]2CCc3[nH]cnc3[C@@H]2c2ccc(F)cc2)n1",
        "COC(=O)c1csc(NC(=O)[C@@]2(C)CCN(C(C)=O)C2)c1",
        "O=C1NCCN(C(=O)c2cc(C3CC3)on2)[C@H]1c1ccc(C(F)(F)F)cc1",
        "COc1ccccc1[C@@H](CNC(=O)N1CC[C@](F)(CO)C1)[NH+]1CCCC1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc4C3=O)",
        "C[C@]1(c2cccc(-c3noc([C@H]4C[C@H]4c4ccc(F)cc4)n3)c2)NC(=O)",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)CC1)C2",
        "CC1CCN(C(=O)C2CCN(C(=O)Nc3cccc(-c4ccc5c(c4)CCO5)c3)CC2)CC1",
        "O=C(Cc1cccnc1)NCc1cn(-c2ccccc2)nc1-c1ccc(F)cc1",
        "CCn1cc(Cl)cc1C(=O)N[C@@H](C(=O)[O-])C(C)C",
    ],
    [
        "O=C(NCc1ccc2c(n1)CCCC2)C1CCN(C(=O)N2CCCC2)CC1",
        "O=C(Nc1cnn(C[C@H]2CCCO2)c1)N[C@H](CN1CCCC1=O)c1ccccc1",
        "O=C(c1n[nH]c2ccc([N+](=O)[O-])cc12)N1CC[C@H](C(F)(F)F)[C@@H]",
        "CS(=O)(=O)NCc1cn(-c2cccc(C(F)(F)F)c2)nn1",
        "C[C@@H](NC(=O)N1C[C@H](c2ccccc2)[C@H]2COCC[C@H]21)c1ccc(NC(=",
        "Cc1c[nH]c(=O)n1-c1cccc(C(=O)N2CCc3c(ncn3-c3ccc(F)cc3)C2)c1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COc1cccc(C(=O)NCC(=O)N[C@@H]2CCC(=O)N[C@H]2[C@@H]2CCCO2)c1",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
    ],
    [
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F)(F)F)c",
        "Cn1ccnc1[C@H]1CCN(C(=O)Cc2n[nH]c(=O)c3ccccc23)C1",
        "O=C(O[C@H]1CCN(c2ccccc2Cl)C1=O)c1n[nH]c(=O)c2ccccc12",
        "Cc1cc(S(N)(=O)=O)cc(C(=O)NC[C@@H]2CCCO2)c1C",
        "C[C@H](C(=O)NS(C)(=O)=O)c1ccc(-c2ccc(O)c(F)c2)c(F)c1",
        "CC(C)c1cccc(S(=O)(=O)NC(=O)CC[C@H]2Cc3ccccc3NC2=O)c1",
        "COc1ccc(-c2nc(CCNC(=O)c3sc(C)nc3C)co2)cc1",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "C[C@](O)(CCc1ccccc1)C(=O)N[C@@H]1CCCOc2ccccc21",
        "Cc1csc([C@H]2CCCN2C(=O)c2ccc3cc[nH]c3n2)n1",
    ],
    [
        "O=C(CN1CCc2ccccc2C1=O)NCc1ccccc1",
        "COC(=O)[C@@H]1CCc2nnc(C(=O)N3CCCC3)n2C1",
        "O=C(CNC(=O)[C@@H]1CCC[NH2+]1)Nc1ccc2c[nH]nc2c1",
        "O=C(CC[C@H]1Cc2ccccc2NC1=O)Nc1c(-c2ccccc2)[nH][nH]c1=O",
        "C[C@H]1C[C@@H]1C(=O)Nc1n[nH]c2nc(C(F)(F)F)ccc12",
        "O=C(Cc1cccnc1)NCc1cn(-c2ccccc2)nc1-c1ccc(F)cc1",
        "Cc1nc([C@H](NC(=O)[C@H]2C[C@H]2c2ccc(C(F)(F)F)cc2)c2cc",
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc54)",
        "CNc1cccc(-c2cn(Cc3cc(C(F)(F)F)nn3C)nn2)c1",
        "CC(C)C(=O)Nc1cc(C(=O)N2CCC(O)(c3ccccc3)CC2)ccn1",
    ],
    [
        "Cc1ccccc1Cc1noc(C2CCN(C(=O)N(C)C)CC2)n1",
        "O=C1CCCc2cc(C(=O)N3C[C@@H](c4ccccc4)[C@@H]4CCC[C@H",
        "CCNC(=O)N1CCC[C@@H]1c1nc(-c2ccccc2)c(C(C)C)o1",
        "COc1cc(C)c([C@H](C)NC(=O)N2CCC2)cc1OC",
        "O=C(O[C@H]1CCN(c2ccccc2Cl)C1=O)c1n[nH]c(=O)c2ccccc",
        "CC(C)Cn1ncc(C(=O)NCC2(O)CCCCCC2)c1C(F)F",
        "COc1ccc(-c2noc(-c3ccc(NC(=O)c4cc(F)cc(F)c4)cc3O)n2",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "CCn1cc(C(=O)NCC2([C@H](O)c3ccccc3)CC2)c2ccccc21",
        "C[C@H]1Cc2c(C(=O)N3CCc4[nH]nc(C(F)(F)F)c4C3)n[nH]c",
    ],
    [
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "O=C1NCCN(C(=O)c2cc(C3CC3)on2)[C@H]1c1ccc(C(F)(F)F)cc1",
        "Cc1cc(S(=O)(=O)NOCC(=O)[O-])ccc1OC(C)C",
        "CC1CCN(S(=O)(=O)N[C@H]2CCN(c3ccccc3)C2=O)CC1",
        "Cc1c[nH]c(=O)n1-c1cccc(C(=O)N2CCc3c(ncn3-c3ccc(F)cc3)",
        "Cn1ccc2ccc(NC(=O)N3CC[C@H](C(C)(C)C)C3)cc2c1=O",
        "Cc1nc(C2CC2)nc(C)c1C(=O)NCC1CCC1",
        "O=C1C[C@@H](C(=O)Nc2c(F)cccc2Oc2ccccc2)c2ccccc2N1",
        "CC1(c2nc(-c3ccnc(N4CCOCC4)c3)no2)CC1",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)C",
    ],
    [
        "C[C@H](NC(=O)c1ccc(Nc2ncccn2)cc1)[C@H](O)c1ccccc1",
        "O=C(Cc1cccnc1)NCc1cn(-c2ccccc2)nc1-c1ccc(F)cc1",
        "Cc1nc2c(cc1C(=O)N[C@H](C)c1ccc3c(c1)CCC(=O)N3)c(C)nn2C",
        "Cc1ccc(Cl)c(S(=O)(=O)NC(=O)C(C)C)c1Cl",
        "CS(=O)(=O)c1ccc(NC(=O)NC2CCOCC2)cn1",
        "O=C(Nc1cccc2ccccc12)N[C@H]1CC[NH2+]C1",
        "CCOc1ccc(CNC(=O)N2CCC[C@H](C(=O)NC)C2)cc1F",
        "O=C(N[C@@H](Cc1ccccc1)C(=O)N1CCCC1)[C@@H](O)[C@@H](O)c1nc2cc",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
    ],
    [
        "CC(C)CCn1ncc(NC(=O)[C@@H]2CC23CCOCC3)c1C(C)C",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)",
        "C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1F)c1ccc(NC(=O)c2ccnc",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OC",
        "CS(=O)(=O)c1ccccc1N1CCC[C@H]1c1cccnc1",
        "Cc1nn(C)c2nc(-c3cccs3)cc(C(=O)NCc3ccccc3Cn3cncn3)c12",
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F",
        "Cc1cc(N2CCC(CO)CC2)nc(-c2cccnc2)n1",
        "COc1ccccc1OCCN(C)C(=O)c1cc(=O)[nH]c2ccccc12",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
    ],
    [
        "Cc1ccc(S(=O)(=O)Cc2nnc(C)n2C)cc1C",
        "COCC(=O)N1CCN(C(=O)c2cccc(NCc3nc(C)cs3)c2)CC1",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "COc1cccc(CNC(=O)N2CCC(C(=O)NCc3ccc(F)cc3)CC2)c1",
        "C[C@H]1C[N@@H+](C2CC2)C[C@@H]1NC(=O)N1Cc2ccc(Br)cc2C1",
        "Cc1cccc(F)c1CNC(=O)[C@H]1CC(=O)N(C2CCCC2)C1",
        "O=C([C@@H]1C[C@@H]2CC[C@H]1O2)N1CCC(c2nc(=O)[nH][nH]2",
        "O=C(NCc1ccc(C(=O)N2CCc3c(nc[nH]c3=O)C2)cc1)OCc1ccccc1",
    ],
    [
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc54)CC3)ccc",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s1",
        "Cc1nocc1NC(=O)NC[C@](C)(O)c1ccc(F)cc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H](C)",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "Cn1cc(NC(=O)N2CCOC3(CCCC3)C2)c(-c2ccccc2)n1",
        "Cc1cc(C)c(S(=O)(=O)N2CCC=C(c3cnn(C)c3)C2)s1",
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F)(F)F)cc2",
        "O=C([O-])c1cc(F)ccc1NS(=O)(=O)c1c[nH]c2ncccc12",
    ],
    [
        "CCc1nc(CNc2cccc3c2C(=O)NC3)no1",
        "Cc1ccn2c(NC(=O)c3cc(F)ccc3Cl)nnc2c1",
        "Cc1cc(NC(=O)c2nn(C)c3ccccc23)ccc1NC(=O)c1cnc2n1CCC2",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1ccccc1",
        "O=C(N[C@H]1CCc2ccc(F)cc21)c1c[nH]nc1-c1ccccc1",
        "C[C@H](Cc1cccc(Cl)c1)C(=O)N1CCCN(C(N)=O)CC1",
        "Nc1nccc([C@H]2CCCN(C(=O)c3cccc(NS(=O)(=O)c4ccc(F)c(F)",
        "Cc1cc(F)ccc1-n1ccc(C(=O)N2CCc3ccccc3[C@H]2CO)n1",
        "C[C@@H](NC(=O)N1CCc2nccnc2C1)c1cccc(Cl)c1",
    ],
    [
        "O=C([C@@H]1C[C@@H]2CCCC[C@H]2N1C(=O)c1ccc2ccccc2c",
        "CCc1cccc2c1N(C(=O)c1cc(OC)no1)CC2",
        "Cc1ccc(CNC(=O)CN2CCCC[C@@H](O)C2=O)cc1F",
        "O=C1CCCc2cc(C(=O)N3C[C@@H](c4ccccc4)[C@@H]4CCC[C@",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@@H]3C[C@H](O)c3ccc(F)",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "Cc1c(CCC(=O)N2CCN(C(=O)c3ccccc3)CC2)cnn1C",
        "CC1(C)OCC[C@H]1NC(=O)c1ccc(C(=O)[O-])cc1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O",
        "COc1ccc([C@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CCOC",
    ],
    [
        "CCCC(=O)N1CCC[C@H]1C(=O)N[C@@H]1COc2ccccc2C1",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "O=C1CCCN1Cc1ccc(C(=O)N2CCC[C@@H](N3CCCS3(=O)=O)C2)cc1",
        "COc1cccc(CN(C)C(=O)c2ccc(C(=O)[O-])cn2)c1",
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc54)CC3)c",
        "C[C@@](O)(CCc1ccccc1)C(=O)NCc1nc(-c2ccccn2)n[nH]1",
        "Cc1cc(C)c(NC(=O)[C@H]2C[C@@H]2c2ccccc2C)c(C)n1",
        "CC(C)c1ncncc1C(=O)Nc1cccc(-c2nncn2C)c1",
        "COc1ccc([C@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CCOCC2)cc1OC",
    ],
    [
        "Cc1c[nH]cc1C(=O)N1CCC(c2ccc(S(N)(=O)=O)cc2)CC1",
        "COc1cc(CCO)ccc1NC(=O)[C@H]1CC1(C)C",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
        "Cc1c(C2CC2)n[nH]c1NC(=O)c1cc(C#N)cc(N(C)C)c1",
        "Nc1nccc([C@H]2CCCN(C(=O)c3cccc(NS(=O)(=O)c4ccc(F)c(F)c4)c3)",
        "CN(Cc1ccc(F)cc1Cl)C(=O)c1cnns1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc3",
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
        "[NH3+][C@H](CC(=O)NCC(=O)NC1CC1)Cc1cc(F)c(F)cc1F",
        "NC(=O)NC[C@H]1CCCN(C(=O)NCc2ccccc2Oc2ccccc2)C1",
    ],
    [
        "C[C@@](O)(CNC(=O)[C@@H]1CCCN(C(=O)Cc2ccccc2)C1)c1c",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "O=c1c2ccc(Cl)cc2ncn1C[C@@]1(O)CCCOC1",
        "Cc1ccc(NC(=O)CCn2c(=O)[nH]c(=O)c3ccccc32)cc1NS(=O)",
        "O=C(NC[C@@H]1CC[N@H+]1C1CCOCC1)c1cc(F)c2ncccc2c1",
        "COc1ccccc1NC(=O)Cc1noc([C@@H]2Cc3ccccc3N2C(C)=O)n1",
        "Cc1cccc(C(=O)N2CCOC[C@H]2CC(=O)[O-])c1Cl",
        "CS(=O)(=O)c1ccc(F)c(C(=O)Nc2ccc(-c3nc(-c4ccccc4)n[",
        "Cc1noc([C@@H]2C[C@H](CNc3cnccn3)[C@@H](O)C2)n1",
        "O=C1Cc2cc(CCCC(=O)Nc3ccccc3N3CCCC3=O)ccc2N1",
    ],
    [
        "Cc1ccc(S(=O)(=O)NC(=O)c2ccco2)cc1C",
        "O=C1O[C@H](c2ccccc2)Cc2cc(C(=O)N3CC[C@H](c4ccccc4F)C3)c",
        "O=C1CN(C(=O)C2CCN(c3ccc4nncn4n3)CC2)CCN1",
        "OCCn1cc(Nc2ccnc(-c3ccccc3)n2)cn1",
        "Nc1nccc([C@H]2CCCN(C(=O)c3cccc(NS(=O)(=O)c4ccc(F)c(F)c4",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "C[N@H+]1CCn2nc(NC(=O)NCc3ccccc3C(F)(F)F)cc2C1",
        "O=C(NCc1ccc(C(=O)N2CCc3c(nc[nH]c3=O)C2)cc1)OCc1ccccc1",
        "O=C(Cc1cccnc1)NCc1cn(-c2ccccc2)nc1-c1ccc(F)cc1",
        "Cc1nc(C(=O)N2CC=CCC23CCOCC3)nc(N2CC[C@@H]([NH3+])C2)c1C",
    ],
    [
        "CO[C@H]1C[C@H](COc2cccnc2)[N@@H+](Cc2ccnn2C)C1",
        "Cc1cc(NC(=O)c2cccc(F)c2)sc1C(=O)N1CC(C2CCOCC2)C1",
        "COc1ccccc1CC(=O)N1CCC(CC(=O)[O-])CC1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "O=C(CC[C@@H]1CC[NH2+]C1)Nc1cc(-c2cc(F)cc(F)c2)[nH]n1",
        "O=C(Nc1cccc(Cn2nc3ccccn3c2=O)c1)N1CCC[C@H](c2cc3cccc",
        "COC(=O)Nc1ccc(NC(=O)[C@@H]2CCCN(c3cnccn3)C2)cc1",
        "O=C([C@@H]1C[C@@H]2CCCC[C@H]2N1C(=O)c1ccc2ccccc2c1)N",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4ccccc",
    ],
    [
        "O=C([O-])C1=[NH+]N(c2ccccc2Cl)C(=O)CC1",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc",
        "O=C(NCc1ccn(C2CCCC2)n1)c1cncnc1",
        "O=C(N[C@H]1CCc2ccc(F)cc21)c1c[nH]nc1-c1ccccc1",
        "COc1cc(C)c([C@H](C)NC(=O)CN2CCOC3(CCC3)C2)cc1OC",
        "C[C@H](NC(=O)c1ccc(-n2cccn2)cc1)[C@@H](C)C(=O)[O-]",
        "O=C(Nc1cccc(Cn2nc3ccccn3c2=O)c1)N1CCC[C@H](c2cc3cc",
        "O=C1Cc2cc(CCCC(=O)Nc3ccccc3N3CCCC3=O)ccc2N1",
        "Cn1c(=O)[nH]c2ccc(C(=O)NCC[C@H]3CN(c4ncnc5[nH]ncc4",
        "O=C(N[C@H]1CCCN(c2ccccc2F)C1)c1cnn2cccnc12",
    ],
    [
        "Cn1c(-c2n[nH]c(=O)c3ccccc23)nnc1N1CC[C@@H](c2ccc(C(F)(F)F",
        "CN(C)C(=O)N1CCN(C(=O)c2ncnc3ccsc23)CC1",
        "C[C@H](O)C(=O)N1CCN(C(=O)c2cn(Cc3cccs3)nn2)CC1",
        "CO[C@H]1C[C@@H](N(C)S(=O)(=O)c2ccc(OCC(=O)[O-])c(Cl)c2)C1",
        "CC(C)[C@@H](O)CC(=O)N1CC=C(c2c[nH]c3ncccc23)CC1",
        "C[C@@H](C(=O)NCc1ccc(C(=O)N2CCOCC2)cc1)N1CCc2ccccc21",
        "O=C(O[C@H]1CCN(c2ccccc2Cl)C1=O)c1n[nH]c(=O)c2ccccc12",
        "O=C1NCCN(C(=O)c2cc(C3CC3)on2)[C@H]1c1ccc(C(F)(F)F)cc1",
        "CCc1nc([C@@H]2CCCN2C(=O)Nc2ccncc2)no1",
        "O=C([O-])c1coc(C[N@@H+]2CC=C(c3ccc(F)cc3)CC2)n1",
    ],
    [
        "COc1cc(F)cc(CNC(=O)N2CC[C@@]3(C2)C(=O)Nc2ccccc23)c1",
        "CO[C@H]1C[C@@H](N(C)C(=O)NC[C@@H]2CCCOC2)C1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c",
        "CC1(C)C[C@@H](NC(=O)Nc2nnc(C(C)(C)C)s2)CCO1",
        "O=C(c1ccc2c(c1)CCCC2)N1CCCC[C@H]1c1nc(=O)[nH][nH]1",
        "O=C([O-])[C@@H]1CCN(S(=O)(=O)c2cccc(Cl)c2)CC1(F)F",
        "Cc1cccc(-c2nnc([C@H](C)[N@H+](C)CC3CCOCC3)o2)c1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s1",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@H]3C[C@H](O)c3ccc(F)cc3",
        "O=C1Nc2ccccc2[C@@H]1C1CCN(C(=O)c2cccc(N3C(=O)c4cccc",
    ],
    [
        "C[C@]1(c2cccc(-c3noc([C@H]4C[C@H]4c4ccc(F)cc4)n3",
        "C#Cc1cc(F)c(NC(=O)C(=O)N2CC=C(c3c[nH]c4ncccc34)C",
        "Cn1cc(-c2cncc(C(=O)N[C@H]3CC[C@H](O)CC3)c2)cn1",
        "CCOc1cn(-c2ccccc2)nc1C(=O)N1CCN(c2ncccn2)CC1",
        "O=C(CCc1nc2cccnc2[nH]1)N(Cc1ccccc1)C[C@@H](O)c1c",
        "Cc1nn(Cc2ncc(-c3ccccc3)o2)c(C)c1[C@@H]1COCCN1C",
        "O=C(NCC1([C@H](O)c2ccccc2)CC1)c1cc(Cl)cc2cccnc12",
        "NC(=O)[C@H](Sc1nc2c(cnn2-c2cccc(Cl)c2)c(=O)[nH]1",
        "O=C1CCCc2cc(C(=O)N3C[C@@H](c4ccccc4)[C@@H]4CCC[C",
        "Cn1cc(S(=O)(=O)N[C@@H]2CCc3c(Cl)cccc32)cn1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c(C)c1",
        "O=C(NCc1ccccc1)N[C@@H]1CCCC[C@@H]1CO",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "C[C@@H](C(=O)NCc1ccc(C(=O)N2CCOCC2)cc1)N1CCc2ccccc21",
        "COc1ccc(C[NH2+]Cc2nnc3n2CCOCC3)c(Cl)c1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)CC1",
        "COc1nc(C)cc(N(C)CC2(O)CCCC2)n1",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2ccccc2)c1",
    ],
    [
        "O=C(c1cccnc1C(F)(F)F)N1CCS(=O)(=O)CC1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "Cc1n[nH]c(-c2ccc(NC(=O)CN3C(=O)N[C@](C)(c4ccc5ccccc5c4)C3=",
        "O=C1CCCc2cc(C(=O)N(CCCO)Cc3cccc(Cl)c3)ccc2N1",
        "CN1CC[C@@H](NC(=O)Nc2cnn(-c3ccccc3Br)c2)C1=O",
        "Cc1cc(C)cc(C(=O)N2CCC[C@H](C(=O)NCc3cccc([C@@]4(C)NC(=O)NC",
        "CCOc1ccccc1CNC(=O)[C@@H]1C[C@@H](C)[C@@H](C(=O)[O-])O1",
        "Cc1nnc(-c2cccc(C(=O)N3CC(O)C3)c2)o1",
    ],
]


- Experiment:
    name: Enrich 5(RDKit2D)

    dataset: datasets/DDS10_RDKIT2D.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]
