- unique_initial_sample:
    seeds: [
    [
        "O=C(CCl)NCc1cnccn1",
        "OC[C@H]1C[C@](O)(c2ccc(F)cc2)[C@@H](c2ccc(F)cc2)O1",
        "Cc1ccc(S(=O)(=O)N2Cc3ccc([N+](=O)[O-])cc3C2)cc1",
        "CC(=O)Nc1ccc(S(=O)(=O)[C@H](Cl)c2ccccc2)cc1",
        "CCCOC(=O)NCCSC(=O)OCCC",
        "CC(=O)NC(CCC(=O)c1ccc(Cl)cc1)(C(=O)[O-])C(=O)[O-]",
        "C[C@@H](O)COc1ccccc1P(c1ccccc1)c1ccccc1",
        "CCOc1cc([C@H](O)[C@@H](O)c2ccc(O)c(OCC)c2)ccc1O",
        "COc1ccccc1[C@@H](O)c1cnc(C)n1Cc1ccccc1",
        "CC(=O)Nc1ccc(S(=O)(=O)F)cc1Cl",
    ],
    [
        "COc1c(O)cc(Br)c(C=O)c1N",
        "CCCCN1C(=O)NC(=O)[C@@]1(C)c1ccccc1",
        "Nc1cccc(-c2nc3ccc4c(O)cc(S(=O)(=O)[O-])cc4c3s2)c1",
        "COC(=O)[C@@]1(Cc2ccc3c(c2)CCC3)Cc2ccccc2[C@H]1O",
        "c1c2c(cc3c1OCN(C1CC1)C3)OCN(C1CC1)C2",
        "CCCCc1cc(O)ccc1O",
        "CCOc1cc(CC[NH2+]C)c2c(ccc3ccc(OC)c(O)c32)c1O",
        "O=C(CSc1ncc[nH]1)c1ccc(Br)cc1",
        "CC[NH+](CC)Cc1cc2c(cc1O)CC[C@@H]1[C@@H]2CC[C@]2(C)C(=O)CC[C@@H]12",
        "Cc1ccc(C(=O)C[C@H](c2ccc(C)cc2)C2C(=O)NC(=O)NC2=O)cc1",
    ],
    [
        "CCN(CC)/[NH+]=C/C[C@H](C)Nc1ccnc2cc(Cl)ccc12",
        "COc1ccc2nc(C)c(COC(C)=O)cc2c1",
        "Oc1ccc([C@H]2Oc3c(ccc(O)c3O)[C@@H](O)[C@H]2O)cc1O",
        "NC(=O)c1c(N)nn2c(-c3ccccc3)cc(-c3ccccc3)cc12",
        "O=CNc1cc(Br)cc2c1[nH]c(=O)c1ccccc12",
        "C[C@H](NNC(=S)N1CCN(c2ccccn2)CC1)c1cc2ccccc2cn1",
        "C=CC(C)(C)c1cc(O)c2oc3c(O)cccc3c(=O)c2c1[O-]",
        "O=C1c2ccccc2C(=O)N1Cc1cc([N+](=O)[O-])ccc1Cl",
        "COc1cccc(P(c2cccc(OC)c2)c2cccc(OC)c2)c1",
        "COc1cccc2c1c(C(=O)C(=O)Nc1cc[nH]n1)cn2Cc1ccc(F)cc1",
    ],
    [
        "CC(=O)NC1=C([NH3+])C(=O)c2ccccc2C1=O",
        "O=C1C=C(c2ccccc2)O[C@H]1[C@@H]1Sc2ccccc2NC1=O",
        "CCc1c(C)c2ccc(O)c(N3C(=O)C(=O)N(c4ccccc4)C3=O)c2oc1=O",
        "COc1ccc(CC2=[N+](C)CCc3cc(OC)c(OC)cc32)cc1OC",
        "O=c1c(CSc2c(-c3ccccc3)c(=O)c2=O)c(-c2ccccc2)c1=O",
        "Cc1ccc(NCC[NH+](C)C[C@H](C)O)c2c(=O)c3ccc(Cl)cc3sc12",
        "CC1(C)O[C@@H]1C(=O)[O-]",
        "COc1cc([C@@H]2c3cc(O)c(OC)cc3C[C@H]3C(=O)OC[C@@H]23)ccc1O",
        "O=C1OC[C@@H](Cc2ccc3c(c2)OCO3)[C@H]1Cc1cccc(O)c1",
        "COc1ccc(CCc2nccn2C)cc1OC",
    ],
    [
        "O=C(Nn1c(-c2ccccc2)nc2ccccc2c1=O)c1ccc([N+](=O)[O-])cc1",
        "CC[C@@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3ccc(C=O)cc3nc2-1",
        "CCOC(=O)/C=C/c1ccc(N)cc1",
        "O=c1[nH]nc2c3cccc4cccc(c5ccc([O-])c1c52)c43",
        "COc1ccc(-c2nn(CCO)c(=O)c(C#N)c2-c2ccc(OC)cc2)cc1",
        "COc1ccc(-c2nc3ccc(C)cc3c3c2c(=O)n(C)c(=O)n3C)cc1",
        "COc1ccc2c(c1O)C[NH2+]C[C@@H]2c1ccc(O)c(O)c1",
        "CCOC(=O)N[C@H]1[C@@H]2OC(C)(C)O[C@@H]2O[C@H]1CC(=O)OC",
        "CCOC(=O)[C@H]1Cc2c(cc3c4c(cccc24)N(C(C)=O)C3)N(C)C1",
        "O=C(Nc1ccccc1CO)c1ccccc1",
    ],
    [
        "CC(=O)Nc1ccc(C(=O)NN2C(=O)[C@@H](Cl)[C@H]2/C=C/c2ccccc2)cc1",
        "COc1ccc(C2=[NH+]N[C@H](c3ccc(-c4ccc(OC)cc4[N+](=O)[O-])o3)C2)cc1",
        "NC(=O)CNC(=O)c1ccccc1SC(=O)c1ccccc1C(F)(F)F",
        "O=S(=O)([O-])CC[C@@H](O)S(=O)(=O)[O-]",
        "Cc1c([N+](=O)[O-])ccc2cccnc12",
        "CCn1c(=O)c2c(ncn2CC)n(CC)c1=O",
        "CCn1c(Cl)c(/C=[NH+]\\Nc2ccc([N+](=O)[O-])cc2)c2ccccc21",
        "C=C1C(=O)O[C@H]2/C=C(\\C)CC/C=C(\\C)C[C@H](OC(=O)/C(=C/CO)CO)[C@@H]12",
        "O=c1oc2ccccc2cc1-n1nnc2cc([N+](=O)[O-])ccc21",
        "COc1ccc(/C=C2\\Oc3cc(O)ccc3C2=O)cc1O",
    ],
    [
        "CCn1c(=O)c(C#N)c2n(CC)c3cc(C)c(C)cc3n2c1=O",
        "Oc1ccc2c(c1)OC[C@@]1(O)Cc3cc(O)c(O)cc3[C@H]21",
        "NC(=O)c1cccc(NC=O)c1",
        "Oc1nc(S)nc2nc3c4cccnc4c4ccccc4c3nc12",
        "COc1ccc([C@@H](O)C(=O)c2nc3ccc([N+](=O)[O-])cc3nc2O)cc1",
        "C=C(Br)C[NH2+]CCCCCC",
        "CCOC(=O)c1[nH]c(CO)c(C(=O)OCC)c1C",
        "O=C1C=CC[C@H](/C=C/C[C@@H](O)C[C@H](O)/C=C/c2ccccc2)O1",
        "CCC[C@H]1OCCN1CC",
        "CCSC[C@H]1C[C@](O)(c2c(C)nn(Cc3ccccc3)c2C)C(=O)O1",
    ],
    [
        "Cc1c2ccccc2c(CSC[C@H]([NH3+])C(=O)[O-])c2ccc3ccccc3c12",
        "O=C1c2ccccc2[C@](O)(c2ccc(O)cc2)c2ccc(O)cc21",
        "COc1ccc([C@H]2COc3cc(O)c(O)cc3C2)cc1OC",
        "CC(=O)Nc1ccc(S(=O)(=O)c2ccc(C)cc2)cc1",
        "COc1ccc(-c2nnc(-c3c(C)n(C)n(-c4ccccc4)c3=O)o2)cc1",
        "COc1cc2cccc(O)c2cc1OC",
        "CC1=C(C(=O)Nc2ccc(F)c(Cl)c2)[C@@H](c2cccc(O)c2)NC(=O)N1",
        "CCOC(=O)[C@@H](C/[N+]([O-])=C/c1ccccc1)NC(C)=O",
        "COc1cc2c3c(c4cc(OC)c(OC)cc4c2cc1OC)C[NH+]1CCC[C@H]1C3",
        "CCN(CC)C(=O)Nc1cccc(O)c1",
    ],
    [
        "CNC(=O)NN",
        "O=C([O-])/C(=C\\c1ccc2c(c1)OCO2)[C@@H](CO)Cc1ccc2c(c1)OCO2",
        "C[NH+]1C(C)(C)CC(O)(C(=O)[O-])CC1(C)C",
        "Nc1ncc2[nH]c(=O)[nH]c2n1",
        "C[C@]12CC[C@@H]3c4cc(O)c(O)cc4CC[C@H]3[C@@H]1CC[C@@H]2O",
        "CCOC(=O)N1CCc2c(ccc3cc(OC)ccc23)[C@@H]1CCO",
        "CCC(=[NH+]\\NC(=S)NC)/C(C)=[NH+]\\NC(=S)NC",
        "Cc1ccccc1C(=O)NNC(=O)c1cccc2ccccc12",
        "CCOc1ccc(N)c(SCC(=O)[O-])c1",
        "Cc1ccc2c(c1)nc1c([n+]2[N-]C(=O)CC[NH+](C)C)-c2cccc3cccc-1c23",
    ],
    [
        "CCOc1nc(C)cc(C(=O)[O-])c1C#N",
        "COc1ccccc1/C=C(/C)C(C)=O",
        "Cc1nn(C(=O)c2ccncc2)c2c1[C@H](c1ccccc1)SC(=N)N2",
        "O=C(c1coc(=O)c(-c2ccc(F)cc2)c1)c1ccccc1O",
        "O=C1c2c(O)ccc(Cl)c2C(=O)c2c(O)ccc(Cl)c21",
        "C1CSC(N2CCOCC2)=N1",
        "CCO[N+]([O-])=C1C=C(C(C)(C)C)C(=O)C(C(C)(C)C)=C1",
        "COc1cccc([C@@H]2CCCC[C@@H]2O)c1",
        "Oc1cc2c(cc1O)[C@@H]1c3ccc(O)c(O)c3OC[C@]1(O)C2",
        "O=C([O-])c1ccc(-c2c3ccc(=O)cc-3oc3cc(O)ccc23)cc1",
    ],
    [
        "CCOC(=O)Cn1c(=O)c(-c2ccccc2NC(C)=O)nc2ccccc21",
        "NC(=O)CCNC(=O)c1ccccc1SC(=O)c1c(F)cc(F)cc1F",
        "N#C/C(=C\\Nc1ccccn1)C(=O)C1CC1",
        "O=c1c(-c2cccc(O)c2)coc2cc(O)c(O)cc12",
        "C[C@@]1(CCCOc2cccc(N)c2)[NH+]=C(N)[NH+]=C(N)N1c1ccccc1",
        "CC1(C(Cl)(Cl)Cl)C=CC(=[NH+]OCC(=O)[O-])C=C1",
        "CC(=O)Nc1ccc(CCNC(=O)c2ccc3ccccc3c2O)cc1",
        "CCO/[NH+]=C(\\C)C(=O)NNS(=O)(=O)c1ccc(C)cc1",
        "O=C(C[NH+](Cc1ccccc1)Cc1ccccc1)NC(=O)c1ccccc1",
        "Cc1ccc(/C=[NH+]/NC(N)=[NH2+])cc1",
    ],
    [
        "O=C(c1coc(=O)c(-c2ccc(F)cc2)c1)c1ccccc1O",
        "O=C1Nc2ccc(F)cc2/C1=C/c1cc(-c2ccc3c(c2)OCO3)n[nH]1",
        "COc1cccc(C2=C(c3cn(C)c4ccccc34)C(=O)NC2=O)c1",
        "CS(=O)(=O)Oc1ccccc1C(=O)[O-]",
        "COc1ccc(C[C@H](CO)NC(=O)c2ccccc2)cc1",
        "C[C@H](NC(=O)NCCCl)c1ccsc1",
        "COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)cc2)ccc1O",
        "CC(C)[C@H](C)C1=CC(=O)C=CC1=O",
        "CC1=C/C(=C/[C@@](C)(O)C[C@H]2C=C(CCC(C=O)=C(C)C)C(=O)O2)OC1=O",
        "NC(=O)c1ccc[n+](Cc2ccccc2)c1",
    ],
    [
        "O=C1N[C@@](O)(c2ccccc2)c2ccccc21",
        "COc1cc(O)c(C(=O)[C@@H]2Cc3ccccc32)c(OC)c1",
        "COc1cc([C@H]2Oc3c(OC)cc(/C=C/C(N)=O)cc3[C@@H]2C(N)=O)ccc1O",
        "CS(=O)(=O)Nc1ccc(-c2ccc3c(NC(=O)C4CC4)n[nH]c3c2)cc1",
        "O=C([O-])c1nc2ccccc2c2ncccc12",
        "CC1=C[C@H]2C[C@@H](C)[C@@H](CO)/C=C(\\C)[C@H](O)C(=O)/C=C(\\C)CC[C@H]12",
        "CCOC(=O)N/[NH+]=C/c1ccc(OC)c(O)c1",
        "COc1cc2c(cc1O)C[NH2+]C[C@H]2c1ccc(O)c(C)c1",
        "CN(C)/C=N/c1ccc(F)cc1",
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)NCc1ccc(C(F)(F)F)cc1",
    ],
    [
        "CCCCC=C1C(=O)NC(=S)NC1=O",
        "CC1(C)CCC[NH+]1CCOC(=O)[C@H](c1ccccc1)[C@H]1C=CCC1",
        "CCCCOC(=O)[C@@H]([NH3+])Cc1ccc(OC)c(Cl)c1",
        "COc1c(C(C)C)cc(O)c2c1CC[C@H]1C(C)=C(C(=O)[O-])CC[C@]21C",
        "C[C@]12CC[C@@H]3c4ccc(O)c(N)c4CC[C@H]3[C@@H]1CC[C@@H]2O",
        "CCCC(=O)Nc1ccc(C)cc1",
        "CC1(C)OC[C@H]([C@@H](O)c2nc3ccccc3nc2C(=O)Nc2ccccc2N)O1",
        "O=c1c(O)c(-c2cc(O)c(O)c(O)c2)oc2cc(O)cc([O-])c12",
        "CCOC(=O)NC(=O)CBr",
        "O=C1c2c(O)ccnc2-c2nccc3c2c1nc1ccccc13",
    ],
    [
        "C[NH2+]C[C@@H](OCCc1ccccc1)c1ccc(O)c(O)c1",
        "COc1ccc([C@@H](CNC(C)=O)c2ccccc2)cc1OC",
        "Cc1cccc(CNc2cccc(C)n2)n1",
        "N#CCN1CCCN(CC#N)C1",
        "CCCC(=O)c1c(O)cc(O)c2c1C(=O)c1cc(OC)cc(O)c1C2=O",
        "C[C@H](c1c[nH]c2ccccc12)[C@@H](NC(=O)Nc1cccc2ccccc12)C(=O)[O-]",
        "CCn1cc(C(=O)[O-])c(=O)c2ccc(C)[n+](C)c21",
        "CC(=O)C(=Cc1cccc([N+](=O)[O-])c1)C(C)=O",
        "Cc1cc(O)c2c(c1)C(=O)C(c1c(C)cc3c(c1O)C(=O)[C@@H]1O[C@@H]1C3=O)=CC2=O",
        "CCc1nn2c(=O)nc(SC)nc2s1",
    ],
    [
        "O=C(/C=C/c1ccc(O)c(O)c1)c1cc(O)cc(O)c1",
        "CC(=O)Nc1nc(-c2nnc(S)n2-c2ccc(Cl)cc2)cs1",
        "O=C1COc2cc(N3CCN(c4cccc(C(F)(F)F)c4)CC3)ccc2N1",
        "CC(=O)Nc1ccc(S(=O)(=O)CCBr)cc1",
        "C=CCC1(O)c2cccc(O)c2C(=O)c2c(O)cccc21",
        "O=C([O-])c1ccc(Oc2ccccc2)cc1",
        "CCOC(=O)C1CCc2ccccc2CC1",
        "O=c1cc(-c2ccc(O)cc2)oc2ccccc12",
        "O=C(c1ccccc1)[C@H](c1ccccc1)[C@]1(O)C(=O)Nc2ccc([N+](=O)[O-])cc21",
        "O=C(CCc1ccc(O)c(O)c1)NCCc1cc(O)c(O)c(O)c1",
    ],
    [
        "CN[C@H](C#N)c1ccc(OC)cc1",
        "O=C(Oc1ccccc1)c1cc2ccccc2oc1=O",
        "COc1ccc2c(c1)C(=O)c1c-2n(CCC[NH2+]CCO)c(=O)c2ccccc12",
        "Cc1ccccc1-n1c(C)nc2cc(NC(N)=S)ccc2c1=O",
        "Nc1nccc2snnc12",
        "COc1ccc2c(C[NH2+]CCCCO)cc3cc4c(cc3c2c1)OCO4",
        "O=C1C2=C(C(=O)c3ncccc31)[C@H]1C=C[C@H]2CC1",
        "O=C(/C=C/c1ccc(O)c(O)c1)c1ccc(O)c(O)c1O",
        "NC(=O)N(CCc1ccccc1)N=O",
        "COC(=O)c1c(O)ccc2c1[C@@]1(Cc3ccccc3C1=O)[C@H](O)O2",
    ],
    [
        "CCCC(=O)c1c(O)cc(O)c2c1C(=O)c1cc(OC)cc(O)c1C2=O",
        "O=C1CS[C@H](c2cc([N+](=O)[O-])ccc2Cl)N1c1nncs1",
        "O=C([O-])c1cccc(N2C(=O)CSC2=S)c1",
        "CCOc1ccc(C2[N@]3CCC[N@H+]2CC3)cc1OC",
        "CCOc1cc([C@H](O)[C@@H](O)c2ccc(O)c(OCC)c2)ccc1O",
        "CC(C)CCC(=O)Nc1ccc(-c2ccc(C(=O)[O-])cc2)cc1",
        "O=c1c2ccccc2sc2c1c(N(CCO)CCO)cc1ccccc12",
        "Cc1nc2[nH]nc(N)c2c(C)c1Br",
        "O=C1C[C@H](c2ccc(O)c(O)c2)Oc2cc(O)cc(O)c21",
        "O=C1OC[C@@H](Cc2ccc(O)c(O)c2)[C@H]1Cc1ccc(O)c(O)c1",
    ],
    [
        "Cc1ccccc1C(=O)NNC(=O)c1cccc2ccccc12",
        "CCOC(=O)[C@]1(C(N)=O)O[C@]1(c1ccc(Cl)cc1)c1ccccc1Cl",
        "OCC[NH+]1CCN(CCCN2c3ccccc3CCc3ccccc32)CC1",
        "CCOC(=O)c1ccc(=O)n(Cc2ccccc2)c1",
        "CC(C)(O)[C@@H]1CCCC[C@H]1Cl",
        "CC(=O)Oc1ccccc1C(=O)Sc1ccccc1C(=O)NCC(N)=O",
        "c1ccc2c(C[NH+]3CCCCC3)cccc2c1",
        "CC(=O)CC(=O)Nc1ccc(Cc2ccc(NC(C)=O)cc2)cc1",
        "O=C([O-])CNC(=O)CCl",
        "O=C(/C=C/c1ccccc1)C1=C([O-])C(=O)O[C@H]1c1ccccc1",
    ],
    [
        "CC(=O)Nc1ccc(CO[C@H](O)C[NH+]2CCCCC2)cc1[N+](=O)[O-]",
        "NC(=O)COc1c(Cl)cc(Cl)cc1Cl",
        "O=C(Nc1ncnc2c1ncn2[C@@H]1C[C@@]2(O)C[C@@H]3C[C@]3(O)[C@H]2O1)c1ccccc1",
        "O=c1c(O)c(-c2ccc(O)c(O)c2)oc2cc(O)ccc12",
        "COc1cc2c(c3oc4c(O)cccc4c(=O)c13)C[C@H]([C@@](C)(O)CCl)O2",
        "C[NH+]1CCN(C(=O)CCNC(=O)Cc2ccc(C(=O)c3ccccc3)cc2)CC1",
        "COc1ccc(CC[NH2+]C2=CC(=O)CC2)cc1OC",
        "C[NH+](CCCl)C[C@@H]1CSCO1",
        "O=C1NC(=O)/C(=C/c2ccc(Cl)cc2Cl)N1",
        "COC(=O)c1cc(-c2ccc(N)cc2)c2c(=O)n(-c3ccccc3)[nH]c2n1",
    ],
    [
        "N#Cc1sc(=S)n(-c2ccccc2)c1N",
        "O=C1OCC2=C1[C@@H](c1cccc(Cl)c1)c1cc3c(cc1N2CCO)OCO3",
        "Nc1nc(=O)c(CCCNc2ccccc2)c(-c2ccccc2)[nH]1",
        "C=Cc1c(C)cc(C)cc1C",
        "CN(C)c1nc(Oc2nc(N(C)C)nc(N(C)C)n2)nc(N(C)C)n1",
        "COc1c2c(c(OC)c3c1C(=O)c1cccc(O)c1C3=O)CC[C@](O)(C(C)=O)C2",
        "O=C1c2ccccc2[C@@]2(O)c3cc4ccccc4cc3O[C@]12O",
        "Cc1cc(O)c2cc(Cc3ccc(N)cc3)ccc2n1",
        "C[NH+](C)Cc1cc(Cl)ccc1O",
        "O=NN(CC(=O)[O-])Cc1ccccc1",
    ],
    [
        "N#C/C(=C\\c1ccc(O)c(O)c1)C(=O)NCc1cccc(C(F)(F)F)c1",
        "O=C([O-])c1cc(Cc2cc(Cl)c(O)c(C(=O)[O-])c2)cc(Cl)c1O",
        "COc1cccc2oc([N+](=O)[O-])cc12",
        "Cn1cnc(C(N)=S)c1N",
        "C[NH2+]C1(c2ccc(F)cc2)CCCCC1",
        "CC[C@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(O)c(O)cc3nc2-1",
        "O=C(c1ccc([N+](=O)[O-])cc1)c1ccc(O)cc1O",
        "Cc1c2ccccc2c(CSCC[C@H]([NH3+])C(=O)[O-])c2ccc3ccccc3c12",
        "COc1ccc(S(=O)(=O)N(CC(=O)[O-])c2ccccc2)cc1",
        "O=C1c2cccc(O)c2C(=O)c2c1ccc(O)c2O",
    ],
    [
        "O=c1cc(CC(O)(c2ccccc2)c2ccccc2)cc[nH]1",
        "O=C1c2ccccc2C(=O)c2c3c(cc(O)c21)N[C@@H]1CCCC[C@@H]1N3",
        "CN(C)C(=O)OCCOc1ccc(Cl)cc1",
        "O=C(OCCO)N1CC[NH+](CCO)CC1",
        "S=C(N/[NH+]=C(\\c1ccccc1)c1ccccn1)SCc1ccccc1",
        "Cc1cc(Cc2cc(C)c(O)c(CO)c2)cc(CO)c1O",
        "C/C(=[NH+]/C(C)(C)C)N1CCCCC1",
        "O=C(Cc1ccccc1)Nn1c(-c2ccccc2)nc2ccccc2c1=O",
        "NC(=O)N[C@H]1C[C@@H]1c1ccc(Cl)c(Cl)c1",
        "O=C1CNc2cc(N3CCN(c4cccc(C(F)(F)F)c4)CC3)ccc2N1",
    ],
    [
        "COc1cc(O)c2c(c1)O[C@@H](c1ccc(OC)c(O)c1)CC2=O",
        "Cc1ncc(C(=O)[O-])s1",
        "CC(=O)Nc1ccc(/C=C/C(=O)c2ccc([N+](=O)[O-])cc2)cc1",
        "O=NN(CCCl)C(=O)Nc1ccc(CC(=O)[O-])cc1",
        "CC(C)=CC[C@@H](OC(=O)CC(C)(C)O)C1=CC(=O)c2c(O)ccc(O)c2C1=O",
        "O=C(/C=C\\c1ccc(O)c(O)c1)c1ccccc1O",
        "COc1cc2ccccc2[n+](C)c1-c1ccccc1F",
        "Nc1nc(N)c2c(ccc3ccc(Cl)cc32)n1",
        "[O-][n+]1cc[n+]([O-])c2c3ccccc3ccc21",
        "CC[C@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3cc(Cl)ccc3nc2-1",
    ],
    [
        "CCOC(=O)/C=C1\\Nc2ccccc2C(c2ccccc2)=[NH+][C@H]1OC(C)=O",
        "COc1ccc(NC(=O)/C(C#N)=C/c2ccc(O)c(O)c2)cc1O",
        "Cc1c(C)c(C)c(C[NH+]2CCCC2)c(C)c1C",
        "C[S+](C)CCO",
        "O=C1N=C(N[C@H](CO)Cc2ccccc2)S/C1=C\\c1ccc2ncccc2c1",
        "Cc1[nH]c(N)nc(=O)c1CCCNC(=O)c1ccc(N)cc1",
        "O=C(NN1C(=O)[C@H](Cl)[C@@H]1c1ccccc1Cl)c1ccccc1O",
        "CC(=O)O[C@@H]1CCCc2c(O)c3c(c(O)c21)C(=O)c1ccccc1C3=O",
        "C[C@H](Oc1ccc2cc(C(=O)c3ccccc3)c(=O)oc2c1)C(=O)[O-]",
        "COc1cc([O-])c2c(=O)c(O)c(-c3ccc(O)c(O)c3)oc2c1",
    ],
    [
        "COc1ccc([C@@H]2OC[C@H]3O[C@@H](OCc4ccccc4)[C@H](O)[C@@H](O)[C@@H]3O2)cc1",
        "CCOc1cc(NC(C)=O)ccc1C(=O)NNC(=O)/C=C/c1ccccc1",
        "N#Cc1cccc(F)c1",
        "Cc1cc2ccccc2nc1Cl",
        "CC[C@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3ccc(C(=O)[O-])cc3nc2-1",
        "Cc1ccc(N2CC[NH+](C[C@H](O)COc3ccccc3)CC2)cc1",
        "COC(=O)c1ccc([C@H]2SCC(=O)N2NC(=O)[C@@H](O)c2ccccc2)cc1",
        "COc1ccc(/C=C2/SC(=O)NC2=O)cc1OC",
        "O=S(=O)(NCc1ccco1)c1ccc(F)cc1",
        "O=c1oc2c(cc1O)oc(=O)c1cc(O)c(O)c(O)c12",
    ],
    [
        "O=c1[nH]c(=O)ss1",
        "CC[C@]1(O)C(=O)OCc2c1cc1n(c2=O)Cc2cc3ccc(O)cc3nc2-1",
        "Cc1ccccc1C(=O)[C@@H]1CCCCC1=O",
        "COc1cc(CCl)cc(OC)c1OC",
        "CCNc1nc2c(ccc3c(C)c(CC)c(=O)oc32)o1",
        "COc1ccccc1[C@@H](C)c1ccc2ccccc2c1C(=O)[O-]",
        "Cc1nn(C(=O)c2ccccc2O)c2c1[C@H](c1ccc(O)cc1O)SC(=N)N2",
        "O[C@@H]1OC[C@H](Cc2ccccc2)[C@@]1(O)Cc1ccccc1",
        "COc1ccc2c(c1)OC/C(=C\\c1ccc([N+](=O)[O-])o1)C2=O",
        "CCOC(=O)/C=C/c1ccc2c(c1)O[C@@H](c1ccc(O)c(OC)c1)[C@H](CO)O2",
    ],
    [
        "O=C(NC(=O)c1cc(-c2ccccc2)n[nH]1)c1ccccc1",
        "Cc1cc(Cl)c(O)c([C@]2([C@@H](O)c3ccc(O)cc3)NC(=S)NC2=O)c1",
        "Cn1c2c(c3ccccc31)CCN(CCCC[NH+]1CCCCC1)C2=O",
        "CC(=O)CC(=O)OC[C@H]1COCO1",
        "O=c1[nH][nH]c(=O)c2c1nc(SCc1ccccc1)n2Cc1ccccc1",
        "CCCCCCOc1ccccc1CO",
        "CCc1ccc2c(c1)N(CCO)C1=C(C(=O)OC1)[C@H]2c1ccccc1",
        "CCOC(=O)CNC(=O)Oc1cccc2cccnc12",
        "CCOC(=O)C1=CN(Cc2ccccc2)[C@H]2O[NH+]=C(c3ccc(Cl)cc3)[C@@H]2C1",
        "COc1cc(NC(C)=O)ccc1C(=O)NN1C(=O)[C@@H](Cl)[C@H]1c1ccco1",
    ],
    [
        "CC(=O)c1cc(=O)[nH]c(=O)[nH]1",
        "O=C(c1nc2ccccc2nc1O)[C@H](O)c1ccccc1",
        "c1ccc(/C(=[NH+]\\[NH+]=c2\\[nH]c3ccccc3s2)c2ccncc2)cc1",
        "C=C[C@@]1(C)C[C@]2(C=C(CO)[C@H](O)O2)Oc2c1c(=O)oc1cccc(C)c21",
        "O=C1NC(=O)C(c2c[nH]c3ccccc23)=C1c1c[nH]c2ccccc12",
        "O=C1NCc2nnn(Cc3ccccc3)c2N1",
        "Nc1ccc(/N=N/c2ccc3nccc(N)c3c2)c(N)n1",
        "OCCCCC#Cc1ccccc1C#Cc1cccc(O)c1",
        "COc1cc2c(c(O)c1OC)C(=O)[C@H](Cc1ccc(O)cc1)CO2",
        "CC(C)(CC(=O)[O-])NC(=O)CN",
    ],
    [
        "O=C1OC[C@@H](Cc2ccc3c(c2)OCO3)[C@H]1Cc1cccc(O)c1",
        "O=c1c(OC/C(=[NH+]/O)c2ccccc2)c(-c2ccccc2)oc2ccccc12",
        "CC(=O)Nc1ccc(C(=O)NN2C(=O)[C@@H](Cl)[C@H]2/C=C/c2ccccc2)cc1",
        "CC(=O)N[C@H](CSCc1c2ccccc2c(C)c2ccccc12)C(=O)[O-]",
        "Cc1ccc(C(=O)C[N+]2(C)CCOCC2)cc1",
        "C1CCC[NH+](CCN2CCOCC2)CCC1",
        "C=C1C[C@@](Cn2cc(C)c(=O)[nH]c2=O)(c2ccc(-c3ccccc3)cc2)OC1=O",
        "O=C([O-])/C(=C\\c1cccc(Br)c1)c1ccccc1",
        "C=C(C)[C@H]1C[C@@H]2O[C@]2(C)[C@@H](O)C1",
        "O=[N+]([O-])c1cc/c(=[NH+]\\[NH+]=C/c2ccc(O)c(S(=O)(=O)[O-])c2)[nH]c1",
    ],
]


- Experiment:
    name: Enrich 5(RF MQN padre greedy)

    dataset: datasets/DTP_MQN.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy
        use_pairwise: True

    metrics: 
        names: [top-k, top-k-acquired]
        k: [1320]
