- unique_initial_sample:
    seeds: [
    [
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
        "NC(=O)c1ccc(C(=O)N2CCC[C@H](Cn3ccnn3)C2)nc1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc3n2)c(C)o1",
        "Cc1csc(N2CCN(C(=O)c3ccc(C(=O)NC4CC4)cc3)C[C@H]2C)n1",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)CC1)C2=O",
        "O=C(Nc1cccnc1)c1cccc(S(=O)(=O)N2CCCCC2)c1",
        "Cc1cc([N+](=O)[O-])c(C)c(S(=O)(=O)N(C)[C@@H]2C[N@H+]3CC[C@@H]2CC3)c1",
        "Cc1ccc(C(=O)N2CC[C@H](c3cc(O)[nH]n3)C2)cc1",
        "Cc1cccc([C@@H]2CCCN2C(=O)NCc2ccc(S(C)(=O)=O)cc2)n1",
        "Cc1ccc(C[C@@H](C)NC(=O)N2CCS(=O)(=O)CC2)s1",
    ],
    [
        "O=C([O-])c1cccc(CS(=O)(=O)N2CC[C@H](O)C2)c1",
        "O=C(CCc1cccc(Br)c1)N[C@H]1C[C@H](Cn2ccnc2)C[C@@H]1O",
        "Cc1ccccc1CNc1cc(C(N)=O)ccc1Cl",
        "C[C@@](O)(CNC(=O)[C@@H]1CCCN(C(=O)Cc2ccccc2)C1)c1cc",
        "Cc1nc([C@H](NC(=O)[C@H]2C[C@H]2c2ccc(C(F)(F)F)cc2)c",
        "O=C(N[C@H]1C[C@@H](Cn2ccnc2)C[C@H]1O)c1ccc2ccccc2c1",
        "COC[C@@H]1CN(C(=O)c2ncoc2C2CC2)CCO1",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "CCc1nocc1CN(C)C(=O)c1ccc2[nH]c(=O)n(C)c2c1",
        "CC[NH+]1CCN([C@@H]2CCN(C(=O)Cc3cncs3)C2)CC1",
    ],
    [
        "CC(C)C[C@H]1C(=O)NCCN1C(=O)c1cc(O)nc(C(C)C)c1",
        "O=C(Cc1ccc(-n2cnnn2)cc1)Nc1cnn(C[C@@H]2CCCO2)c1",
        "Cc1nc(NCc2cccc(N3CCCCC3=O)c2)cc(-c2ccccn2)n1",
        "O=C(c1ccnn1C1CCCC1)N1CCN(c2cncc3ccccc23)CC1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H",
        "N#Cc1ccc(C(=O)N2CCCC[C@H]2C(=O)[O-])cc1",
        "C[C@@H](C(=O)NCc1ccc(C(=O)N2CCOCC2)cc1)N1CCc2ccccc21",
        "Cc1c(CC(=O)N2CC[C@@H](S(C)(=O)=O)C2)nnn1-c1ccccc1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "CN(C)c1cccc(S(=O)(=O)N2CCC[C@@H](n3cc(C(=O)[O-])cn3)C2)c1",
    ],
    [
        "CCc1nn(C)cc1C(=O)N[C@@H]1c2ccccc2C[C@@H]1O",
        "COc1ccccc1CN(C[C@H]1CCCO1)C(=O)c1cccc2[nH]c(=O)oc12",
        "O=C(N[C@H]1CCO[C@@H]1c1ccc(Cl)c(F)c1)[C@@H]1C[C@@H]",
        "CC[C@@H](CC#N)NC(=O)c1nnc2ccc(Br)cn12",
        "O=C(Nc1cccc(C(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c1)[C@@",
        "Cn1c(=O)[nH]c2ccc(C(=O)NCC[C@H]3CN(c4ncnc5[nH]ncc45",
        "CSC[C@@H](C)C(=O)N1CCOC[C@H]1CC(=O)[O-]",
        "C[C@H]1CN(c2nnc(-c3ccccc3)n2C[C@@H]2CCCO2)CCS1",
        "COCC1(C)CCN(C(=O)Nc2ccc(-n3cccn3)nc2)CC1",
        "O=C(c1ncsc1Nc1ccccc1)N1C[C@@H](CO)[C@@H](CO)C1",
    ],
    [
        "NC(=O)C1(c2ccccc2)CCN(C(=O)N[C@@H]2CCN(c3ccc(Cl)c(F)c",
        "CCc1cccc(C)c1NS(=O)(=O)c1cnc2n1CCC2",
        "O=C(Nc1cnn(-c2ncccc2F)c1)C1(F)CCC1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)NCc1nc2ccccc2n1CC",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "O=C(NC[C@H]1CCC[N@H+](Cc2ncon2)C1)c1cccc(-n2cncn2)c1",
        "Cc1cccc2nc(N3CC[C@H](S(C)(=O)=O)C3)sc12",
        "C[C@@H]1Cc2ccccc2N1C1CCN(C(=O)[C@H]2CCCN(C(=O)c3ccc4[",
        "CCc1onc(C)c1NS(=O)(=O)c1ccc(OCC(=O)[O-])c(Cl)c1",
        "CC(=O)Nc1ccc(NC(=O)c2cccc3ncn(C)c23)cc1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "C[C@H]([NH3+])[C@@H]1CCCN(c2ccc(-c3ccc(Cl)s3)nn2)C1",
        "CNC(=O)[C@@H]1CCC[C@H]1[NH2+][C@H]1[C@@H]2CCO[C@@H]2C12CCCC2",
        "CCc1cc(N2CC[C@@H](n3cc(C(=O)[O-])nn3)C2)c2ccccc2n1",
        "C[C@@]1(c2cnccn2)NC(=O)N(Cc2noc3c2CCCC3)C1=O",
        "NC(=O)C1(c2ccccc2)CCN(C(=O)N[C@@H]2CCN(c3ccc(Cl)c(F)c3)C2)CC",
        "O=C(NCc1ccc2c(n1)CCCC2)C1CCN(C(=O)N2CCCC2)CC1",
        "CCOc1c(Cl)cc(CNc2ccc3nc(C)nn3n2)cc1OC",
        "O=C(C[C@@H]1CCc2ccccc2C1)N1CCC(c2nnc3n2CC[NH2+]C3)CC1",
        "CNc1cccc(-c2cn(Cc3cc(C(F)(F)F)nn3C)nn2)c1",
    ],
    [
        "Cc1ccc(NC(=O)CCn2c(=O)[nH]c(=O)c3ccccc32)cc1NS(",
        "CCc1ccsc1C(=O)N1CCC(N2CCNC2=O)CC1",
        "CCS(=O)(=O)N1CCN(c2nnc(-c3cccn3C)n2C)CC1",
        "COCC1(C)CCN(C(=O)Nc2cnn(-c3ncccn3)c2)CC1",
        "O=C(c1ccccc1)N1CCN(C(=O)C2CCOCC2)CC1",
        "O=C(NCc1ccc(Br)s1)NC[C@H]1CCCO1",
        "O=C(NCc1ccc(-n2ccnc2)nc1)Nc1ccc(CN2CCCC2=O)cc1",
        "c1ccc2c(c1)OCC[C@@H]2c1nc(-c2ccc3[nH]cnc3c2)no1",
        "O=C(CCCc1c[nH]c2ccccc12)N[C@@H]1C[C@H](Cn2ccnc2",
        "CS(=O)(=O)[C@@H]1CCN(C(=O)c2cccnc2N2CCCC2)C1",
    ],
    [
        "CCn1nc(C)c(C[N@H+]2CCc3[nH]cnc3[C@@H]2c2ccc(F)cc2)n1",
        "COC(=O)c1csc(NC(=O)[C@@]2(C)CCN(C(C)=O)C2)c1",
        "CNc1cccc(-c2cn(Cc3cc(C(F)(F)F)nn3C)nn2)c1",
        "COc1ccccc1[C@@H](CNC(=O)N1CC[C@](F)(CO)C1)[NH+]1CCCC1",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)Nc1cnn(CCOC)c1",
        "Cc1cccc(CN(C)C(=O)c2cnn3ccc(C)cc23)c1",
        "CC(C)N(C)C(=O)C1CCN(C(=O)CCc2ccc(C(=O)[O-])cc2)CC1",
        "Cc1n[nH]c(-c2ccc(NC(=O)CN3C(=O)N[C@](C)(c4ccc5ccccc5c4)C3=",
        "O=C(NCc1ccc2c(n1)CCCC2)C1CCN(C(=O)N2CCCC2)CC1",
        "CCn1cc(Cl)cc1C(=O)N[C@@H](C(=O)[O-])C(C)C",
    ],
    [
        "CCn1nc(C)c(Cn2cnc3c(sc4ncccc43)c2=O)n1",
        "O=C(Nc1cnn(C[C@H]2CCCO2)c1)N[C@H](CN1CCCC1=O)c1ccccc1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc3n",
        "CS(=O)(=O)NCc1cn(-c2cccc(C(F)(F)F)c2)nn1",
        "Cc1ccc2c(c1)C(=O)N(CCCC(=O)N1CCC(C(=O)NCc3ccc(F)cc3)CC1)C2=O",
        "Cc1nc(C(=O)N(C)C)nc(N2CC[C@H](Nc3ncc(C#N)cc3F)C2)c1C",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc1ccccc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COc1cccc(C(=O)NCC(=O)N[C@@H]2CCC(=O)N[C@H]2[C@@H]2CCCO2)c1",
        "Cn1nc(-c2ccccc2)c2c(NC(=O)[C@H]3C[C@@H]3C(F)F)n[nH]c21",
    ],
    [
        "CC(=O)N1c2ccc(S(=O)(=O)N3CC4(CCC4)c4c(F)cccc43)cc2C[C@@H]1C",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C)noc3",
        "COC[C@H](Nc1ccc2nc(C3CC3)oc2c1)C1CCOCC1",
        "C[C@@H](NC(=O)C(Cc1ccccc1)Cc1ccccc1)c1ccc2c(c1)CC(=O)N2",
        "O=C(NCc1noc2c1CCCC2)N[C@H]1CCCN(Cc2ccc(F)cc2F)C1=O",
        "CC(C)c1cccc(S(=O)(=O)NC(=O)CC[C@H]2Cc3ccccc3NC2=O)c1",
        "COc1ccc(-c2nc(CCNC(=O)c3sc(C)nc3C)co2)cc1",
        "CCc1csc(CC(=O)N[C@@H](CN2CCOCC2)c2ccc(C)cc2)n1",
        "O=C(NCCc1ccc2cn[nH]c2c1)N1CCCC1",
        "Cc1csc([C@H]2CCCN2C(=O)c2ccc3cc[nH]c3n2)n1",
    ],
    [
        "O=C(CN1CCc2ccccc2C1=O)NCc1ccccc1",
        "Cc1cc(-c2cc(C(=O)NCc3cccc([C@]4(C)NC(=O)NC4=O)c3)c3c(C",
        "O=C(CNC(=O)[C@@H]1CCC[NH2+]1)Nc1ccc2c[nH]nc2c1",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "C[C@H]1C[C@@H]1C(=O)Nc1n[nH]c2nc(C(F)(F)F)ccc12",
        "Cn1ccnc1[C@]1(CNC(=O)c2ccc(-c3nnn[nH]3)cn2)NC(=O)NC1=O",
        "Cc1n[nH]c(C)c1CC(=O)N1CCO[C@H](c2ccccc2)C1",
        "O=C(CC[C@@H]1CCCOC1)NS(=O)(=O)Cc1cccc(F)c1",
        "Cc1n[nH]c(-c2ccc(NC(=O)CN3C(=O)N[C@](C)(c4ccc5ccccc5c4",
        "NC(=O)c1cn(CC(=O)N2CCC[C@@H]2c2ccc(F)cc2)c2ccccc12",
    ],
    [
        "Cc1ccccc1Cc1noc(C2CCN(C(=O)N(C)C)CC2)n1",
        "CC(C)Cc1cc(N2CCC(Cc3nncn3C)CC2)ncn1",
        "CCNC(=O)N1CCC[C@@H]1c1nc(-c2ccccc2)c(C(C)C)o1",
        "COc1cc(C)c([C@H](C)NC(=O)N2CCC2)cc1OC",
        "O=C(c1n[nH]c2ccc([N+](=O)[O-])cc12)N1CC[C@H](C(F)(",
        "CC(C)Cn1ncc(C(=O)NCC2(O)CCCCCC2)c1C(F)F",
        "Cc1cccc(-c2cccc(C(=O)N3C[C@H](CO)[C@@H](CO)C3)c2)c",
        "C[NH+]1CCC(CNC(=O)CNC(=O)c2ccc3ccccc3c2)CC1",
        "O=C1Nc2ccccc2O[C@H]1CC(=O)N1CCC(c2c[nH]c3ncccc23)C",
        "Cc1ccc(S(=O)(=O)N[C@@H]2C=C[C@H](C(=O)[O-])C2)cc1C",
    ],
    [
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc54",
        "O=C(NCc1ncccn1)c1ccc2c(c1)C[C@H](c1ccccc1)OC2=O",
        "Cc1cc(S(=O)(=O)NOCC(=O)[O-])ccc1OC(C)C",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "CCc1nc([C@@H](C)NC(=O)N[C@@H]2CCCc3cn[nH]c32)n[nH]1",
        "Cn1ccc2ccc(NC(=O)N3CC[C@H](C(C)(C)C)C3)cc2c1=O",
        "Cc1nc(C2CC2)nc(C)c1C(=O)NCC1CCC1",
        "NC(=O)C1(c2ccccc2)CCN(C(=O)N[C@@H]2CCN(c3ccc(Cl)c(F)c",
        "CC1(c2nc(-c3ccnc(N4CCOCC4)c3)no2)CC1",
        "C[C@]1(C(=O)[O-])CCC[N@@H+]1CC(=O)Nc1ccc(F)cc1Cl",
    ],
    [
        "C[C@H](NC(=O)c1ccc(Nc2ncccn2)cc1)[C@H](O)c1ccccc1",
        "O=C(NCc1ccc(Oc2cccnc2)c(F)c1)N1CC[C@H](C2CCOCC2)C1",
        "CCCNC(=O)C[NH+]1CCC(Nc2cc(C(F)(F)F)nc3ncnn23)CC1",
        "Cc1ccc(Cl)c(S(=O)(=O)NC(=O)C(C)C)c1Cl",
        "CS(=O)(=O)c1ccc(NC(=O)NC2CCOCC2)cn1",
        "O=C([C@@H]1CCc2[nH]ncc2C1)N1CCC[C@@H]1c1ccccc1",
        "CCOc1ccc(CNC(=O)N2CCC[C@H](C(=O)NC)C2)cc1F",
        "O=C(c1c[nH]nc1-c1cc2ccccc2o1)N1CCO[C@]2(CCCOC2)C1",
        "O=C(N[C@@H](Cc1ccccc1)C(=O)N1CCCC1)[C@@H](O)[C@@H](O)c1nc2cc",
        "C[C@@H](NC(=O)c1c[nH]nc1-c1cccnc1)c1ccc(Cl)cc1",
    ],
    [
        "CC(C)CCn1ncc(NC(=O)[C@@H]2CC23CCOCC3)c1C(C)C",
        "CCc1cccc(C[NH2+][C@H]2CCC(=O)N[C@@H]2c2cnn(C)c2)c1",
        "C[C@H](COc1ccc(F)cc1F)NC(=O)N1CCC2(CCO2)CC1",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OC",
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc5",
        "Cc1nn(C)c2nc(-c3cccs3)cc(C(=O)NCc3ccccc3Cn3cncn3)c12",
        "CNC(=O)C1(c2nc(-c3ccc(N4CCCC4=O)cc3)no2)CCC1",
        "C[C@@H](NC(=O)N1C[C@H](c2ccccc2)[C@H]2COCC[C@H]21)c1",
        "COc1ccccc1OCCN(C)C(=O)c1cc(=O)[nH]c2ccccc12",
        "CNC(=O)[C@H]1CCCCN1C(=O)Cc1ccc2c(c1)CCO2",
    ],
    [
        "Cc1ccc(S(=O)(=O)Cc2nnc(C)n2C)cc1C",
        "O=C(NCC(=O)N1CCc2ccccc2C1)[C@@H]1C[C@H](O)CN1C(=O)OCc",
        "O=C(NCc1ccc(F)cc1)C1CCN(C(=O)C2(O)CCCC2)CC1",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "CCS(=O)(=O)N1CCN(C(=O)C2(c3ccccc3)CC2)CC1",
        "Cc1ccc(CCC(=O)N[C@@H]2CCCCNC2=O)c(C)c1",
        "C[C@@H](CO)NC(=O)Nc1cnc(-c2cccc(C(F)(F)F)c2)cn1",
        "Cc1cccc(F)c1CNC(=O)[C@H]1CC(=O)N(C2CCCC2)C1",
        "CC1(C)CCC(CNC(=O)Cc2nc3ncccn3n2)CC1",
        "CN(CCCNc1cccc2c1NC(=O)CO2)c1ccccc1",
    ],
    [
        "Cc1cc(COCC(=O)N(C)c2ccc(Br)cn2)no1",
        "C[C@@](O)(CNC(=O)[C@@H]1CCCN(C(=O)Cc2ccccc2)C1)c1ccc(F)cc1",
        "Cc1nocc1NC(=O)NC[C@](C)(O)c1ccc(F)cc1",
        "CC(C)(C)c1cc(Cn2cnc3sccc3c2=O)no1",
        "COc1ccc([C@@H]2CCCN2C(=O)Nc2cc(C(F)(F)F)ccc2N2CCOCC2)cc1OC",
        "Cc1cc(-c2noc(CCC(=O)N3CCC[C@@H]3C[C@H](O)c3ccc(F)cc3)n2)ccc1F",
        "Cn1cc(NC(=O)N2CCOC3(CCCC3)C2)c(-c2ccccc2)n1",
        "Cc1cc(C)c(S(=O)(=O)N2CCC=C(c3cnn(C)c3)C2)s1",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "O=C([O-])c1cc(F)ccc1NS(=O)(=O)c1c[nH]c2ncccc12",
    ],
    [
        "C[C@@H](NC(=O)C(Cc1ccccc1)Cc1ccccc1)c1ccc2c(c1)CC(=O)",
        "Cn1c(=O)[nH]c2ccc(C(=O)NCC[C@H]3CN(c4ncnc5[nH]ncc45)c",
        "N#Cc1cc(Br)cc(S(=O)(=O)NC(=O)Cc2ccc(F)cn2)c1",
        "O=C(Nc1ccc(C(=O)N2CCCCCC2)cc1)c1cn([C@H]2CCOC2)nn1",
        "CCOC(=O)Cn1cnc2cc(Cl)ccc2c1=O",
        "C[C@H]([NH2+]Cc1ccc2cn[nH]c2c1)c1ccccc1F",
        "C[C@H](Cc1cccc(Cl)c1)C(=O)N1CCCN(C(N)=O)CC1",
        "O=C(Nc1ccc2c(c1)COC2)c1coc(C2CCOCC2)n1",
        "COc1cc(C)c(C(=O)N2CCC[C@H]2c2nncn2C)cc1C(=O)[O-]",
        "C[C@@H](NC(=O)N1CCc2nccnc2C1)c1cccc(Cl)c1",
    ],
    [
        "O=C(COc1ccccc1F)N1CCCCC[C@@H]1c1ncon1",
        "CCc1cccc2c1N(C(=O)c1cc(OC)no1)CC2",
        "COc1cccc(C(=O)NCC(=O)N2CCC(c3c[nH]c4ncccc34)CC2)c",
        "O=C1[C@@H]([N@H+]2CCC[C@@H](Cn3ccnn3)C2)CCN1C1CC1",
        "CCc1c(NCc2ncnn2-c2ccccc2)cnn1-c1ccccc1C",
        "COc1cc2c(cc1F)CC[C@@H]2NC(=O)Cn1c(C)nc2ccccc2c1=O",
        "Cc1c(CCC(=O)N2CCN(C(=O)c3ccccc3)CC2)cnn1C",
        "CC1(C)OCC[C@H]1NC(=O)c1ccc(C(=O)[O-])cc1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH",
        "O=C(Cc1ccc(O)cc1)N1CCC[C@@H]1C[C@H](O)c1ccccc1",
    ],
    [
        "CCCC(=O)N1CCC[C@H]1C(=O)N[C@@H]1COc2ccccc2C1",
        "COc1ccc(Cl)cc1C(=O)N[C@H]1CCC(=O)NC1=O",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "O=C1CCCN1Cc1ccc(C(=O)N2CCC[C@@H](N3CCCS3(=O)=O)C2)cc1",
        "COc1cccc(CN(C)C(=O)c2ccc(C(=O)[O-])cn2)c1",
        "Cn1nc2c(c1NC(=O)[C@H]1CCCN(C(=O)Cc3ccccc3)C1)CCC2",
        "Cc1ccc2c(c1)C(=O)N([C@H](C)C(=O)Nc1cccnc1)C2=O",
        "Cc1cc(C)c(NC(=O)[C@H]2C[C@@H]2c2ccccc2C)c(C)n1",
        "Cc1cc(C)c(N2C[C@@H](C(=O)NCc3ccnc(-n4ccnc4)c3)CC2=O)c(C)c1",
        "O=C1Cc2cc(CCCc3nc(-c4ccc(F)cc4)no3)ccc2N1",
    ],
    [
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
        "COc1cc(CCO)ccc1NC(=O)[C@H]1CC1(C)C",
        "Cc1nnc2n1C[C@H](C(=O)NCC1(c3ccc(F)cc3Cl)CC1)CC2",
        "Cc1c(C2CC2)n[nH]c1NC(=O)c1cc(C#N)cc(N(C)C)c1",
        "Cn1ccnc1[C@@]1(CNC(=O)c2ccc(O[C@H]3CC3(F)F)cc2)NC(=O)NC1=O",
        "CN(Cc1ccc(F)cc1Cl)C(=O)c1cnns1",
        "O=C(NC[C@@H]1CCC[C@@]12NC(=O)NC2=O)Nc1ccn(-c2cccc(C(F)(F)F)",
        "CC(C)CC(=O)N1CCC(NC(=O)NC2CCOCC2)CC1",
        "O=C(N[C@H]1CCc2ccc(F)cc21)c1c[nH]nc1-c1ccccc1",
        "CN(CC1CC1)C(=O)Cn1ccc(-c2ccccc2)nc1=O",
    ],
    [
        "CCOc1ccc(NC(=O)N[C@H]2CCc3[nH]ncc3C2)cc1OC",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1c(F)cccc1F",
        "CCc1sc(C(=O)NCc2nc(C)c(C(=O)[O-])s2)cc1C",
        "O=C(NC[C@@H]1CC[N@H+]1C1CCOCC1)c1cc(F)c2ncccc2c1",
        "COc1ccccc1NC(=O)Cc1noc([C@@H]2Cc3ccccc3N2C(C)=O)n1",
        "Cc1cccc(C(=O)N2CCOC[C@H]2CC(=O)[O-])c1Cl",
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "Cc1noc([C@@H]2C[C@H](CNc3cnccn3)[C@@H](O)C2)n1",
        "Cc1cnc(C(=O)Nc2cccc(-c3nc(C)c(C)[nH]3)c2)cn1",
    ],
    [
        "Cc1ccc(S(=O)(=O)NC(=O)c2ccco2)cc1C",
        "O=C(Nc1ccccc1N1CCCC1)N[C@H]1[C@H]2CCO[C@H]2C12CCC2",
        "Nc1nccc([C@H]2CCCN(C(=O)c3cccc(NS(=O)(=O)c4ccc(F)c(F)c4",
        "OCCn1cc(Nc2ccnc(-c3ccccc3)n2)cn1",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
        "CN(C(=O)CS(=O)(=O)c1cc(F)ccc1F)C1CC1",
        "C[N@H+]1CCn2nc(NC(=O)NCc3ccccc3C(F)(F)F)cc2C1",
        "O=C(NC[C@H]1Cc2ccccc2C[NH2+]1)N1CCC2(CC1)CC2(F)F",
        "Cc1nn(-c2ccccc2)c2nc(C(=O)N3CCC([C@H]4C(=O)Nc5ccccc54)C",
        "Cc1nc(C(=O)N2CC=CCC23CCOCC3)nc(N2CC[C@@H]([NH3+])C2)c1C",
    ],
    [
        "CO[C@H]1C[C@H](COc2cccnc2)[N@@H+](Cc2ccnn2C)C1",
        "Cc1cc(NC(=O)c2cccc(F)c2)sc1C(=O)N1CC(C2CCOCC2)C1",
        "COc1ccccc1CC(=O)N1CCC(CC(=O)[O-])CC1",
        "Cc1c[nH]c(=O)n1-c1cccc(C(=O)N2CCc3c(ncn3-c3ccc(F)cc3",
        "O=C1CCCc2cc(C(=O)N(CCCO)Cc3cccc(Cl)c3)ccc2N1",
        "Cc1n[nH]c(C)c1CC(=O)N[C@H]1CC(C)(C)Oc2ccccc21",
        "CC(=O)Nc1ccc(NC(=O)c2ccoc2CN2c3ccccc3C[C@H]2C)cc1",
        "Cc1ccc(CNc2nccc(C(C)(C)C)n2)c(N2CCCC2)n1",
        "Cc1cc(C(=O)N2CCC(CCC(=O)[O-])CC2)ccn1",
        "CN(c1ccccc1)S(=O)(=O)c1csc(C(=O)[O-])c1",
    ],
    [
        "C[C@@H]1Cc2ccccc2N1C1CCN(C(=O)[C@H]2CCCN(C(=O)c3cc",
        "Cc1cc(C(=O)[O-])ccc1S(=O)(=O)N[C@H](C)c1c(C)noc1C",
        "O=C(NCc1ccn(C2CCCC2)n1)c1cncnc1",
        "Cc1[nH]nc(C(=O)N2CCC(Oc3ccccc3Cl)CC2)c1C",
        "COc1cc(C)c([C@H](C)NC(=O)CN2CCOC3(CCC3)C2)cc1OC",
        "C[C@H](NC(=O)c1ccc(-n2cccn2)cc1)[C@@H](C)C(=O)[O-]",
        "O=C1NCc2nccc(N3CCC(c4ccccc4)CC3)c21",
        "O=C(NC[C@H](O)c1cccc(Cl)c1)c1c[nH]nc1-c1ccc(Cl)s1",
        "CC(C)n1cccc1C(=O)N[C@@H]1CC(=O)N(C(C)(C)C)C1",
        "O=C([C@H]1CCCc2ccccc21)N1CCC(c2c[nH]c3ncccc23)CC1",
    ],
    [
        "CNc1ccc(C(=O)NCc2cccc(N3CCOCC3)c2)cn1",
        "CN(C)C(=O)N1CCN(C(=O)c2ncnc3ccsc23)CC1",
        "C[C@H](O)C(=O)N1CCN(C(=O)c2cn(Cc3cccs3)nn2)CC1",
        "C[C@H]1Cc2c(C(=O)N3CCc4[nH]nc(C(F)(F)F)c4C3)n[nH]c2[C@@H]",
        "O=C(C[C@@H]1CCCC(=O)N1)NCc1nnc(C2CC2)n1C1CC1",
        "[NH3+]Cc1nnc(N2CCCCC2)o1",
        "COCCn1cc(NS(=O)(=O)c2cnc3c(c2)c(C)nn3C)cn1",
        "Cc1n[nH]c(-c2ccc(NC(=O)CN3C(=O)N[C@](C)(c4ccc5ccccc5c4)C3",
        "CCc1nc([C@@H]2CCCN2C(=O)Nc2ccncc2)no1",
        "O=C([O-])c1coc(C[N@@H+]2CC=C(c3ccc(F)cc3)CC2)n1",
    ],
    [
        "O=C(Nc1cccc(Cn2nc3ccccn3c2=O)c1)N1CCC[C@H](c2cc3ccc",
        "CO[C@H]1C[C@@H](N(C)C(=O)NC[C@@H]2CCCOC2)C1",
        "Cc1cc(F)ccc1-n1ccc(C(=O)N2CCc3ccccc3[C@H]2CO)n1",
        "O=C(N[C@H]1CCc2ccc(F)cc21)c1c[nH]nc1-c1ccccc1",
        "Cc1ccc(CC(=O)N2CCC(NC(=O)c3ccccc3)CC2)cn1",
        "O=C([O-])[C@@H]1CCN(S(=O)(=O)c2cccc(Cl)c2)CC1(F)F",
        "Cc1cccc(-c2nnc([C@H](C)[N@H+](C)CC3CCOCC3)o2)c1",
        "Cc1c(N2C(=O)[C@H]3C[C@H](O)CN3C2=O)nnn1-c1ccc(F)cc1",
        "CCc1ccc(C(=O)N2CC[N@@H+](C)C3(CCOCC3)CC2)o1",
        "CS(=O)(=O)N1CC[C@H](CNc2ncnc3ccccc23)C1",
    ],
    [
        "C[C@@H]1CCCN1C(=O)c1ccc(-c2nnn[nH]2)cc1",
        "O=S(=O)(NCc1cccnn1)c1ccccc1Br",
        "Cn1cc(-c2cncc(C(=O)N[C@H]3CC[C@H](O)CC3)c2)cn1",
        "CCOc1cn(-c2ccccc2)nc1C(=O)N1CCN(c2ncccn2)CC1",
        "Cc1c[nH]c(=O)n1-c1cccc(C(=O)N2CCc3c(ncn3-c3ccc(F",
        "Cc1nn(Cc2ncc(-c3ccccc3)o2)c(C)c1[C@@H]1COCCN1C",
        "O=C(NCC1([C@H](O)c2ccccc2)CC1)c1cc(Cl)cc2cccnc12",
        "O=C1NCc2c(NC(=O)N3CCCC4(CCCCC4)CC3)cccc21",
        "CCOc1ccccc1C(=O)N1CCC[C@@H]1C(=O)NCc1nc2ccccc2n1",
        "Cn1cc(S(=O)(=O)N[C@@H]2CCc3c(Cl)cccc32)cn1",
    ],
    [
        "NC(=O)c1cccc(Oc2ccc(NC(=O)[C@H]3C[C@@H]3c3ccc(F)cc3)cn2)c1",
        "Cc1[nH]c2ccccc2c1NC(=O)CCC(C)(C)C",
        "COc1ccc(CNC(=O)c2cnn(C(C)C)c2C)cc1",
        "C[C@@H]1Cc2c(C(=O)N3CCC(c4c[nH]c5ncccc45)CC3)n[nH]c2[C@@H]",
        "C[C@@H](NC(=O)[C@@H]1CCCN1C(=O)Cc1ccccc1)c1cccc(O)c1",
        "CC[C@@H]1C[N@H+](C)CCCN1S(=O)(=O)c1nc(C)c(C)s1",
        "COc1ccc(C[NH2+]Cc2nnc3n2CCOCC3)c(Cl)c1",
        "C[C@@H](NC(=O)c1c[nH]nc1-c1cccnc1)c1ccc(Cl)cc1",
        "COc1nc(C)cc(N(C)CC2(O)CCCC2)n1",
        "O=C(OCc1ccccc1)N1CCC[C@](O)(CN2CCOCC2)C1",
    ],
    [
        "O=C(c1cccnc1C(F)(F)F)N1CCS(=O)(=O)CC1",
        "O=C(O[C@H]1CCN(c2ccccc2Cl)C1=O)c1n[nH]c(=O)c2ccccc12",
        "Cc1ccncc1NC(=O)CC(C)(C)c1ccccc1",
        "CCC[C@H]1CCCC[C@H]1CNC(=O)N1CC(=O)N(C)C1",
        "C[C@H](NC(=O)c1c[nH]nc1-c1ccccc1F)c1ccc(NC(=O)c2ccncc2)cc1",
        "NS(=O)(=O)c1cccc(CNC(=O)NCc2cn(Cc3ccccc3)nc2-c2ccccc2)c1",
        "CN1CC[C@@H](NC(=O)Nc2cnn(-c3ccccc3Br)c2)C1=O",
        "O=C([O-])[C@]1(O)CCCN(S(=O)(=O)c2ccccc2Cl)C1",
        "CCOc1ccccc1CNC(=O)[C@@H]1C[C@@H](C)[C@@H](C(=O)[O-])O1",
        "NC(=O)c1cn(CC(=O)N2CCC[C@@H]2c2ccc(F)cc2)c2ccccc12",
    ],
]



- Experiment:
    name: Enrich 3(RDKit2D)

    dataset: datasets/DDS10_RDKIT2D.pkl

    model:
        name: RF
        iterations: 5
        acquisition_size: 20
        acquisition_method: greedy
        use_pairwise: True

    metrics: 
        names: [top-k, top-k-acquired]
        k: [100]
